### ISSUE TITLE
Separate bindhosts for IPv4 and IPv6

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1002]
This has been talked on IRC often, but I was unable to find issue, so I am opening this one as I am starting to see the point.

My shell gives users own IPv6 addresses for reverse DNS, but IPv4 addresses are all shared. If I set bindhost as that address, I am locked out of IPv4. What I want is

* IPv6 bindhost: \<my own domain\>
* IPv4 bindhost: \<empty\>

If https://github.com/znc/znc/issues/241 was also implemented, I would get my rDNS IPv6 most of time, but when IPv6 doesn't work I would get connected anyway with IPv4. Currently all the networks that I am on have IPv6, but they have various issues such as having only one IPv6 server or the IPv6 connectivity being tunnelled and having random tunnel issues.

**Comment by DarthGandalf** [comment]
You can have a domain which resolves to your IPv6 and your IPv4 at the same time, and use that as bindhost configured in ZNC.
Even without #241 you're connected sometimes via IPv6, sometimes via IPv4 with such setup.
Also, #241 does not cause you to prefer IPv6, in fact it may be vice versa esp. in case of tunnels. It would choose whatever protocol connects faster.

**Comment by Mikaela** [comment]
Does that work even if my bindhost is x.example.org and IPv4 reverse DNS is y.example.com?

I didn't think about adding records, but I have done that now and I am just wondering that. Also does ZNC have a method for checking itself where does bindhost resolve to as the previously set AAAA-record had TTL of 12 hours?

**Comment by DarthGandalf** [comment]
ZNC never looks at reverse DNS, it's IRC server's job to do that and show it in hostmask.
ZNC just uses `getaddrinfo()`. It's the resolver's (and also DNS server's) job to honor TTL.

**Comment by Mikaela** [comment]
That appears to work, so I am closing this issue.

**Comment by Mikaela** [comment]
Another question, what happens if the domain points to 0.0.0.0 (A record) and correct address with IPv6? When IPv4 is used, ZNC will act like bindhost was 0.0.0.0?

**Comment by DarthGandalf** [comment]
Should be like that, yep. But not tested.

**Comment by Mikaela** [comment]
I will change it and test it when I restart next time assuming it's after TTL.
