### ISSUE TITLE
Client connect causes "error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol"

### ISSUE THREAD

**Issue by DonRichie** [znc/znc#1006]
Hello,

since some days or maybe weeks I can't connect to my znc instance on my server.
I am using ZNC 1.6.0-2 on Ubuntu 15.04 with Kernel Version 3.19.0-22-generic.
Used Clients: xchat and mirc

When I start ZNC in debug mode the connection to the IRC networks is working fine, all of my clients can't connect.

```
[2015-07-24 03:36:35.361684] _LISTENER == ConnectionFrom(2a02:908:f460:9da0:642a:27dd:b2ff:2c12, 5255) [Allowed]
[2015-07-24 03:36:35.361781] There are [0] clients from [2a02:908:f460:9da0:642a:27dd:b2ff:2c12]
[2015-07-24 03:36:35.383654] src/Csocket.cpp:602 at src/Csocket.cpp:3325
[2015-07-24 03:36:35.383772] src/Csocket.cpp:607 error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
[2015-07-24 03:36:38.449695] _LISTENER == ConnectionFrom(37.201.192.88, 13045) [Allowed]
[2015-07-24 03:36:38.449801] There are [0] clients from [37.201.192.88]
[2015-07-24 03:36:38.474327] src/Csocket.cpp:602 at src/Csocket.cpp:3325
[2015-07-24 03:36:38.474435] src/Csocket.cpp:607 error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
.....
```

I unfortunaly have no idea why the issue suddenly appeared. In the past it was working fine. I am pretty sure SSL/TLS is the problem because when I connect without it everything works fine.

In my configuration file:
```
SSLCertFile = /etc/znc/znc.pem
```

and
```
<Listener listener0>
        AllowIRC = true
        AllowWeb = true
        IPv4 = true
        IPv6 = true
        Port = 1025
        SSL = true
        URIPrefix = /
</Listener>
```

I removed the znc.pem file and restarted znc to generate a new file. Unfortunaly this did not solve my problem.

Well, thank you for reading this. I hope somebody can help me :)

Regards,

Richard

**Comment by KindOne-** [comment]
What does mIRC print with this command? 
```//echo -ag $os $version $sslready```
And what is your ```/server``` line you are using in mIRC?

**Comment by TingPing** [comment]
xchat is outdated and does not support modern TLS versions, upgrade to hexchat for that.

**Comment by teward** [comment]
@TingPing that doesn't solve the mIRC issue.  It does solve the XChat problem.

**Comment by DonRichie** [comment]
@KindOne- 
My operating Windows 8.1 with mIRC 7.42. 
I can't see an output for the /server line. The SSL options are very limited but "Display invalid certificates for approval" is checked.

I installed HexChat and the connection is working. It is necessary to check "Accept invalid certificates", but thats no issue.

Personally I need a windows-gui, a linux-gui and a linux-cli client.
hexchat and irssi (which is also working btw) are fullfilling my needs.

I am happy now, but does somebody have an idea why the behavior suddenly changed?

An update of some TLS-libraries is the only reason I can imagine. My apt log is showing that my ssl libraries are updated from time to time.
I will be available to try stuff if necessary.

And thank you for your fast answers.

**Comment by teward** [comment]
If it very recently started working then you may need to look into what mIRC has done in terms of updates.  It's quite possible they've disabled a protocol that needs to be "on", or default-disable 'good' protocols and use 'old' ones.  Given the "unknown protocol" part of that, that's my guess.

**Comment by KindOne-** [comment]
@DonRichie Well, mIRC 7.42 has builtin ssl/tls support, so you are doing something wrong on your end. Just from looking at your paste and figuring stuff out, I managed to connect to your znc with my mIRC with ```/server your_znc_ip_address_here:+1025```. I have my mIRC set to "Automatically accept invalid certs".

**Comment by DonRichie** [comment]
@KindOne- 
After reinstalling and reconfiguring my mirc I was also able to connect. I don't know why but okay. It was in fact an issue on my side.

Will close the issue now. Thank you very much
