### ISSUE TITLE
Fake CTCP replies sometimes fail to work

### ISSUE THREAD

**Issue by oakkitten** [znc/znc#1016]
I've got the following in `Your Settings` in znc's web console under `CTCP Replies`:

 > VERSION FOO

This works fine (other users are getting `FOO`, I'm getting nothing) unless they execute the command repeatedly, in which case they sometimes get a reply from my client (and I see their requests).

**Comment by DarthGandalf** [comment]
Duplicate of #664 
Fixed in 1.6.0
