### ISSUE TITLE
ZNC strips : from smileys

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1037]
I was wondering when did eyeless smileys become so popular and originally reported this at https://github.com/weechat/weechat/issues/496, but then I opened HexChat which got the same issue so it must be ZNC.

* Debian GNU/Linux 7.8 (wheezy)
* ZNC 1.7.x-git-266-e546ced - http://znc.in
    * IPv6: yes, SSL: yes, DNS: threads, charset: yes

**Comment by jpnurmi** [comment]
Sorry for the inconvenience. The root cause is the overly generalized message parser that was introduced by #1000. #1031 makes such changes to the CMessage type hierarchy that will make it easier to fix this.

**Comment by Mikaela** [comment]
Inconvenience? I have just been wondering why eyeless smileys became so fashionable and when I discovered it's a bug in <s>WeeChat</s>, I don't remember how I have laughed this well :laughing:

**Comment by jpnurmi** [comment]
We could either make ```CMessage::ToString()```
A) always prefix the last parameter with ```:``` regardless of spaces, or
B) take the message type into account.

I've been planning to add ```EType CMessage::GetType()``` after #1031, to avoid having to do so much string comparison with ```CMessage::GetCommand()```. That would be nice for option B.

**Comment by DarthGandalf** [comment]
C) Prefix the last parameter with `:` if last parameter starts with `:`

**Comment by jpnurmi** [comment]
Sounds better )
