### ISSUE TITLE
support for idlerpg / multirpg

### ISSUE THREAD

**Issue by Lord255** [znc/znc#1039]
--- FEATURE ---

hello,
a nice feature would be to add loadable modules for idlerpg and for multirpg. lots of networks are having these.
my idea is that you could set a channel, login and password and of course the bot's name for the network/idle/multirpg.
znc would login to the channel automatically, and use the login and password to login to idlerpg / multirpg.

extra: users could make other useful scripts (so extend the features) of the module(s).

**Comment by neico** [comment]
You can already do this with the perform module,
though without protecting your login data which is something that should be tackled instead...

**Comment by Lord255** [comment]
yeap, i know, but users could write more features such as automatized things to them as well. also i think it wouldn't be that hard to implement. but, as i said, this would be just a feature, so of course this has low priority and perhaps i'm the only one who was thinking about this.

**Comment by Mikaela** [comment]
I don't think this should be implemented as the perform does exactly what is asked for everyone else.

```
/msg *status loadmod --type=network perform
/msg *perform add join #idlerpg
/msg *perform add PRIVMSG idlebot :identify username password
```

**Comment by Mikaela** [comment]
I think this issue could probably be closed.

**Comment by jpnurmi** [comment]
Should anyone have interest in implementing such module, it's probably best to release it as an external module. Just create a repo on GitHub and add a page to ZNC wiki. If the module turns out to be a huge success, maybe it can be reconsidered as a core module. :)

**Comment by bashgeek** [comment]
In case someone comes across this issue via Google, please also checkout this module:
https://wiki.znc.in/Idlerpg
