### ISSUE TITLE
it's impossible to have an empty quit message

### ISSUE THREAD

**Issue by kerio92** [znc/znc#1048]
In ZNC 1.7.x-git-308-eac0af1 it's impossible to not have a quit message, setting the network-level QuitMsg to the empty string uses the user-level QuitMsg, and setting *that* one to the empty string causes it to reset to the default quit message, "ZNC - http://znc.in", as described by https://github.com/znc/znc/blob/eac0af1/src/User.cpp#L1269 .

**Comment by teward** [comment]
And this is a problem... how?

**Comment by KindOne-** [comment]
@teward Some people just don't want a quit message. Its a preference.

**Comment by kerio92** [comment]
A suggested fix can be found in #1049

**Comment by kmark** [comment]
Looks like %empty% is no longer available at least as of ZNC 1.6.3 so there is no longer a way to have an empty quit message. Reopen?

**Comment by dgw** [comment]
The commit that added `%empty%` to the expansions (39d373c) is not included in 1.6.x. It will be included when 1.7 is released. It's less that "there is no longer a way", and more that "there is not yet a way when using stable releases".

**Comment by kmark** [comment]
Ah. Thanks for the clarification.
