### ISSUE TITLE
clientnotify: also inform when clients disconnect

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1073]
I think [clientnotify] as user-level [notify_connect], but noticed that the wiki page doesn't say anything about disconnects (and the module doesn't notify about disconnects), unlike with [notify_connect]. I think they both should also tell when a client disconnects.

[clientnotify]:http://wiki.znc.in/Clientnotify
[notify_connect]:http://wiki.znc.in/Notify_connect

* ZNC 1.7.x-git-347-50ed9ad - http://znc.in
    * IPv6: yes, SSL: yes, DNS: threads, charset: yes
* Debian GNU/Linux 7.9 (wheezy)

**Comment by Zarthus** [comment]
I took a look at this issue but it looks already implemented. Can you confirm if this is no longer a problem?

**Comment by Mikaela** [comment]
I should have started by checking the help, I just assumed it doesn't implement any commands.
