### ISSUE TITLE
[META] mode +r & topic?

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1076]
Currently the channel doesn't require identifying to services, but that could reduce the amount of spam. ZNC has the \*sasl module so more +r shouldn't cause too big issues.

The topic currently says:

> http://znc.in | ZNC 1.6.1: http://wiki.znc.in/ChangeLog/1.6.1 | http://znc.in/nightly | https://github.com/znc/znc | Debian stable: 1.4 is 1.5 year old | 1.2 is 2 years old | 1.0 is 3 years old | Debian oldstable: 0.206 is 3.5 years old | don't randomly PM people | http://blog.max-mehl.com/2014/i-love-znc-because-ilovefs/

I think that at least how old all releases are could be removed or replaced with link to git tags and if mode +r is acceptable mention SASL:

> www.znc.in | ZNC 1.6.1: http://wiki.znc.in/ChangeLog/1.6.1 | http://znc.in/nightly | https://github.com/znc/znc | How old is my ZNC? https://github.com/znc/znc/tags | don't randomly PM people | http://blog.max-mehl.com/2014/i-love-znc-because-ilovefs/ | Trouble joining? http://wiki.znc.in/Sasl

**Comment by Mikaela** [comment]
With bad math and `/who #znc %na` it looks like <100 of 946 aren't identified to services and if they wish to continue being on the channel after netsplit or something removes them, they will surely take a look at identifying.

**Comment by Mikaela** [comment]
And while I am having IRC-monologue there I would also like to point out that I haven't received any more highlight spam than before being visibly op, so I would encourage other ops to get +O flag too.

* https://mikaela.info/english/2015/04/01/keep-the-ops-opped.html

**Comment by KindOne-** [comment]
> ... but that could reduce the amount of spam ....

Clearly you have never seen the totally idle efnet channel.

> .... so more +r shouldn't cause too big issues.

And the random unregistered people that just need to ask one or two questions and never return? Do we just force them to register some nick to ask questions in the channel? Could totally create a ```#znc-unregistered``` and just forward them into that channel and help them in that channel. (I don't like that idea).

> I think that at least how old all releases are could be removed or replaced with link to git tags

I like people on Debian/Ubuntu LTS/etc... with old versions seeing the /topic, knowing they might be on an old version of znc, but everybody knows nobody reads the /topic. /sarcasm 

> And while I am having IRC-monologue there I would also like to point out that I haven't received any more highlight spam than before being visibly op, so I would encourage other ops to get +O flag too.

Clearly we should just OP _THE_ENTIRE_CHANNEL_, I'm sure that will just get rid of all the spam cholby (or whoever that was) creates. When he spams the channel, he goes for all the normal people skipping the op'd/voice'd people, so they don't get highlighted to kick/ban him.  (He knows the existence of the ASM bot and what it does, but oh well). 

> https://mikaela.info/english/2015/04/01/keep-the-ops-opped.html
 
... really? So you don't like freenode logic, who cares.

**Comment by Mikaela** [comment]
> And the random unregistered people that just need to ask one or two questions and never return? Do we just force them to register some nick to ask questions in the channel? Could totally create a #znc-unregistered and just forward them into that channel and help them in that channel. (I don't like that idea).

I think it's very unlikely for people on freenode to never have need for registered nick even if they asked #znc only one question. I am not suggesting any forwards as `+r` clearly tells you that you must be registered to join #znc.

> I like people on Debian/Ubuntu LTS/etc... with old versions seeing the /topic, knowing they might be on an old version of znc, but everybody knows nobody reads the /topic. /sarcasm

If no one reads the topic it doesn't matter what it says.

> Clearly we should just OP THE_ENTIRE_CHANNEL

Won't work in freenode.

> ... really? So you don't like freenode logic, who cares.

There are explanations on why if you ever clicked that link.

**Comment by Zarthus** [comment]
There's a lot of spam? It honestly hasn't bothered me.

I don't think these precautions are necessary, and if anything I'd rather see `+q $~a` than `+r`.

**Comment by DarthGandalf** [comment]
> I think it's very unlikely for people on freenode

Are people who saw "irc.freenode.net" on ZNC wiki and joined to ask some question considered to be "people on freenode"?

**Comment by Mikaela** [comment]
> Are people who saw "irc.freenode.net" on ZNC wiki and joined to ask some question considered to be "people on freenode"?

How many people you know that never do anything at freenode?

I can see that this issue doesn't seem to be getting so much support and since we have Sigyn (freenode utility bot that /kills nick spammers) since sometime after opening this issue I think this can be closed.

**Comment by DarthGandalf** [comment]
> How many people you know that never do anything at freenode?

Every new user of IRC who has some question about ZNC. We shouldn't discriminate them.

**Comment by jpnurmi** [comment]
What about a separate +r #znc-dev channel?

**Comment by Mikaela** [comment]
What would it be used for? From experience it looks like separate dev/support channels don't work and another not working thing is separating offtopic from main channel when it doesn't go too offtopic.

**Comment by jpnurmi** [comment]
I'd forward all GitHub notices there instead. Discussion limited to ZNC
development. I'm here to develop this thing, not to babysit some wannabe
trolls.

Where does it not work? It works great for a much larger project that I'm
affiliated with. It's imho a very sensible thing to do when the community
channel gets crowded.

On Sat, Sep 19, 2015, 12:54 Mikaela Suomalainen <notifications@github.com>
wrote:

> What would it be used for? From experience it looks like separate
> dev/support channels don't work and another not working thing is separating
> offtopic from main channel when it doesn't go too offtopic.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/znc/znc/issues/1076#issuecomment-141645494>.
>
-- 
J-P Nurmi

**Comment by Mikaela** [comment]
That makes sense.

For example #ircv3 (but the dev channel is not used and the whole thing is dev) or Chromium (which made  the mistake of calling dev channel #chromium and support channel of #chromium support (which is probably why it doesn't work and guess where do people go looking for support...))

**Comment by Mikaela** [comment]
I assume `+q $a` isn't any more welcome than mode +r, but it's the best way to manage botnet joining to the channel and starting spamming temporarily until staffers do their killing/lining.

**Comment by Zarthus** [comment]
botnets are only temporary, setting +r at the time of the event hasn't harmed anyone.
