### ISSUE TITLE
unable to connect to znc when using 4096 bit key signed cert, only 2048 bit

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [znc/znc#1081]
title says it all. znc webadmin or bnc wont load when using a signed 4096 cert. it works with a signed 2048 cert only

**Comment by Mikaela** [comment]
And you have followed http://wiki.znc.in/Signed_SSL_certificate ?

@kerio92 you are more familiar with ZNC & SSL than me.

**Comment by berrythesoftwarecodeprogrammar** [comment]
yep. did the same thing for both certs. 2048 works. 4096 doesnt

**Comment by Mikaela** [comment]
And you are sure that the issue is with ZNC and not your client?

Could you also add the information that was asked when you opened this issue?

* https://github.com/znc/znc/blob/master/CONTRIBUTING.md#reporting-bugs

The information I think is needed this time is:
* `/znc version`.
* your OS/distribution version.
* what `znc -D` says when you connect to ZNC with the bigger certificate?

**Comment by berrythesoftwarecodeprogrammar** [comment]
yes because i tried the webadmin with my browser too. webadmin on 4096 didnt work but it did on 2048. znc just seemed completely inaccessible with 4096.

<*status> ZNC 1.6.1 - http://znc.in
<*status> IPv6: yes, SSL: yes, DNS: threads, charset: no

Centos 6

ill try znc -D soon

**Comment by berrythesoftwarecodeprogrammar** [comment]
ok i feel really stupid now
[2015-09-13 01:01:04.890403] src/Csocket.cpp:1680 Error with PEM file [/home/brr/.znc/znc.pem]
[2015-09-13 01:01:04.890449] src/Csocket.cpp:602 at src/Csocket.cpp:1681
[2015-09-13 01:01:04.890476] src/Csocket.cpp:607 error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch

i tried some other certs and its working now. so i mustve made a mistake when creating the pem file for my domain which i just cat'd into znc.pem or something. signed 4096 certs for other domains are working with znc so it was just an issue with one of them. :|

**Comment by Mikaela** [comment]
At least it wasn't a bug or nothing serious and thank you for pointing to making #1082 :)
