### ISSUE TITLE
reconnect causes all open network windows to connect to the same one (quite possibly ZNC unrelated)

### ISSUE THREAD

**Issue by Nihim** [znc/znc#1083]
As per the title it most likely is caused by mirc and not znc but this way I can be sure it's not znc.

So when my router changes IP the loss of connectivity, almost always on reconnect, has all open windows (a window == individual network) connect to the same znc network, so I end up with multiples of the same network / channels.

As far as I see it mirc gets confused and connects on all with the default selected network instead of trying to reconnect to each individual different network.

Any chance this can be caused by znc as well? If it's certain it's not znc then I can take this over to mirc forums.

Cheers

**Comment by Mikaela** [comment]
`/msg *status loadmod disconkick`

In the master branch the disconkick module has been merged to core, because Pidgin also suffered this issue.

I believe this can be closed.

**Comment by Mikaela** [comment]
The Pidgin issue was https://github.com/znc/znc/issues/968 and this could well be duplicate of it. I am surprised that no other mIRC user has reported this as it's so popular or maybe those users just have loaded the disconkick module.

**Comment by jpnurmi** [comment]
Make sure to specify the network either in username (```username/network```) or password (```username/network:password```), so that ZNC knows which network you are connecting to.

**Comment by KindOne-** [comment]
As far as your mIRC issue, sounds like this. http://forums.mirc.com/ubbthreads.php/topics/244084/Re:_Connect_to_networks

**Comment by Nihim** [comment]
@jpnurmi I use `username/network:password` but that doesn't help since after the 1st network which works on start of mirc rest are opened by a script.

@Mikaela it's the client disconnecting from ZNC due to IP change, not ZNC disconnecting from the IRCd

@KindOne- cheers one of your solution seems like the solution I have to try :P Atm I use the native on start up and rest networks are created by a remote script. As such a default network is selected for the first network.

Will use the on:start to have all of them and if needed I will remove the servers.ini

**Comment by Mikaela** [comment]
In that case this is fully mIRC bug and there is nothing ZNC could do. You also appear to be going against the [ZNC wiki instructions for mIRC.](http://wiki.znc.in/MIRC)

**Comment by Nihim** [comment]
That is very much true, I never saw that article, which includes KindOne's solution.
I just implemented it on my client and everything looks dandy, will have to wait for that next IP change sponsored as always by my ISP.
Thank you all for your swift & helpfull replies.

Should I close this or wait till I have "verified" it works as intended?

**Comment by Mikaela** [comment]
I think you can close this, because
1. this is not a ZNC issue.
2. there are so many mIRC users that they would have said if the wiki instructions don't work.

**Comment by Nihim** [comment]
Yea 2 is quite a valid point :)
