### ISSUE TITLE
[meta] Move from GitHub IRC hook to notifico?

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1088]
Currenty commit announcements at IRC use the GitHub hook connecting to ZNC-Linker (down at the moment) and Travis has separate announcements configured in `.travis.yml`

GitHub could send Travis status directly to Notifico with the `status hook` which might also work with appveyor in the future.

How I would do it:

1. register at http://n.tkte.ch/ (no SSL there either (wiki.znc.in apparently currently waits for LetsEncrypt)).
2. create a new project, ZNC
3. add a new channel for project ZNC, chat.freenode.net 6697 SSL
4. create a new hook for project ZNC and copy-paste it to https://github.com/organizations/znc/settings/hooks where it's set to *send me everything*
    * less work if e.g. #787 happens
5. remove the Travis IRC notification.

This is just how I would do it, other ways are also equally valid such as importing repositories, but I prefer the organization approach or hand picking which events to send.

This would also fix https://github.com/travis-ci/travis-ci/issues/1094, forks sending IRC status notifications to #znc which isn't needed.

**Comment by Zarthus** [comment]
should consider hosting it yourself, and stop relying on third party entirely.

**Comment by DarthGandalf** [comment]
For now, Travis is switched to use ZNC-Linker.
AppVeyor status combined with Travis status would be nice; no need to keep this issue though.
