### ISSUE TITLE
Please either move to spaces instead of tabs or add at least vim modelines telling to not use spaces instead of tabs

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1090]
##

**Comment by Zarthus** [comment]
Spaces are a lot more consistent, and less confusing/messy to apply and work with.

:+1:

**Comment by Mikaela** [comment]
* http://sprunge.us/OcQa
   * starts from 12:00:23
      * but you can skip to 14:46:55

**Comment by DarthGandalf** [comment]
I have this in vim:
```vim
set ts=4
set sw=4
set sts=4
```

**Comment by Mikaela** [comment]
I don't think I can change my global config just because of one project while Vim has modelines that the file can use to inform what should be done witw it.

* http://vim.wikia.com/wiki/Modeline_magic

**Comment by Mikaela** [comment]
Based on IRC, didn't we decide that 4 spaces instead of one tab is acceptable?

**Comment by Zarthus** [comment]
it wasn't really a decision, just a preference of those whom were present at the time.

**Comment by DarthGandalf** [comment]
This is done already
