### ISSUE TITLE
Webadmin gives 404 errors on master branch

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1116]
Go to webadmin and login successfully. Then try to access all tabs normally.

In global settings under webadmin everything brings 404 error meaning:

* Global settings
* Your settings
* Traffic info
* Manage users

* * * * *

* Debian GNU/Linux 7.9 (wheezy)
* ZNC 1.7.x-git-441-d66cb36 - http://znc.in
    * IPv6: yes, SSL: yes, DNS: threads, charset: yes

**Comment by jpnurmi** [comment]
Could it be a screwed up installation? I can't reproduce the issue with the same revision.

**Comment by Mikaela** [comment]
It can be in addition to one symlink labeled as "this can possibly be a bad idea", I will remove it and reinstall and see if it fixes this.

**Comment by Mikaela** [comment]
Screwed up installation.
