### ISSUE TITLE
Text parsing is faulty or something?

### ISSUE THREAD

**Issue by DangerDane** [znc/znc#1123]
I am in a Danish channel and people regularly using the danish characters æøå. My old bouncer setup used ZNC 1.2 which parses the letter correctly from ALL users. Once I upgraded to 1.6.1 at last from some users it gets replaced as 3 boxes with a ? inside of it. And I tried shifting around the parsing settings of ZNC 1.6.1 and nothing I have tried has resolved this issue.

**Comment by Zarthus** [comment]
What is the output of `znc version`?

**Comment by DangerDane** [comment]
ZNC 1.6.1 - http://znc.in
IPv6: yes, SSL: yes, DNS: threads, charset: yes

Vs

ZNC 1.2 - http://znc.in
IPv6: yes, SSL: yes, DNS: threads

**Comment by Zarthus** [comment]
If you're using the web interface, navigate to edit user (for me: https://somesite.com:1234/mods/global/webadmin/edituser) 

Can you see something like the following? [!image](http://i.imgur.com/mQkSHDP.png)

I am not sure how to configure it via controlpanel.

**Comment by DangerDane** [comment]
Well I did as instructed with setting UTF for client and ISO whatever for the server and it did the trick. Either that or it was me performing an error 40 :P

**Comment by DarthGandalf** [comment]
It's still UTF for server, just with ISO fallback... Unless you make it to be just ISO without UTF

**Comment by DangerDane** [comment]
How would I do that, just for reference?

**Comment by DarthGandalf** [comment]
Well, it has several options, including:
* Try to parse as UTF-8 and as ___, send as UTF-8
* Parse and send as ___ only

**Comment by Mikaela** [comment]
And **you don't want that!**
