### ISSUE TITLE
ZNC Bindhost change

### ISSUE THREAD

**Issue by mazlumb** [znc/znc#1125]
http://i.imgur.com/G3zkjSh.png Local host: omg.you.are.so.gay.hello2.us (94.23.207.50)
[14:33:41] <*status> This user's default bind host is [2001:41D0:2:5232::1337]
[14:33:41] <*status> This network's bind host is [92.222.207.220]

I did everything what I could do but I can't change my bindhost.
How do I fix this issue now?
My Config: http://p.maz.rocks/paste/560542d667277

**Comment by Zarthus** [comment]
Are you sure you own the IP 92.222.207.220? What is the output of `ip addr` in your terminal?

**Comment by mazlumb** [comment]
http://p.maz.rocks/paste/5605471e194dd
All IP's;
IP Address: 
94.23.207.50
94.23.147.183
178.32.47.92
178.32.59.254
188.165.29.87
87.98.246.190
92.222.207.220
92.222.207.221
92.222.207.222
92.222.207.223

**Comment by mazlumb** [comment]
Debug logs; http://p.maz.rocks/paste/5605488dc03f7

**Comment by psychon** [comment]
According to the debug log, you are connectiong from 92.222.207.220.
```
$ dig -x 92.222.207.220 | grep HEADER
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 25754
```

That IP doesn't have a reverse DNS entry (status: NXDOMAIN, no such domain).

Assuming you want your vhost to be `omg.you.are.so.gay.hello2.us`, you should try using 94.23.207.50 instead (or specifying `omg.you.are.so.gay.hello2.us` that directly as your bindhost)

**Comment by mazlumb** [comment]
Still Maz is connecting from *@omg.you.are.so.gay.hello2.us 94.23.207.50
server -m  94.23.207.50:1337 CokeB/mijnchat:

**Comment by mazlumb** [comment]
Let me clarify, I am trying to use the ip 92.222.207.220 to connect to the networks (without rdns, that’s right).
The 94.23.207.50 ip is the network interface that my znc service itself is listening on.
I configured the 92.222.207.220 IP address as bindhost, but znc still uses 94.23.207.50

**Comment by mazlumb** [comment]
psychon, I just want the vhost to be blank.

**Comment by mazlumb** [comment]
Network settings; http://p.maz.rocks/paste/56055b8d318da

**Comment by teward** [comment]
> I want the vhost to be blank

@mazlumb what exactly do you mean by 'blank'?  There is never going to be a 'blank' rDNS entry / vHost.  Whenever you connect to a network it will either be the IP or the rDNS.

**Comment by mazlumb** [comment]
@teward I putted the rDNS now to 92.222.207.220 to yo.i.want.titsorgtfo.me and it still doesn't connect.

**Comment by psychon** [comment]
`netstat -tpan | grep znc`, please (which hopefully only includes the connection of your test instance of znc).

If znc says `using bindhost [92.222.207.220]`, then it really thinks it is using that IP. Something else must be messing with this.

Can you connect elsewhere with this bindhost e.g. via telnet?

**Comment by mazlumb** [comment]
@psychon 
root@omg:~# netstat -tpan | grep znc
tcp        0      0 92.222.207.220:38332    37.48.109.201:6667      ESTABLISHED 20798/znc
tcp6       0      0 :::1337                 :::*                    LISTEN      20798/znc
tcp6       0      0 94.23.207.50:1337       163.158.219.10:44126    ESTABLISHED 20798/znc

**Comment by Mikaela** [comment]
> tcp 0 0 92.222.207.220:38332 37.48.109.201:6667 ESTABLISHED 20798/znc

it looks like bindhost is working to me.

> telnet 92.222.207.220

I think @psychon wanted you to connect *from* that address to somewhere, but I cannot find how to specify bindhost with telnet.

**Comment by psychon** [comment]
`(echo USER a b c d ; echo NICK hopefullyunused ; sleep 30 ) | telnet -b 92.222.207.220 irc.spotchat.org 6667`

Also, yup. What Mikaela said. ZNC is connecting from 92.222.207.220, so everything is working fine.
