### ISSUE TITLE
Add client_count_less_than option to simple_away

### ISSUE THREAD

**Issue by Jay2k1** [znc/znc#1133]
Assume you use multiple IRC clients, of which one is always connected no matter what. If you could tell simple_away to always set you away whenever the number of connected clients drops below the configurable number N instead of N being hardcoded to 1, this would be great. The push module <a href="https://github.com/jreese/znc-push#conditions">has this</a>.

<b>Why would you need this?</b>
I have one IRC client that's always connected because it's a webchat client running on the same server as my znc (<a href="http://shout-irc.com">shout</a> for those who are interested), so I can use my bouncer from a browser when I need to. Combined with the wonderful <a href="http://wiki.znc.in/Clientbuffer">clientbuffer</a> module, this is a great workaround for the (yet) non-existent ZNC webchat. The only downside is that you're not automatically set away anymore when you close your (other) IRC clients, because shout stays connected even when you close your browser.

**Comment by dgw** [comment]
Might want to call it e.g. `MinClients` instead of `client_count_less_than`, but I agree 100% with this suggestion.
