### ISSUE TITLE
znc removes the vnotice/opnotice symbol from vnotices/opnotices in backlogs.

### ISSUE THREAD

**Issue by Zarthus** [znc/znc#1136]
Every notice is displayed as a normal notice, regardless of them being specific to voices or ops, in the znc backlog.

**Comment by Mikaela** [comment]
I didn't understand the issue title, but you mean STATUSMSG/STATUSNOTICE. Did you test if STATUSMSGs work?

**Comment by Zarthus** [comment]
Confirmed working since 3cb2834cc5d5e81fc7f219f16d0de64ce251fb16, sorry about that.
