### ISSUE TITLE
Identfile is never populated using oidentd

### ISSUE THREAD

**Issue by linuxrules94** [znc/znc#1151]
When I enable identfile and configure it accoring to the wiki (http://wiki.znc.in/Identfile)  the file remains empty even after restarting oidentd then znc or rebooting the computer.

Info:

    Linux MitchMultimedia 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:36:45 CEST 2015 i686 GNU/Linux

    ZNC 1.6.1 - http://znc.in
    IPv6: yes, SSL: yes, DNS: threads, charset: yes

    oidentd 2.0.8
    Written by Ryan McCabe <ryan@numb.org>
    http://dev.ojnk.net

`~` expands to `/var/lib/znc`

    <user> GetFile
    <*identfile> File is set to: ~/.oidentd.conf
    <user> GetFormat
    <*identfile> Format is set to: global { reply "%ident%" }
    <*identfile> Format would be expanded to: global { reply "user" }
    <user> show
    <*identfile> m_pISpoofLockFile = 0
    <*identfile> m_pIRCSock = 0
    <*identfile> identfile is free

/etc/oidentd.conf 

    user "znc" {
        default {
            allow spoof
            allow spoof_all
            allow spoof_privport
            allow random
            allow random_numeric
            allow numeric
            allow hide
        }
    }

**Comment by iynque** [comment]
As far as I know, the identfile should be empty unless the user is logging into IRC (at which point it—briefly—contains that user's ident). Setting it up doesn't populate it. It gets populated on use.

Does ident work for you, even though the identify is empty?

**Comment by linuxrules94** [comment]
sometimes it does, other times it fails to ident with port 113 returning no-user when I watch with  `tcpdump -Xnvv port 113`

**Comment by linuxrules94** [comment]
I found the issue, I added `oidentd.socket` to `After=` in `znc.service`
