### ISSUE TITLE
Don't hardcode dh params

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1156]
Break the hardcoded DH params and you can break encryption on all ZNCs.
- https://github.com/znc/znc/blob/znc-1.6.1/src/Utils.cpp#L44-L51 or is there even a need of breaking?
- https://www.eff.org/deeplinks/2015/10/how-to-protect-yourself-from-nsa-attacks-1024-bit-DH
- https://freedom-to-tinker.com/blog/haldermanheninger/how-is-nsa-breaking-so-much-crypto/
##

**Comment by psychon** [comment]
Just to measure things, I generated my own dhparams. This printed three pages of mixtures of dots and pluses and took 6 minutes. In the same time I was using the computer in other ways, so I guess there was more entropy available than in some freshly booted server doing nothing else.

**Comment by teward** [comment]
Let me put my two cents.

Firstly, it doesn't take too long to generate the dhparams for 2048bit.  Secondly, let's take a page out of webservers: Allow a custom dhparams file to be used.

This then is the logic:

if (CUSTOM DHPARAM PROVIDED) then (USE CUSTOM)
else (USE HARDCODED).

Most webservers seem to still do this type of function.  Let people generate the dhparams with OpenSSL or others and then use the custom ones if they have been provided as a config option.

**Comment by DarthGandalf** [comment]
We allow custom dhparams... It's read from `znc.pem`.
The default hardcoded one is used only during `znc --makepem` to write `znc.pem`

**Comment by Mikaela** [comment]
Custom dhparams on a separate file seem to have become supported (by https://github.com/znc/znc/pull/1192?) or I don't see ZNC complaining about `SSLDHParamFile = /home/znc/.znc/ssl/dh.pem`.

I am still not sure on the default hardcoded ones though.

**Comment by teward** [comment]
I dont think they are hard coded in ZNC but in the SSL libs.  Which is why we support the params file now...

**Comment by DarthGandalf** [comment]
It's read from `SSLDHParamFile`, yes, which defaults to `~/.znc/znc.pem`. If that file doesn't have DH params, the pregenerated (hardcoded) one is used.

I don't see the problem.

**Comment by teward** [comment]
I think the bigger issue here is, that we don't *have* DHParams.  It's almost like this request is "If there are no defined DHParams in znc.pem AND there are no separate dhparam files, generate some.

@Mikaela is this what you're looking for?  All libssl driven systems 'inherit' the default DHParams.  (We could alter default SSL Ciphers to drop all DHE ciphers (but not ECDHE which uses elliptical curves instead of DHParams))

**Comment by Mikaela** [comment]
I am under impression that ZNC has dhparams in https://github.com/znc/znc/blob/znc-1.7.4/src/Utils.cpp#L69-L76 that are put to znc.pem or used by default and that if they are broken (or is that like a private key that doesn't need to be broken as it's there for anyone to see?), the traffic between most of ZNC instances and IRC client is followable by parties such as the NSA as indicated by the articles I linked four years ago.

I don't know about the default parameters of lbssl systems and I am not sure if I even understand DH.

**Comment by DarthGandalf** [comment]
dhparams are not private. Moreover, if server supports DH at all, it tells the SSL client what the values are.
