### ISSUE TITLE
Problem with latest version of ICU.

### ISSUE THREAD

**Issue by JeDa** [znc/znc#1157]
As for the encoding method, it required ICU, which wasn't installed on my system. I installed it (the latest version) and now ZNC doesn't wants to start. That's what I got:

***irc@jedayoshi:~$ znc
znc: error while loading shared libraries: libicuuc.so.56: cannot open shared object file: No such file or directory***

Any idea why? I'm using the latest version of ZNC (1.6.1) with Debian Sid.

**Comment by JeDa** [comment]
PS: As Mikaela's request, the ICU version is 56.

**Comment by Mikaela** [comment]
Is it possible that you could have installed icu without the development libraries? The Debian package wanted is `libicu-dev` which is why I ask.

**Comment by DarthGandalf** [comment]
Where did you install ICU 56? Is that directory listed in `/etc/ld.so.conf` or `LD_LIBRARY_PATH`?

**Comment by JeDa** [comment]
@Mikaela hmm, I don't know. When I extract'd the ICU file, I cd'd to icu/source and compiled it.

@DarthGandalf I installed it on the default directory.

**Comment by DarthGandalf** [comment]
The "default" directory is `/usr/local`? By default `/etc/ld.so.conf` doesn't contain `/usr/local/lib`.
