### ISSUE TITLE
Show IP of Client when behind a remote proxy

### ISSUE THREAD

**Issue by rjemanuele** [znc/znc#1169]
When using the URIPrefix and allowing web access through a reverse proxy (Apache), the header shows "Logged in as: User (from 127.0.01)" where in this case the proxy is on the same host.

I'd like the web interface to be show the client's true address by using the "X-Forwarded-For" header.

I'm digging into the code to put together a patch but any pointers would be appreciated.

**Comment by dgw** [comment]
What version are you on? I run webadmin through an nginx reverse proxy and I see my real IP in the header.

````
*status ZNC - 1.6.0 - http://znc.in
[22:49:32] *status IPv6: yes, SSL: yes, DNS: threads, charset: yes
````

**Comment by rjemanuele** [comment]
ZNC 1.6.1+deb1~ubuntu14.04.0 - http://znc.in
IPv6: yes, SSL: yes, DNS: threads, charset: yes

Maybe there is another Apache setting I need.

**Comment by rjemanuele** [comment]
I just confirmed using tcpdump that the Apache proxy is making a request with X-Forwarded-For set to my IP correctly.

**Comment by dgw** [comment]
Perhaps mine works because of the line `TrustedProxy = 127.0.0.1` in znc.conf. I don't believe any TrustedProxies are set by default.

**Comment by rjemanuele** [comment]
@dgw Yes!  TrustedProxy was the key to making it work!  Thank you!

**Comment by dgw** [comment]
You're quite welcome :)

**Comment by Mikaela** [comment]
Related issues:
* Some options are only in webadmin/controlpanel/znc.conf, nowhere else #1128
* Always trust reverse proxy on localhost without additional configuration #1126 
    * closed as potentially bad idea.
