### ISSUE TITLE
Option to disable password login / enforce certificate

### ISSUE THREAD

**Issue by mvdwoord** [znc/znc#1173]
Hi, I would like to have an option to disable password access whenever a user has enabled certificate based authentication using the certauth module.  Analog to disabling password based authentication on SSH.

A workaround is to manually set an invalid SHA256 hash for the user but that feels a but hackish.
Thanks.
##

**Comment by Mikaela** [comment]
I think this might be a duplicate of https://github.com/znc/znc/issues/331.
