### ISSUE TITLE
Using squid and Port forward

### ISSUE THREAD

**Issue by dannyti** [znc/znc#1177]
Squid has only ports 80 and 443 open on remote machine.

ZNC on local machine with port 7000 (web interface) port forwarded from 80.

From remote machine browser accessing the server:80 brings up the znc interface.

Although , on logging in with admin user/pass ; it has the "Access Denied" error. With squid bypassed, normal logging in takes place. Any logs which I can bring up ?

The following error on logging in from remote machine.

> Access denied
> 
> This session does not belong to your IP.
> 
> ZNC - http://znc.in
##

**Comment by DarthGandalf** [comment]
May you draw a scheme what is 'local machine', 'remote machine', where is browser, what port is forwarded to where, etc?

This error means that at first ZNC see you connecting from one IP, then with the same cookie from another IP. That could be because of e.g. #593 
If there is a valid reason to change IP, and if you're brave, you can turn off that protection.

**Comment by DarthGandalf** [comment]
Also, depending on your setup, TrustedProxy setting may be useful

**Comment by dannyti** [comment]
http://imgur.com/I77juAJ

Here is an amateur schematic. 

:)

**Comment by dannyti** [comment]
Squid is not Under my control.

**Comment by DarthGandalf** [comment]
If you clear cookies, and don't switch between proxy and direct connection, ZNC will see you connecting from only one IP.
If you switch between proxy and direct connection, ZNC sees 2 connections from 2 different IPs but with the same cookie.

**Comment by dannyti** [comment]
There was option of different IP sessions under global settings. I deselected it and now znc doesn't complain. 

Thanks for this. 

Although , irc connections to 7000 do not work via the squid server. A pain in ass really.

**Comment by DarthGandalf** [comment]
I don't see what else can be done here. ZNC has no control over how client connects to it, and whether there are any proxies in between.
