### ISSUE TITLE
Override CSRF protection for POST requests [$73]

### ISSUE THREAD

**Issue by lol768** [znc/znc#1180]
Is it possible to disable/override the CSRF protection token verification requirement for a module's OnWebRequest listener?

I believe the check is performed [here](https://github.com/znc/znc/blob/d66cb36cc3cef65f472f4c6535128b9f785c94b4/src/WebModules.cpp#L608) - there doesn't appear to be a way to disable it.

**Comment by psychon** [comment]
Am I understanding you correctly: You are writing a module `foo` and it offers a web page `/bar` and you want to disable the CSRF protection for this specific page?
Why would you want/need that?

**Comment by lol768** [comment]
Hi @psychon,

That's correct. In my case, it's not a webpage but it's a route in a RESTful API I'm working on. For one of the routes, a POST action makes the most sense and there's no real way that the API client would be able to know the CSRF token (nor should it be expected to).

Cheers!

**Comment by DarthGandalf** [comment]
Is HTTP-Basic auth an option for you?

**Comment by lol768** [comment]
Not in this case, the API is designed to be accessible to anyone (no authentication should be required).

**Comment by psychon** [comment]
So, are you looking for `WebRequiresLogin() { return false; }`?
https://github.com/znc/znc/blob/73d5f382f83eb1cd77d3ea4afb98e132fb6f4705/include/znc/Modules.h#L422-L425

**Comment by lol768** [comment]
> Edit: Ohhhhh, now I get it!
> You already have WebRequireLogin() returning false, but of course the CSRF check is still run.

Yup. I've worked around it so far by forcing use of GET requests but it's not ideal, especially when you have a lot of data (gets messy putting it in the query string).

**Comment by lol768** [comment]
I've added a bounty on this since it was annoying me and I'd like to do some further API work in my module.

Ideally I think there'd be a `virtual EModRet OnCsrfCheck(CWebSock& WebSock, const CString& sPageName);` (and then I could return HALT) or perhaps a  `virtual bool RequiresCsrfCheck(CWebSock& WebSock, const CString& sPageName);` where I could just return `false` for API requests.
