### ISSUE TITLE
Failed to login via IRC, webadmin works fine

### ISSUE THREAD

**Issue by marsjaninzmarsa** [znc/znc#1194]
After upgrade from e879203d546a4730e5f299ba0eef57f81edbbdd9 to new snapshot, I cannot login to bouncer - server killing connection after `/pass` with 'Invalid password', when same password works for webadmin, same thing for other users. Bouncer can connect to servers, I can connect to bouncer, but every user, every network - same error. No another info when starting ZNC in debug mode. Resetting password, recompiling, clearing config, even deleting all files, cloning repo again and recompiling doesn't work, every time the same error. Compiling 1.6.x branch, new config - all fine, compiling revision mentioned above, my old config - all fine, so it's regression.
##

**Comment by magnum7385** [comment]
Just to clarify, e879203 was the last working version, and the versions after that were the ones which denied you login via /PASS while allowing webadmin logins, correct?

**Comment by marsjaninzmarsa** [comment]
@magnum7385 I don't know what was the last working version, e879203d546a4730e5f299ba0eef57f81edbbdd9 was last version that I successfully tested, my buddy is on 2de6d34 and I can check it, but not today. cbf5c38d0a978ba4e251e675e818023f7ab2c68f and versions after it refusing me login via /PASS while allowing webadmin logins, and I know nothing about versions between that last tested as working and that first tested as broken.

**Comment by magnum7385** [comment]
Okay, great.  I was just trying to get a better picture of where the cutoff point was between 'known functional' and 'known non-functional'.  I appreciate the addtional version details.  (I'm MetaNova in #znc by the way)

**Comment by psychon** [comment]
Could this be the same issue as https://github.com/znc/znc/issues/1188? (Read: Does your password contain spaces and you/your IRC client sends it without the necessary ":" in front?)

**Comment by marsjaninzmarsa** [comment]
@psychon don't think so, multiple users, multiple passwords, and mostly HexChat, also tested with manual password entrance with all available methods.

**Comment by marsjaninzmarsa** [comment]
Umm, looks like HexChat issue... I must run serious debug around this, you can be right about that.
