### ISSUE TITLE
Just send self private messages to all clients without waiting for them to request znc.in/self-message

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#1214]
https://github.com/ircv3/ircv3-specifications/commit/1bfba47843c2526707c902034b3395af934713c8

```
<dx> and then assume that every client that doesn't have echo-message
     implements what self-message described?
<kaniini> dx: seems reasonable
<dx> right now we could definitely get away with capless self-message
```

**Comment by DarthGandalf** [comment]
There are lots of clients which don't understand messages in this format.

**Comment by Mikaela** [comment]
Which break against that and ZNC couöd make them more interested in fixing it.

**Comment by DarthGandalf** [comment]
No, the only thing such change would do, is to annoy users and force them to downgrade ZNC to a version which doesn't send that.
