### ISSUE TITLE
autoconf make fail with --enable-modperl  in git master branch

### ISSUE THREAD

**Issue by Intrainos** [znc/znc#1236]
git master branch(latest commit 82b30ced).
./configure --enable-modperl
make

....

make[1]: *** No rule to make target `modperl/generated.tar.gz', needed by `modperl/modperl_biglib.cpp'. 

----
But '''cmake -DWANT-PERL=yes''' is work.

**Comment by KindOne-** [comment]
pastebin the config.log?

**Comment by Intrainos** [comment]
https://gist.github.com/b041573bb4ce8bce2acc

**Comment by DarthGandalf** [comment]
Looks like you're using old `configure`, you need to rerun `./bootstrap.sh` to generate `configure` again

**Comment by Intrainos** [comment]
It work. Thanks.
