### ISSUE TITLE
'Allowed ips' seems to be limited to 4 entrys

### ISSUE THREAD

**Issue by fred0r** [znc/znc#1238]
I do have 4 entries - the first 2 with fixed ipv4 and another 2 ipv4 with wildcards.
The 5. entry is never saved.
I'm using ZNC 1.7.x-git-559-04ad80b

**Comment by DarthGandalf** [comment]
Works for me.
```
*
1.2.3.4
10.*
11.*
5.6.7.8
9.*
```
