### ISSUE TITLE
can not progress cmake with -DWANT_CYRUS=YES

### ISSUE THREAD

**Issue by Intrainos** [znc/znc#1243]
-- Checking for module 'libsasl2'
--   Package 'libsasl2' not found
CMake Error at CMakeLists.txt:113 (message):
  Can't find Cyrus SASL 2

-- Configuring incomplete, errors occurred!
See also "/home/intrainos/znc/CMakeFiles/CMakeOutput.log".
See also "/home/intrainos/znc/CMakeFiles/CMakeError.log".

CMakeOutput.log : https://gist.github.com/d6b534f87ca1b30cf38e
CMakeError.log : https://gist.github.com/ad9fe02ee4d94373a894

----
./configure --enable-cyrus is work.

**Comment by DarthGandalf** [comment]
Show `config.log` of ./configure

**Comment by Intrainos** [comment]
https://gist.github.com/c202fa2fcc9660527680

(and on c6ed6b2e)

**Comment by DarthGandalf** [comment]
Looks like bug in sasl, fixed in https://cgit.cyrus.foundation/cyrus-sasl/commit/include/sasl.h?id=2f740223fa1820dd71e6ab0e50d4964760789209

**Comment by Intrainos** [comment]
work fine.
