### ISSUE TITLE
direct support for letsencrypt certificate rather than znc.pem

### ISSUE THREAD

**Issue by zedinosaur** [znc/znc#1247]
Having to regenerate znc.pem (http://wiki.znc.in/Signed_SSL_certificate#LetsEncrypt) each time you renew a letsencrypt certificate rotates is annoying. It would be great if znc supported reading the letsencrypt certificate directly.

**Comment by berrythesoftwarecodeprogrammar** [comment]
i think ive seen people on the LetsEncrypt github talk about adding alternate output methods for things such as lighttpd,znc,etc. this might be more of a letsencrypt issue than a znc one.

maybe you need to utilise some of the scripts that are out there or write some bash to add generating the znc.pem to your certificate renewal process. and the znc.pem can be anywhere, `SSLCertFile` in znc.conf just needs  to point to it

**Comment by Mikaela** [comment]
Even if LetsEncrypt supported ZNC directly, it would be useless because of #1215 and ZNC not supporting running as root or even dropping out of root.

**Comment by zedinosaur** [comment]
Sure, but these all sound like workarounds. It would be nice if znc could support them directly without needing scripts to create znc.pem.

**Comment by Mikaela** [comment]
And I just remembered this is already done or is https://github.com/znc/znc/pull/1192 not what you are asking?

**Comment by zedinosaur** [comment]
Ah, that does look like what I'm after, thanks!
