### ISSUE TITLE
ZNC crashing when disconnecting at the moment of sending data

### ISSUE THREAD

**Issue by JeDa** [znc/znc#1248]
Hey there.

I found a bug in ZNC, which looks to exist on 1.6.3-rc1, 1.6.3 and 1.7.*-git.

I was doing ```/znc *shell grep '(some|nicks)' ~/moddata/log/jeda/freenode/*/*.log``` on my ZNC, and I disconnected which made ZNC crash. By the debug I did, it's a "Broken pipe" error.

> Signal        Stop Print Pass to program Description SIGPIPE       No Yes Yes Broken pipe Starting program: /usr/local/bin/znc -D During startup program exited with code 127. Quit Quit Error detected on fd 0 error detected on stdin Undefined command: "gdb".  Try "help". Attaching to process 30301 Reading symbols from /usr/local/bin/znc...done. Reading symbols from /lib/x86_64-linux-gnu/libdl.so.2...Reading symbols from /usr/lib/debug/.build-id/52/c4b519ccbf0399d677cf3d39874007dd01afa0.debug...done. done. Reading symbols from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2...(no debugging symbols found)...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libz.so.1...(no debugging symbols found)...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libicuuc.so.55...(no debugging symbols found)...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libicudata.so.55...(no debugging symbols found)...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libstdc++.so.6...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libm.so.6...Reading symbols from /usr/lib/debug/.build-id/8c/94875b3b757b9f37302d61a69d672693b95cf5.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libgcc_s.so.1...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...Reading symbols from /usr/lib/debug/.build-id/22/08f598f26a367614dcfefea741acd556eb7da7.debug...done. done. [New LWP 30343] [New LWP 30305] [New LWP 30303] [Thread debugging using libthread_db enabled] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1". Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug/.build-id/bc/793b207d17064f91e35f22c00987a91a514712.debug...done. done. Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug/.build-id/42/480648b8070bbaacf1f6a8ef73749fd0f63fa3.debug...done. done. Reading symbols from /usr/local/lib/znc/webadmin.so...done. Reading symbols from /usr/local/lib/znc/adminlog.so...done. Reading symbols from /usr/local/lib/znc/blockuser.so...done. Reading symbols from /usr/local/lib/znc/certauth.so...done. Reading symbols from /usr/local/lib/znc/chansaver.so...done. Reading symbols from /usr/local/lib/znc/fail2ban.so...done. Reading symbols from /usr/local/lib/znc/identfile.so...done. Reading symbols from /usr/local/lib/znc/lastseen.so...done. Reading symbols from /usr/local/lib/znc/log.so...done. Reading symbols from /usr/local/lib/znc/modpython.so...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libexpat.so.1...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libutil.so.1...Reading symbols from /usr/lib/debug/.build-id/ca/63c0d0fce7f293937fa2e512116054d417f74f.debug...done. done. Reading symbols from /usr/local/lib/znc/modpython/_znc_core.so...done. Reading symbols from /usr/local/lib/znc/partyline.so...done. Reading symbols from /usr/local/lib/znc/controlpanel.so...done. Reading symbols from /usr/local/lib/znc/autocycle.so...done. Reading symbols from /usr/local/lib/znc/autovoice.so...done. Reading symbols from /usr/local/lib/znc/crypt.so...done. Reading symbols from /usr/local/lib/znc/keepnick.so...done. Reading symbols from /usr/local/lib/znc/kickrejoin.so...done. Reading symbols from /usr/local/lib/znc/modules_online.so...done. Reading symbols from /usr/local/lib/znc/nickserv.so...done. Reading symbols from /usr/local/lib/znc/route_replies.so...done. Reading symbols from /usr/local/lib/znc/sasl.so...done. Reading symbols from /usr/local/lib/znc/savebuff.so...done. Reading symbols from /usr/local/lib/znc/schat.so...done. Reading symbols from /usr/local/lib/znc/simple_away.so...done. Reading symbols from /usr/local/lib/znc/stickychan.so...done. Reading symbols from /usr/local/lib/znc/watch.so...done. Reading symbols from /usr/local/lib/znc/alias.so...done. Reading symbols from /usr/local/lib/znc/autoattach.so...done. Reading symbols from /usr/local/lib/znc/autoreply.so...done. Reading symbols from /usr/local/lib/znc/bouncedcc.so...done. Reading symbols from /usr/local/lib/znc/buffextras.so...done. Reading symbols from /usr/local/lib/znc/cert.so...done. Reading symbols from /usr/local/lib/znc/clearbufferonmsg.so...done. Reading symbols from /usr/local/lib/znc/clientnotify.so...done. Reading symbols from /usr/local/lib/znc/ctcpflood.so...done. Reading symbols from /usr/local/lib/znc/disconkick.so...done. Reading symbols from /usr/local/lib/znc/notes.so...done. Reading symbols from /usr/local/lib/znc/perform.so...done. Reading symbols from /usr/local/lib/znc/awaystore.so...done. Reading symbols from /usr/local/lib/znc/modtcl.so...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libtcl8.6.so...(no debugging symbols found)...done. Reading symbols from /usr/local/lib/znc/dcc.so...done. Reading symbols from /usr/local/lib/znc/shell.so...done. Reading symbols from /usr/local/lib/znc/send_raw.so...done. Reading symbols from /usr/local/lib/znc/autoop.so...done. Reading symbols from /lib/x86_64-linux-gnu/libnss_compat.so.2...Reading symbols from /usr/lib/debug/.build-id/ff/e1799cf99751daf43cd087e2486b56b10a5428.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libnsl.so.1...Reading symbols from /usr/lib/debug/.build-id/db/43ca74fbbcbae52d63e53e08124f7060e431c1.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libnss_nis.so.2...Reading symbols from /usr/lib/debug/.build-id/9a/4241e505dbfb9a0e13a371396bfcb298941101.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libnss_files.so.2...Reading symbols from /usr/lib/debug/.build-id/3e/6c79c3186003b55afb8efb036e09608fcfa583.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libnss_dns.so.2...Reading symbols from /usr/lib/debug/.build-id/62/c49f986abcc930f435f21254e5f352fe73a145.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libresolv.so.2...Reading symbols from /usr/lib/debug/.build-id/7a/a08c6372a82257727905d3df2b2a73231b2f7b.debug...done. done. 0x00007fb9ce8fab6d in poll ()     at ../sysdeps/unix/syscall-template.S:81 81 ../sysdeps/unix/syscall-template.S: Permission denied. Signal        Stop Print Pass to program Description SIGPIPE       No Yes Yes Broken pipe Continuing.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Program received signal SIGPIPE, Broken pipe.
Quit Detaching from program: /usr/local/bin/znc, process 30301

I hope you guys can fix it. Thanks.

**Comment by Mikaela** [comment]
This issue is invalid as you didn't follow http://wiki.znc.in/Debugging (`(gdb) handle SIGPIPE nostop`). 

SIGPIPE is not the issue.

**Comment by JeDa** [comment]
As wiki data was wrong, I fixed it. Looks like it is a SEGFAULT.

> Attaching to process 30435 Reading symbols from /usr/local/bin/znc...done. Reading symbols from /lib/x86_64-linux-gnu/libdl.so.2...Reading symbols from /usr/lib/debug/.build-id/52/c4b519ccbf0399d677cf3d39874007dd01afa0.debug...done. done. Reading symbols from /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2...(no debugging symbols found)...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libz.so.1...(no debugging symbols found)...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libicuuc.so.55...(no debugging symbols found)...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libicudata.so.55...(no debugging symbols found)...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libstdc++.so.6...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libm.so.6...Reading symbols from /usr/lib/debug/.build-id/8c/94875b3b757b9f37302d61a69d672693b95cf5.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libgcc_s.so.1...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...Reading symbols from /usr/lib/debug/.build-id/22/08f598f26a367614dcfefea741acd556eb7da7.debug...done. done. [New LWP 30480] [New LWP 30438] [New LWP 30436] [Thread debugging using libthread_db enabled] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1". Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug/.build-id/bc/793b207d17064f91e35f22c00987a91a514712.debug...done. done. Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug/.build-id/42/480648b8070bbaacf1f6a8ef73749fd0f63fa3.debug...done. done. Reading symbols from /usr/local/lib/znc/webadmin.so...done. Reading symbols from /usr/local/lib/znc/adminlog.so...done. Reading symbols from /usr/local/lib/znc/blockuser.so...done. Reading symbols from /usr/local/lib/znc/certauth.so...done. Reading symbols from /usr/local/lib/znc/chansaver.so...done. Reading symbols from /usr/local/lib/znc/fail2ban.so...done. Reading symbols from /usr/local/lib/znc/identfile.so...done. Reading symbols from /usr/local/lib/znc/lastseen.so...done. Reading symbols from /usr/local/lib/znc/log.so...done. Reading symbols from /usr/local/lib/znc/modpython.so...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libexpat.so.1...(no debugging symbols found)...done. Reading symbols from /lib/x86_64-linux-gnu/libutil.so.1...Reading symbols from /usr/lib/debug/.build-id/ca/63c0d0fce7f293937fa2e512116054d417f74f.debug...done. done. Reading symbols from /usr/local/lib/znc/modpython/_znc_core.so...done. Reading symbols from /usr/local/lib/znc/partyline.so...done. Reading symbols from /usr/local/lib/znc/controlpanel.so...done. Reading symbols from /usr/local/lib/znc/autocycle.so...done. Reading symbols from /usr/local/lib/znc/autovoice.so...done. Reading symbols from /usr/local/lib/znc/crypt.so...done. Reading symbols from /usr/local/lib/znc/keepnick.so...done. Reading symbols from /usr/local/lib/znc/kickrejoin.so...done. Reading symbols from /usr/local/lib/znc/modules_online.so...done. Reading symbols from /usr/local/lib/znc/nickserv.so...done. Reading symbols from /usr/local/lib/znc/route_replies.so...done. Reading symbols from /usr/local/lib/znc/sasl.so...done. Reading symbols from /usr/local/lib/znc/savebuff.so...done. Reading symbols from /usr/local/lib/znc/schat.so...done. Reading symbols from /usr/local/lib/znc/simple_away.so...done. Reading symbols from /usr/local/lib/znc/stickychan.so...done. Reading symbols from /usr/local/lib/znc/watch.so...done. Reading symbols from /usr/local/lib/znc/alias.so...done. Reading symbols from /usr/local/lib/znc/autoattach.so...done. Reading symbols from /usr/local/lib/znc/autoreply.so...done. Reading symbols from /usr/local/lib/znc/bouncedcc.so...done. Reading symbols from /usr/local/lib/znc/buffextras.so...done. Reading symbols from /usr/local/lib/znc/cert.so...done. Reading symbols from /usr/local/lib/znc/clearbufferonmsg.so...done. Reading symbols from /usr/local/lib/znc/clientnotify.so...done. Reading symbols from /usr/local/lib/znc/ctcpflood.so...done. Reading symbols from /usr/local/lib/znc/disconkick.so...done. Reading symbols from /usr/local/lib/znc/notes.so...done. Reading symbols from /usr/local/lib/znc/perform.so...done. Reading symbols from /usr/local/lib/znc/awaystore.so...done. Reading symbols from /usr/local/lib/znc/modtcl.so...done. Reading symbols from /usr/lib/x86_64-linux-gnu/libtcl8.6.so...(no debugging symbols found)...done. Reading symbols from /usr/local/lib/znc/dcc.so...done. Reading symbols from /usr/local/lib/znc/shell.so...done. Reading symbols from /usr/local/lib/znc/send_raw.so...done. Reading symbols from /usr/local/lib/znc/autoop.so...done. Reading symbols from /lib/x86_64-linux-gnu/libnss_compat.so.2...Reading symbols from /usr/lib/debug/.build-id/ff/e1799cf99751daf43cd087e2486b56b10a5428.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libnsl.so.1...Reading symbols from /usr/lib/debug/.build-id/db/43ca74fbbcbae52d63e53e08124f7060e431c1.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libnss_nis.so.2...Reading symbols from /usr/lib/debug/.build-id/9a/4241e505dbfb9a0e13a371396bfcb298941101.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libnss_files.so.2...Reading symbols from /usr/lib/debug/.build-id/3e/6c79c3186003b55afb8efb036e09608fcfa583.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libnss_dns.so.2...Reading symbols from /usr/lib/debug/.build-id/62/c49f986abcc930f435f21254e5f352fe73a145.debug...done. done. Reading symbols from /lib/x86_64-linux-gnu/libresolv.so.2...Reading symbols from /usr/lib/debug/.build-id/7a/a08c6372a82257727905d3df2b2a73231b2f7b.debug...done. done. 0x00007f009d975b6d in poll ()     at ../sysdeps/unix/syscall-template.S:81 81 ../sysdeps/unix/syscall-template.S: Permission denied. Signal        Stop Print Pass to program Description SIGPIPE       No No Yes Broken pipe Continuing.
Program received signal SIGSEGV, Segmentation fault. 0x00007f009dc35118 in main_arena ()    from /lib/x86_64-linux-gnu/libc.so.6 #0  0x00007f009dc35118 in main_arena ()    from /lib/x86_64-linux-gnu/libc.so.6 No symbol table info available. #1  0x00000000006c1e5e in CClient::PutClient (     this=0x18ce210, sLine=...) at src/Client.cpp:792
         bReturn = false
         sCopy = {<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >> = ":*shell!shell@/var/lib/znc PRIVMSG JeDa :3pw\316\023y\017\202\225\334<Oni\021\335\343\327R\310*;\364\206\355\324\257#LA\265\232\370ѫ\023\303\336\066\327\211\223\360\355\241^\251O]\302\315\031\216\354\027\061\210\242\372\020\004+\320\303\064C\363Z.$`\333L\263s\026\222\016\020\\)\300*u\322b\344\246-\200\242\273\215\227[R\
Quit
Detaching from program: /usr/local/bin/znc, process 30435
