### ISSUE TITLE
Potential issue:  PRIVMSGs sent to +#<channel> are not handled correctly.

### ISSUE THREAD

**Issue by afk11** [znc/znc#1251]
See Freenode for info. Woke up to several new PM windows open. One came from freenode staff, advising to raise this issue on IRC client repo's.

**Comment by Mikaela** [comment]
This is 100% client issue and also invalid as you didn't read CONTRIBUTING.md or give any information requested in it.

**Comment by Mikaela** [comment]
* `-- CTCP reply from afk11: VERSION xchat 2.8.8 Ubuntu`

You might want to consider moving to HexChat as Xchat is dead and this won't be fixed in it while it's fixed in HexChat. Xchat is also missing support for SASL and TLS (unless pstched by distrobution).

**Comment by Mikaela** [comment]
See also: https://hexchat.readthedocs.org/en/latest/faq.html#how-do-i-migrate-my-settings-from-xchat

**Comment by afk11** [comment]
Ok, ll get away from xchat! Thanks for pointing me in the right direction!
