### ISSUE TITLE
znc keeps using old system dns resolvers even after theyre changed?

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [znc/znc#1254]
is that how znc works? because i was having trouble all day with my dns messing up so znc was unable to connect to anything. and then when i finally fixed the system dns, znc continued to not work until i restarted it. so it seemed like znc continued to use the old dns servers instead of getting the new system ones. not sure if this always happens or if it was a special case

<*status> ZNC 1.6.3 - http://znc.in
<*status> IPv6: yes, SSL: yes, DNS: threads, charset: no

CentOS 6.7

**Comment by TheDoctorsLife** [comment]
Try restarting znc

**Comment by DarthGandalf** [comment]
It just uses `getaddrinfo()` to resolve DNS, as the majority of other software...

**Comment by berrythesoftwarecodeprogrammar** [comment]
it didnt seem to pick up any of my dns changes until i restarted it. only then did it start resolving hosts again. idk

**Comment by berrythesoftwarecodeprogrammar** [comment]
well if it does what every other software does maybe something else caused it somehow. now i know i can restart it if it happens again. so you can close this if you think theres no problem with znc

**Comment by berrythesoftwarecodeprogrammar** [comment]
had this happen again on another server. i set up `unbound` to manage my dns requests and every application was able to start  resolving hosts using the new resolvers but znc wouldnt. it needed to be restarted

**Comment by Mikaela** [comment]
I think `/etc/resolv.conf` had some option for telling everything to always read it which is said to be a bad idea and [searx](https://searx.me/?q=centos%20reload%20/etc/resolv.conf&categories=general) says that you should [service network restart](https://www.centos.org/forums/viewtopic.php?t=41520).

**Comment by berrythesoftwarecodeprogrammar** [comment]
kk ill try that next time
