### ISSUE TITLE
Crash after updating to 1.6.3 from 1.6.2

### ISSUE THREAD

**Issue by thepace** [znc/znc#1255]
Im runing znc on ubuntu 14.04 lts , compiled it from source. 1.6.2 was working fine compiled from source too using official releases both times. After upgrading to 1.6.3 znc is crashing. Steps to reproduce: start znc from command line, top lists it on process list, webui works. Then i try to connect to bounces using mirc from local machine (ZNC runs on remote server) and it dies. Guys from #znc told me that this info might be useful for investigating whats going on http://pastebin.com/A3HbQKrB
##

**Comment by thepace** [comment]
http://pastebin.com/9W54Gw9P this is what i got via gdb before typing bt full

**Comment by DarthGandalf** [comment]
May you show last lines of `znc -D` before the crash?
What modules do you have loaded?

**Comment by thepace** [comment]
Can u give me step by step for that , i start znc load mirc = crash , should i start znc type znc -d and crash it or what ?

**Comment by psychon** [comment]
Yup, you should start znc with `znc -D` and then make it crash. You will get lots of output from ZNC (which could also include passwords, so don't copy everything blindly). We are interested in this output (at least the last part of it, let's say... the last 100 lines?)

**Comment by DarthGandalf** [comment]
From discussion on IRC:
There was an external module built for 1.6.2. The crash was fixed after rebuilding that module.
Though update between 1.6.x versions should require rebuild...
