### ISSUE TITLE
Disabling SASL module via webpanel causes ZNC to crash

### ISSUE THREAD

**Issue by RoboMWM** [znc/znc#1258]
For whatever reason, when I uncheck the sasl module from the webpanel and save the changes, it seems that the ZNC just flat out dies, forcing me to restart it.

Using unloadMod via IRC client results in no issues.

Not sure if there's a log file I can provide. I am making this change from the ZNC admin account on another user (myself). No clients were connected to the ZNC during this.

Version ZNC 1.6.2+cygwin2, Windows Server 2012 R2
##

**Comment by Un1matr1x** [comment]
http://wiki.znc.in/Debugging#Tracing_crash_bugs

**Comment by DarthGandalf** [comment]
Reopen when you have the stack trace.
