### ISSUE TITLE
modpython: ImportError when trying to load my module

### ISSUE THREAD

**Issue by dwbfox** [znc/znc#1263]
I created a znc script usind modpython. When I try to import a second helper script into my custom module, I get an import error for the script I'm trying to import. Here's an example of the issue:

`mymodule.py`
```python
import znc
import mymodulehelper # throws an ImportError exception
class foo:
    def OnLoad(self, args, msg):
        self.PutModule('Loaded....')
        # ...
        
```        
folder structure
```
| ~/.znc/modules
    | mymodule.py
    | mymodulehelper.py
```

Any help would be greatly appreciated.

**Comment by DarthGandalf** [comment]
ZNC doesn't add path to modules to `sys.path`, you can do it yourself.
```py
import sys
sys.path.append('/path/to/helpers')
import mymodulehelper
```
It's better to be a different directory from `~/.znc/modules/` though. Files in `~/.znc/modules/` are intended to be loaded from ZNC as a module, not from python using `import`.
