### ISSUE TITLE
*log: (loggin module) - filter out the joins / quits from log files

### ISSUE THREAD

**Issue by dreamcat4** [znc/znc#1264]
Would be to have a way to filter out all `joins` / `quits` from znc log files.

Not sure how its best to do that. Either internally within the znc *log module itself. Or else some external log-scrubbing tool. That watched the logs files folder of znc, and re-copied each logs files without the jonis / quits.

Or even some http web service of a pre-existing logs presentation software. That already included soms regexp * filter feature.

Would be a nice addition either way.

**Comment by dreamcat4** [comment]
Ah... its already been implemented!

https://github.com/znc/znc/issues/601

Just not documented on the wiki?

For the modules interactive help system, this but seems to say theres a `set` command:

https://github.com/znc/znc/blob/master/modules/log.cpp#L80-84

But trying that I get `invalid command` from ZNC 1.6.3+deb1. So maybe its newer than my version yet? Says it was committed on 23 Aug 2015

**Comment by DarthGandalf** [comment]
Correct. It'll be in 1.7. Install nightly or git if you want it now.

**Comment by DarthGandalf** [comment]
Help to update the outdated wiki is welcome!

**Comment by dreamcat4** [comment]
Thanks for these infos. Appreciate it.
