### ISSUE TITLE
Unloading block_motd user module results in a crash

### ISSUE THREAD

**Issue by RoboMWM** [znc/znc#1265]
Similar to results in #1258, except in this case unloading the mod via a private message to *status causes ZNC to flat out die. On top of this, block_motd is not unloaded when I start ZNC back up.

Unloading the mod via the webpanel also causes a crash, but upon restarting ZNC, the block_motd module remains unloaded.

Version ZNC 1.6.2+cygwin2, Windows Server 2012 R2
##

**Comment by psychon** [comment]
Does `gdb` work on cygwin? Could you try something like http://wiki.znc.in/Debugging#Tracing_crash_bugs ?

**Comment by DarthGandalf** [comment]
AFAIK, for gdb to work better, need to have znc-debuginfo package installed.

2016-04-20 8:45 GMT+01:00 Uli Schlachter <notifications@github.com>:

**Comment by RoboMWM** [comment]
Seems znc-debuginfo package is listed as n/a in cygwin...

**Comment by DarthGandalf** [comment]
Reopen when you have more details
