### ISSUE TITLE
Sudden errors while trying to run znc (4 errors)

### ISSUE THREAD

**Issue by coffeeneed** [znc/znc#1268]
This is the error i get when I run znc from the /.znc/ folder. Anyone know what's wrong? No changes has been made, just a server reboot and this happens. Cheers!

[ ok ] Checking for list of available modules...
[ ok ] Opening config [/home/joey/.znc/configs/znc.conf]...
[ ** ] Config was saved from ZNC 1.6.3. It may or may not work with current ZNC 1.2
[ ok ] Loading global module [webadmin]... [/usr/lib/znc/webadmin.so]
[ ok ] Binding to port [5001]...
[ ** ] Unhandled lines in Listener config!
[ ** ] uriprefix = /
[ ** ] Unrecoverable config error.

**Comment by wolfy1339** [comment]
Why are you using ZNC 1.2.x shouldn't you be using 1.6.x?

**Comment by coffeeneed** [comment]
@wolfy1339 Thanks for reply. That's the strange thing. I downloaded and installed the newest version a month ago (been running stable on IRC). Even the config file says Version = 1.6.3 (?!).

**Comment by DarthGandalf** [comment]
How did you install 1.6.3?
You also have installed 1.2.
Check `znc --version`,
`which znc` is likely to return `/usr/bin/znc`, that's the version from your OS distribution, you should remove it to reduce the confusion.
Depending on how you installed 1.6.3, probably it's in `/usr/local/bin/znc`.
