### ISSUE TITLE
Webadmin weird behavior - URIPrefix causes webadmin failures

### ISSUE THREAD

**Issue by lepasserby** [znc/znc#1287]
Hi!
When I have uriprefix enabled I can't navigate in webadmin, and firefox console complains of following error
"The stylesheet was not loaded because its MIME type, "text/html" is not "text/css".

**Comment by psychon** [comment]
I'm too lazy to try this out myself (not that I could really help anyway...): What does "can't navigate in webadmin" mean exactly? Could you e.g. provide a screenshot (or copy any error message that you see)? Perhaps you could also run znc in debug mode (`znc --debug`) and provide the debug output for the failing requests.

Also, what exactly are you doing?

**Comment by DarthGandalf** [comment]
Also, what ZNC version?
