### ISSUE TITLE
SASL: "verbose no" does not disable verbose mode

### ISSUE THREAD

**Issue by kmark** [znc/znc#1291]
On ZNC 1.6.3 the new verbose yes|no command for the SASL module does not allow me to disable verbose mode:

> \<Me> Verbose no
> \<*sasl> Verbose: true

This is on Debian 7.11.

Ref: #770 & 66daadfee8f7500311be73ea0480b9eb7aad6b82

**Comment by psychon** [comment]
https://github.com/znc/znc/blob/ae803769c2e51831777aa8dc327d8b36a13e1f4c/modules/sasl.cpp#L79

Replace `m_bVerbose = sLine.ToBool();` with `m_bVerbose = sLine.Token(1, true).ToBool();`. No, I'm too lazy to submit a pull request.
(The code tries to turn "verbose no" into a boolean, but it should only try to turn "no" into a boolean)

**Comment by DarthGandalf** [comment]
As a workaround for 1.6.3, `/znc reloadmod sasl` would disable the verbose mode.

**Comment by kmark** [comment]
Awesome! Thanks for the extremely fast movement in this.
