### ISSUE TITLE
ZNC fails to handle round robin irc network servers correctly.

### ISSUE THREAD

**Issue by shinji257** [znc/znc#1298]
When ZNC hits a timeout condition it doesn't try the next server ip in a dns round robin scenario.  Instead it will try the same ip it just timed out on which may or may not continue to timeout depending on if the server is down or if it might just be very slow to respond.  As it stands the timeout is about 4 minutes or so which makes for a long wait.

Example server: Freenode's round robin load balancing server address.

**Comment by shinji257** [comment]
Just found out that the person that reported this to me (since I can't reproduce it myself -- don't have a scenario to test on) is on ZNC 1.1-git-11-89f586d

**Comment by shinji257** [comment]
Disregard ticket.  It seems it is doing the round robin correctly based on a test I setup.

**Comment by DarthGandalf** [comment]
It was fixed in 1.6.0

**Comment by Mikaela** [comment]
And the original issue was #133.
