### ISSUE TITLE
Build issue on FreeBSD: unknown type name 'u_int'

### ISSUE THREAD

**Issue by fireglow** [znc/znc#1313]
Trying to build znc (at 1480177458f82c8d67f2ee8b1fe64ab940aca275) on FreeBSD (11-STABLE)

This happens during make:
```
Building core object Utils...
In file included from src/Utils.cpp:22:
In file included from ./include/znc/Utils.h:26:
/usr/include/sys/file.h:221:2: error: unknown type name 'u_int'
        u_int   xf_flag;        /* flags (see fcntl.h) */
        ^
src/Utils.cpp:387:21: warning: data argument not used by format string [-Wformat-extra-args]
                    sMessage.c_str());
                    ^
1 warning and 1 error generated.
gmake: *** [Makefile:134: src/Utils.o] Error 1
```

**Comment by fireglow** [comment]
I did some testing and I think commit f1ef8c79db7f8d04c5105eb817bd57a9c3ea0b4e is the one that causes the issue with FreeBSD.

**Comment by DarthGandalf** [comment]
debfdf6c02cc922a4e5a7b42eb5b608267c34fb5 fixes this. I'll merge it to master branch today... Didn't think that master is also affected.

P.S. I still want some FreeBSD CI service... E.g. https://github.com/travis-ci/travis-ci/issues/1818

**Comment by fireglow** [comment]
Confirmed, with the additional ifdef master builds fine on FreeBSD.
