### ISSUE TITLE
Random disconnections via ZNC

### ISSUE THREAD

**Issue by josvazg** [znc/znc#1317]
Have ZNC on an EC2 instance as my bouncer to my work IRC servers.

It has been disconnecting quite often, I would say more during "silent" chat moments.

I have tried chaning the ec2 instance in us-east-1 to one closer at eu-west-1, issues remain.
Also if I try without ZNC, direct connections don't seem to brake.

Some other colleages with a very similar setup and same EC2 instance tpy don't have the same issue.

How can I further debug this?

Sample disconnection:
* Disconnected ()
>NickServ< identify ****
>chanserv< invite #channel
* josvaz sets mode +r on josvaz
* Notify: user1 is online (myconn-ZNC)
...
* Notify: userN is online (myconn-ZNC)
* Now talking on #channel

**Comment by DarthGandalf** [comment]
ZNC version?
Output of znc -D? (replace passwords and other secret info with xxxxx)

2016-09-19 17:46 GMT+01:00 josvazg <notifications@github.com>:

**Comment by josvazg** [comment]
Version is:

version
<*status> ZNC 1.6.3+deb1 - http://znc.in
<*status> IPv6: yes, SSL: yes, DNS: threads, charset: yes

Will run today with znc -D and attack logs later here

**Comment by josvazg** [comment]
Aha!

znc -D has been quite useful for me to debug this issue:
1) I have NOT detected disconnections in the ZNC-IRC segment.
2) Disconnections on my side (USER-ZNC) seem to be related to me setting the VPN on or off, as I had all traffic routed via that VPN. My IP changed and my client had to reconnect to ZNC.

I believe I even had issues while still under the VPN cause it might reconfigure and change my IP from time to time, or reconnect everytime I wake up the laptop again.

**Comment by josvazg** [comment]
Documenting for other having similar issues:
1) Use znc -D on your znc host to debug if the disconnection is between you and ZNC or ZNC-IRC. (Using a screen session or similar is recommended to detach znc -D from ssh connections)

2) The logs from znc -D are usually quite clear on whether the user's client disconnected from ZNC or ZNC from IRC.

If the disconnection is from your client to ZNC, watch out for something chaning your public IP, like using a VPN and routing all traffic through it. VPN setup and tear down will break your connections with ZNC.
