### ISSUE TITLE
ZNC sends a QUIT when it thinks the connection is dead, please make this timeout configurable

### ISSUE THREAD

**Issue by Robby-** [znc/znc#1323]
When ZNC thinks the connection is dead it sends a QUIT to IRC and starts the reconnection process. I have however found that in many of these cases if ZNC would simply not touch the connection, or just wait longer, that the connection would resume again without issues, and so sending this QUIT is useless and just provides more noise in IRC. I can most of the time even still see other ZNC users quitting with the configured quit message when my connection survives the short temporary connection problem.

So, in light of this it would be nice if this hardcoded timeout would be made configurable.
##

**Comment by Mikaela** [comment]
Potential duplicate or at least related: https://github.com/znc/znc/issues/979.

**Comment by DarthGandalf** [comment]
Yep, it's duplicate.
