### ISSUE TITLE
OpenBSD 6.x64: autogen / configure and compile error

### ISSUE THREAD

**Issue by fred0r** [znc/znc#1335]
Hi,
i tried to compile the latest git-version of znc on OpenBSD6.x64.
For a quick overview look at:
https://gist.github.com/anonymous/fd2c7873262b38cc462d964ce7943902
I used the latest automake/autoconf available.
Thanks to psychon i was able to start compiling by using
`./configure CXX=/usr/local/bin/egcc`
But then i get this error:
https://gist.github.com/anonymous/3e0019042aae6c22608cb548398bfa89

**Comment by psychon** [comment]
Could you run `make V=1`? All of these linking errors sound like the C++ standard library is missing. However, I have no idea why that would happen (and I don't see any recent changes which could cause this). Do you know a last working ZNC version? Was it working with this compiler and compiler version? (=Could it be that an upgrade to the compiler broke things, and not a change in ZNC?)
Also, I find the various "do not use this function"-warnings funny. :-)

**Comment by fred0r** [comment]
Sure - here it is:
https://gist.github.com/anonymous/79b003c4844eb478724bda6bd4853b46
I looks like i 'fixed' it by running `./configure CXX=/usr/local/bin/eg++`
Now i was able to compile.

**Comment by psychon** [comment]
Oh. Sorry, this is my fault for telling you to set `CXX` to `egcc`. `CXX` should be a C++ compiler, but `egcc` is a C compiler.

**Comment by fred0r** [comment]
You're right psychon - i wondered also.
The initial compile ran with 'your egcc' and the failed linking.
At this time i had only this g++ installed:
` /usr/bin/g++ -v
Reading specs from /usr/lib/gcc-lib/amd64-unknown-openbsd6.0/4.2.1/specs
Target: amd64-unknown-openbsd6.0
Configured with: OpenBSD/amd64 system compiler
Thread model: posix
gcc version 4.2.1 20070719 
`
Before my successful compile i installed the latest g++ which installed to  `/usr/local/bin/eg++`:

`/usr/local/bin/eg++ -v
Using built-in specs.
COLLECT_GCC=/usr/local/bin/eg++
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-openbsd6.0/4.9.3/lto-wrapper
Target: x86_64-unknown-openbsd6.0
Configured with: /usr/obj/ports/gcc-4.9.3/gcc-4.9.3/configure --enable-libgcj --without-jar --verbose --program-transform-name='s,^,e,' --disable-nls --with-system-zlib --disable-libmudflap --disable-libgomp --disable-tls --with-as=/usr/bin/as --with-ld=/usr/bin/ld --with-gnu-ld --with-gnu-as --enable-threads=posix --enable-wchar_t --with-gmp=/usr/local --enable-languages=c,c++,fortran,objc,java,ada --disable-libstdcxx-pch --enable-cpp --prefix=/usr/local --sysconfdir=/etc --mandir=/usr/local/man --infodir=/usr/local/info --localstatedir=/var --disable-silent-rules --disable-gtk-doc
Thread model: posix
gcc version 4.9.3 (GCC) 
`
