### ISSUE TITLE
ZNC joins channels, then auths NickServ

### ISSUE THREAD

**Issue by thegreatestminer** [znc/znc#1337]
Basically, I use the nickserv module to auth into an IRC server, but for some reason, it seems like it joins the channels THEN activates nickserv.

Is there anyway to make it auth to nickserv BEFORE joining the channels?

**Comment by dgw** [comment]
I know the party line on this is going to be "Use SASL". But it really would be nice if the nickserv module could delay joining channels until it has authenticated. That said, there are so many different services with so many different NickServ messages (not even counting translations) that it's not likely to happen.

**Comment by RealKindOne** [comment]
You have a few options, 

1, Use http://wiki.znc.in/Sasl or http://wiki.znc.in/Cert assuming the network supports it.

2, Set a join delay:
    ```/msg *controlpanel setnetwork $me network joindelay number_of_seconds```
 
   If you want to do it via webadmin: Your settings -> Edit [network] -> Channel join delay.

**Comment by Zarthus** [comment]
Does PERFORM support a waiting time yet?

**Comment by thegreatestminer** [comment]
Last I checked, no.

**Comment by thegreatestminer** [comment]
OK, just tried the channel join delay, works perfectly. Thanks for the help! 👍

**Comment by iliv** [comment]
> You have a few options,
...
> 2, Set a join delay: `/msg *controlpanel setnetwork $me network joindelay number_of_seconds`
> 
> If you want to do it via webadmin: Your settings -> Edit [network] -> Channel join delay.

Using ZNC 1.8.2+deb2build5, this *controlpanel command no longer works.

The new syntax is:

```
/msg *controlpanel setnetwork joindelay username network seconds
```

FYI, by default joindelay value seems to be set at 0.
