### ISSUE TITLE
[Ubuntu 16.04.1 + ZNC 1.6.3+deb1] SSL handshake timeouts

### ISSUE THREAD

**Issue by Cysioland** [znc/znc#1339]
Nothing is shown on stderr. Connecting over separate, unencrypted port works fine, connecting over SSL port fails.

Let me know, what do you need to properly reproduce and debug this.

**Comment by Mikaela** [comment]
Run ZNC with the `-D` (debug) flag.

**Comment by Cysioland** [comment]
Absolutely nothing relevant shows neither on stdout, nor on stderr

**Comment by teward** [comment]
And you are sure the port is open and not blocked by a firewall or behind NAT?

**Comment by Cysioland** [comment]
PORT      STATE SERVICE
31337/tcp open  Elite

And all ports are open on my IRC end. I did not mess with my firewall 
config, so the port is still open.

**Comment by Cysioland** [comment]
PORT      STATE SERVICE
31337/tcp open  Elite

And all ports are open on my IRC end. I did not mess with my firewall 
config, so the port is still open.

Results of `openssl s_client` ran from the localhost:

``` 
CONNECTED(00000003)
140367625135768:error:140790E5:SSL routines:ssl23_write:ssl handshake failure:s23_lib.c:177:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 305 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1478445860
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

**Comment by teward** [comment]
You wouldn't happen to be trying to connect over SSL at other plain text port would you?  I don't think ZNC supports SSL and plain text on the same port...

**Comment by Cysioland** [comment]
That's why I set up plaintext on another port, but, to satiate your 
curiosity, connecting plaintext over not-working SSL port still failed.

**Comment by psychon** [comment]
Try the same port number over which you got a successful plain text connection. If znc --debug does not say anything, then the connection does not reach znc. It will print something for sure even before it actually accepts the connection.

**Comment by Cysioland** [comment]
Do I have to try SSL over it, or plaintext?

**Comment by teward** [comment]
Either - it'll print something in either case, I believe

**Comment by Cysioland** [comment]
It was not a bug, the PEM file was wrong.
