### ISSUE TITLE
[Module request]Part channels when dropped

### ISSUE THREAD

**Issue by MAGICCC** [znc/znc#1344]
Is somebody willing to write a module to detect when a channel got dropped and then the client will be parted automatically?

**Comment by DarthGandalf** [comment]
What do you mean by dropped?

**Comment by MAGICCC** [comment]
Deregistering a channel by the user or autodropping by services because inactivity.

**Comment by DarthGandalf** [comment]
How is the module supposed to know when that happens?

**Comment by MAGICCC** [comment]
Yes that's the problem. Some networks set a channelmode to prevent channel modes from being reset when the last user leaves a registered channel, but the channelmode is not always the same.
Using services won't help as well since Quakenet has different services (Q) than Freenode/Rizon (both ChanServ)

**Comment by DarthGandalf** [comment]
I don't think this belongs here. Such module won't be added upstream.
Feel free to implement it and publish on http://wiki.znc.in as an external module.

**Comment by MAGICCC** [comment]
I didnt said it should be merged into master anyway. Gonna find some guy who wants to code this
