### ISSUE TITLE
znc --makeconf username does not correctly allow alphanumeric

### ISSUE THREAD

**Issue by joekir** [znc/znc#1349]
`znc --makeconf` 
username validation does not correctly allow all alphanumerics.

e.g try "77abc" this will be rejected, then try "abc77" this will be accepted. Both should be valid alphanumeric.

**Comment by Mikaela** [comment]
I think the IRC RFC forbids usernames from starting with numbers and I didn't check, but I think ZNC uses username as the default nickname, so I don't think this is an issue.

**Comment by joekir** [comment]
Ah yes 
`nickname = ( letter / special ) *8( letter / digit / special / "-" )` 
From [section 2.3.1](https://tools.ietf.org/html/rfc2812#section-2.3.1) 

Thanks!
