### ISSUE TITLE
Openvpn screwed things up?

### ISSUE THREAD

**Issue by zotoli** [znc/znc#1356]
ZNC was working beautifully on my vps until I installed Openvpn at the same droplet. Now it is giving me  took too long to respond error on browser and (Connection timed out) in hexchat. Any idea what might have caused this?

**Comment by Mikaela** [comment]
Post the relevant part of `znc -D` and your znc version and bindhost can also be helpful.

The support channel would be #znc at freenode.

**Comment by DarthGandalf** [comment]
Looks like Openvpn is misconfigured. Without any details about your configuration it's hard to say anything in particular.

**Comment by zotoli** [comment]
Thanks for the replies, Openvpn is working so I was just wondering if there is a known issue that causes one to not work with the other. I will go hit up the znc channel in freenode. thanks again.

**Comment by zotoli** [comment]
Solved my problem, somehow the vpn setup removed the rule that allows the port, added it back using:

sudo ufw allow <port>
sudo ufw reload

works again,
