### ISSUE TITLE
Alphabetically order building of modules during compilation

### ISSUE THREAD

**Issue by Zarthus** [znc/znc#1358]
It would be nice if compilation of modules were alphabetically sorted, so you roughly know when the module you are intending to build will be built.

https://github.com/znc/znc/blob/384681351228c1a4e4be2bea3d7ae7585409a210/modules/Makefile.in#L117

ps: Are the rm -rf's there safe? Won't that delete everything if the variables are unset?

**Comment by DarthGandalf** [comment]
If you want to build a specific module, you can just say `make thatmodule.so`. Also consider interaction with `-j` flag.

**Comment by Zarthus** [comment]
I don't want to make a specific module, I just want the list of modules that is being compiled to be alphabetically sorted since it takes quite a while and there's no way of knowing how far in you're at in the process.

**Comment by DarthGandalf** [comment]
If you use CMake, it'll say current completion in percents, with either
ninja or makefile generator.

2017-01-19 16:40 GMT+00:00 Jos Ahrens <notifications@github.com>:

**Comment by Zarthus** [comment]
CMake is only a recent addition, many people will probably stick to the known ./configure method unless something tells them there's a better alternative.
