### ISSUE TITLE
Login to webadmin behind nginx reverse proxy results in "Your browser does not have cookies enabled for this site!"

### ISSUE THREAD

**Issue by eggshell** [znc/znc#1372]
OS: Ubuntu Xenial 16.04.1
znc version: 1.6.4

`TrustedProxy = 127.0.0.1` is in `znc.conf`

nginx vhost config:
```
server {
    listen 80;
    listen [::]:80;
    server_name znc.mydomain.com;

    location / {
        proxy_pass https://127.0.0.1:6667;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
```

Attempting to log in to webadmin via `znc.mydomain.com` results in the error `Your browser does not have cookies enabled for this site!` and a failed login. Logging into web admin by pointing a browser to the ip:port works fine.

**Comment by bjoe2k4** [comment]
No problems here. I have configured a seperate listener for the Webinterface.

```
Version = 1.7.x

<Listener listener0>
        AllowIRC = false
        AllowWeb = true
        Host = 127.0.0.1
        IPv4 = true
        IPv6 = false
        Port = 21212
        SSL = false
        URIPrefix = /znc/
</Listener>
```
```
        location /znc/ {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://127.0.0.1:21212;
        }
```
Btw, you don't need TLS encryption for http on localhost. Let nginx handle that. That may also be the origin of your error.

**Comment by eggshell** [comment]
@bjoe2k4 thanks for the help! I had originally tried without TLS encryption for http on localhost, but it resulted in 502 errors from nginx, which was equally as confusing. Enabling it seems to be the only way to get the webadmin login page to show up, but then I hit the cookie issue.

Here's a snippet of my `znc.conf`:
```
<Listener listener0>
        AllowIRC = true
        AllowWeb = true
        IPv4 = true
        IPv6 = false
        Port = 6667
        SSL = true
        URIPrefix = /
</Listener>
```

I'm configuring nginx so it reverse proxies to a [subdomain](http://wiki.znc.in/Reverse_proxy#As_a_subdomain) rather than a [subURL](http://wiki.znc.in/Reverse_proxy#As_a_subURL), though I have tried the subURL method with similar results. I also have the webadmin and irc protocol on the same listener.

**Comment by DarthGandalf** [comment]
Try enabling debug logging on nginx side, to see what headers it sends and receives, and check what headers browser sends and receives, e.g. with Firebug.

**Comment by DarthGandalf** [comment]
When you have more details to reproduce, reopen.

**Comment by ngm** [comment]
I got this error after I had logged in the webadmin with SSL enabled, then turned SSL off in config, restarted, and tried to log in again.

I just needed to delete the cookie XXXX-SessionId, where XXXX is the ZNC port number.

**Comment by lodenrogue** [comment]
I faced this issue today. No cookies were set in my browser, Brave, but when I switched to Safari it worked fine.
