### ISSUE TITLE
Many route_replies messages

### ISSUE THREAD

**Issue by sunrunner20** [znc/znc#1394]
I'm connected to three IRC servers, and only freenode has this problem (other two are efnet and synirc). I'm bombarded with route_replies messages and often disconnected. I cannot completely rule out connectivity. 

Here's the list from the past few hours:

* Loaded log from Fri Apr  7 17:17:28 2017
 
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##devops %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
* Disconnected (Remote host closed socket)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##csharp %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1204295609
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##networking %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##pfsense %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##freenas-classic %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1204925609
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: whois sunrunner20
<*route_replies> Expected replies: 
<*route_replies> 311
<*route_replies> 312
<*route_replies> 313
<*route_replies> 317
<*route_replies> 319
<*route_replies> 301
<*route_replies> 276
<*route_replies> 330
<*route_replies> 338
<*route_replies> 378
<*route_replies> 671
<*route_replies> 307
<*route_replies> 379
<*route_replies> 760
<*route_replies> 318 (last)
<*route_replies> 401 (last)
<*route_replies> 402 (last)
<*route_replies> 431 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1204955609
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1204985609
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1205015609
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1205045609
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1206464199
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO #reddit-sysadmin %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1206485609
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: whois sunrunner20
<*route_replies> Expected replies: 
<*route_replies> 311
<*route_replies> 312
<*route_replies> 313
<*route_replies> 317
<*route_replies> 319
<*route_replies> 301
<*route_replies> 276
<*route_replies> 330
<*route_replies> 338
<*route_replies> 378
<*route_replies> 671
<*route_replies> 307
<*route_replies> 379
<*route_replies> 760
<*route_replies> 318 (last)
<*route_replies> 401 (last)
<*route_replies> 402 (last)
<*route_replies> 431 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##vb.net %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##windows %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1207745610
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##mono %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1208045609
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: PING LAG1208075610
<*route_replies> Expected replies: 
<*route_replies> PONG (last)
<*route_replies> 402 (last)
<*route_replies> 409 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO #chef %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##webdev %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)

**Comment by dgw** [comment]
I've had `silent yes` set for a loooooong time, but I remember getting this sort of thing far more on freenode than any other network I connect to. Not sure why.

As an aside, congrats on getting the FireWire (IEEE 1394) issue.

**Comment by sunrunner20** [comment]
Haha, I didn't even think of anything when I got 1394 as the ticket number.

**Comment by sunrunner20** [comment]
It seems dropping recompiling client_buffer with a fix for the warning (see pullrequest), and/or downing the rate limit for freenode to 4burst .5/s has solved this issue.

**Comment by sunrunner20** [comment]
Of course as soon as I say that I get another one:
<*route_replies> This module hit a timeout which is probably a connectivity issue.
<*route_replies> However, if you can provide steps to reproduce this issue, please do report a bug.
<*route_replies> To disable this message, do "/msg *route_replies silent yes"
<*route_replies> Last request: WHO ##linux %chtsunfra,152
<*route_replies> Expected replies: 
<*route_replies> 402 (last)
<*route_replies> 352
<*route_replies> 315 (last)
<*route_replies> 354
<*route_replies> 403 (last)

**Comment by sunrunner20** [comment]
I rebuilt my ZNC, did not reinstall colloquy push notification plugin, but went with the supported generic PUSH plugin. I am no longer seeing this issue. This was either a result of the plugin or a bad config, closing this issue as a result.
