### ISSUE TITLE
-d <datadir> parameter takes space after option argument.

### ISSUE THREAD

**Issue by D1W0U** [znc/znc#1401]
Please, remove the space that the ZNC takes from the command line when invoking the program by this way:

./znc -d ./

It's going to search by path " ./configs/znc.conf" for example instead of "./configs/znc.conf".

Thanks!

**Comment by DarthGandalf** [comment]
Show config.log
What shell is that?
Did you try --datadir?

**Comment by D1W0U** [comment]
Oh sorry, it was my fault using the execve() system call on a program I used to change uid and gid in a chroot for chrooting znc.

Here is the error:
char *args[] = { "./znc", "-d .", NULL };

should be:
char *args[] = { "./znc", "-d", ".", NULL };

Thanks for the interest and the help!
