### ISSUE TITLE
Log Module logs everything

### ISSUE THREAD

**Issue by antonstarlid** [znc/znc#1405]
Its impossible to get log module to work and its bad written as no one understands how it actully works.

Insted of do "SetRules whatever" in one line why don´t have it as perform and let you add and delete stuff one by one?

And insted of have it to log everything by defualt why don´t let you don´t log anything by default or ignore everything by default depending on how mutch you like to log

Like me i just want to log one channel but it seems impossible to make it do that as it log everything whatever i do, the documentation for it don´t tell you mutch about how the rules for it work ether.

I have try whit "SetRules #znc !*" as it in my eyes match #znc first and that pass while the other rule ignore everything else but this don´t seems to be the case

**Comment by lib2k** [comment]
The documentation is straight forward and easy to understand. Ask in #znc if you don't understand something.

>And insted of have it to log everything by defualt why don´t let you don´t log anything by default or ignore everything by default depending on how mutch you like to log  

That's not the purpose of log. It works as intended and logs everything **by default** instead of having to add every single rule that you want logged, just like any other similar piece of code.

If you want to log one particular channel without logging everything else, use the proper blacklisting syntax with wildcards.

**Comment by antonstarlid** [comment]
I have actully asked there 2 days now, and no one seems to understand how the module is working

**Comment by antonstarlid** [comment]
I run 1.6.3 and have this rules now

`
[2017-05-08] [22:35:56]  »» [Whiskey] setrules #php.se !#* !*
[2017-05-08] [22:35:56]  »» [*log] +=========+=================+
[2017-05-08] [22:35:56]  »» [*log] | Rule | Logging enabled |
[2017-05-08] [22:35:56]  »» [*log] +=========+=================+
[2017-05-08] [22:35:56]  »» [*log] | #php.se | true |
[2017-05-08] [22:35:56]  »» [*log] +---------+-----------------+
[2017-05-08] [22:35:56]  »» [*log] | #* | false |
[2017-05-08] [22:35:56]  »» [*log] +---------+-----------------+
[2017-05-08] [22:35:56]  »» [*log] | * | false |
[2017-05-08] [22:35:56]  »» [*log] +=========+=================+
`
It still seems to log everything

**Comment by DarthGandalf** [comment]
> its bad written as no one understands how it actully works

That's not a good way to ask for help, you know.

How many log modules do you have loaded? Show `/znc listmods`

**Comment by antonstarlid** [comment]
Look like i have one DarthGandalf

> [2017-05-09] [01:27:05]  »» [*status] Global modules:
> [2017-05-09] [01:27:05]  »» [*status] +===========+===========+
> [2017-05-09] [01:27:05]  »» [*status] | Name | Arguments |
> [2017-05-09] [01:27:05]  »» [*status] +===========+===========+
> [2017-05-09] [01:27:05]  »» [*status] | webadmin | |
> [2017-05-09] [01:27:05]  »» [*status] +-----------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | modperl | |
> [2017-05-09] [01:27:05]  »» [*status] +-----------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | modpython | |
> [2017-05-09] [01:27:05]  »» [*status] +===========+===========+
> [2017-05-09] [01:27:05]  »» [*status] User modules:
> [2017-05-09] [01:27:05]  »» [*status] +============+===========+
> [2017-05-09] [01:27:05]  »» [*status] | Name | Arguments |
> [2017-05-09] [01:27:05]  »» [*status] +============+===========+
> [2017-05-09] [01:27:05]  »» [*status] | disconkick | |
> [2017-05-09] [01:27:05]  »» [*status] +------------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | chansaver | |
> [2017-05-09] [01:27:05]  »» [*status] +------------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | push | |
> [2017-05-09] [01:27:05]  »» [*status] +------------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | fix_lagchk | |
> [2017-05-09] [01:27:05]  »» [*status] +============+===========+
> [2017-05-09] [01:27:05]  »» [*status] Network modules:
> [2017-05-09] [01:27:05]  »» [*status] +==========+===========+
> [2017-05-09] [01:27:05]  »» [*status] | Name | Arguments |
> [2017-05-09] [01:27:05]  »» [*status] +==========+===========+
> [2017-05-09] [01:27:05]  »» [*status] | fish | |
> [2017-05-09] [01:27:05]  »» [*status] +----------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | perform | |
> [2017-05-09] [01:27:05]  »» [*status] +----------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | nickserv | |
> [2017-05-09] [01:27:05]  »» [*status] +----------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | keepnick | |
> [2017-05-09] [01:27:05]  »» [*status] +----------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | crypt | |
> [2017-05-09] [01:27:05]  »» [*status] +----------+-----------+
> [2017-05-09] [01:27:05]  »» [*status] | log | |
> [2017-05-09] [01:27:05]  »» [*status] +==========+===========+

**Comment by DarthGandalf** [comment]
As verified on IRC, it works.
