### ISSUE TITLE
auto log in on irc on connect ?

### ISSUE THREAD

**Issue by LoloLaurentiu** [znc/znc#1417]
Hello,
is it possible that my ZNC will auto perform a login command when it connects?

**Comment by psychon** [comment]
In descending order of preference: There is the sasl module, the nickserv module and the perform module.

**Comment by psychon** [comment]
https://wiki.znc.in/Sasl
https://wiki.znc.in/Nickserv
https://wiki.znc.in/Perform

Oh and there is even a Q module: https://wiki.znc.in/Q
