### ISSUE TITLE
ControlPanel/AddServer: Permit specifying port

### ISSUE THREAD

**Issue by Zarthus** [znc/znc#1426]
Or alternatively: Do not assume 6667.

ControlPanel/AddServer adds the server for port 6667, but you can't specify +6697 instead

**Comment by teward** [comment]
I'm confused - *where* do you want this to happen?

You can already add a different port when you use AddServer by specifying the port.

What version of ZNC are you observing this on?  Have you actually *tried* adding a different server with a different port?

**Comment by DarthGandalf** [comment]
Fixed by you in #1428
