### ISSUE TITLE
route-replies: if a Tcldrop and a Weechat are connecting to ZNC all at once, everything falls off the rails and at minimum the Weechat needs to be reconnected (it thinks the bouncer is stoned)

### ISSUE THREAD

**Issue by janicez** [znc/znc#1429]
This happens with a channel list around 45 long.

**Comment by DarthGandalf** [comment]
Any details?
What exactly is "stoned"?
What version?
Logs of raw traffic?

**Comment by janicez** [comment]
"stoned" as in lagged out.

Version of ZNC based on f9f9dec1ad86b8e3db5a8857a0d1d02fe5b97419 with modifications that do not affect the behaviour of route-replies.

Often the errors are for messages like "WHOIS Ellenor", "PING" and "WHO <channel>" after both clients reconnect with ZNC reconnecting to the server - it's usually the storm of resynchronisations, that's fine (if inconvenient) without route-replies, but breaks with.

route-replies has not been kind to me in the past - it makes Irssi, WeeChat, and other clients think the connection is stoned, it gets lagged, loses stuff... on good connections by the way!

I can't give logs of raw traffic due to an extremely large amount of personal data that would be involved.

**Comment by DarthGandalf** [comment]
I assure you: without logs there is nothing to be done here.
