### ISSUE TITLE
UTF-8 and ISO-8859-1 combination doesn't work.

### ISSUE THREAD

**Issue by apliedes** [znc/znc#1433]
I have my charset set to "Try to parse as UTF-8 and as   ISO-8859-1  , send as UTF-8 (recommended)", and UTF-8 works fine, but other people's ISO-8859-1 Scandinavian characters show as unknown characters in both HexChat and XChat Azure clients (both clients set to UTF-8). My ZNC version is 1.6.5+deb1, running on current Debian-stable.

**Comment by DarthGandalf** [comment]
Set it in network settings, not in user settings. User settings is for the
client encoding, between ZNC and your IRC client.

2017-08-11 8:51 GMT+01:00 apliedes <notifications@github.com>:

**Comment by apliedes** [comment]
Doh, that fixed it. Thank you, and sorry about the issue. It might be worthwhile to mention this at the client encoding settings though.

**Comment by DarthGandalf** [comment]
It is mentined there, right above it :(
Do you have any suggestion how to make it more clear?

2017-08-11 10:32 GMT+01:00 apliedes <notifications@github.com>:

**Comment by DarthGandalf** [comment]
You're not the first one who is confused by this setting.

2017-08-11 10:32 GMT+01:00 apliedes <notifications@github.com>:

**Comment by apliedes** [comment]
Ah, it's not mentioned in my version (1.6.5+deb1). Hopefully the problem will go away once everyone updates.

**Comment by DarthGandalf** [comment]
It is there :)

https://github.com/znc/znc/blob/znc-1.6.5/modules/data/webadmin/tmpl/add_edit_user.tmpl#L291

2017-08-11 10:43 GMT+01:00 apliedes <notifications@github.com>:
