### ISSUE TITLE
Travis CI build takes 4 hours to complete, and randomly* fails.

### ISSUE THREAD

**Issue by Zarthus** [znc/znc#1447]
All of the following builds should have passed, but either didn't due to negative codecov (of less than a percentage) or the CI (travis) failing:
```
FAIL transperancy: Make the user aware that DEBUG mode is enabled. #1446 opened 21 hours ago by Zarthus   1
PASS debugging: Add Filter method to hide filter sensitive data #1445 opened 22 hours ago by Zarthus   1
PASS Tidy up README #1444 opened 2 days ago by Zarthus   2
FAIL route_replies: rizon: [MODE] Add 403, 442 expectations #1443 opened 2 days ago by Zarthus   1
FAIL Remove unused AUTHORS symlink opened 5 days ago by Zarthus   1
```

**Comment by DarthGandalf** [comment]
Codecov accepts configuration in yaml, feel free to send pull request
Or do you propose to remove CI?

**Comment by Zarthus** [comment]
I wrote an issue so it's not forgotten. I don't care what the solution looks like, closing this issue because "someone can submit a PR instead" seems a bit counter-intuitive, we might as well close all issues then.
