### ISSUE TITLE
"version `OPENSSL_1.0.2d' not found" (current version OpenSSL 1.1.0f)

### ISSUE THREAD

**Issue by rhazor** [znc/znc#1457]
I upgraded my Ubuntu and all its packages and libraries and znc broke down.

```
libssl-dev is already the newest version (1.1.0f-2~ubuntu16.04.1+deb.sury.org+1).
libssl1.0.0 is already the newest version (1.0.2k-1+deb.sury.org~xenial+1).
```

```
/usr/lib/x86_64-linux-gnu # sudo apt-get install libssl1.0.0 libssl-dev --reinstall
Reading package lists... Done
Building dependency tree
Reading state information... Done
Reinstallation of libssl1.0.0 is not possible, it cannot be downloaded.
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/1,578 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 140718 files and directories currently installed.)
Preparing to unpack .../libssl-dev_1.1.0f-2~ubuntu16.04.1+deb.sury.org+1_amd64.deb ...
Unpacking libssl-dev:amd64 (1.1.0f-2~ubuntu16.04.1+deb.sury.org+1) over (1.1.0f-2~ubuntu16.04.1+deb.sury.org+1) ...
Setting up libssl-dev:amd64 (1.1.0f-2~ubuntu16.04.1+deb.sury.org+1) ...
```

```
/usr/lib/x86_64-linux-gnu # su - znc -c znc
znc: /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by znc)
znc: /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.2: version `OPENSSL_1.0.2d' not found (required by znc)
```

I ran openssl version and got different (newer) version, maybe that's the problem? How do I tell ZNC to use current version?

```
openssl version
OpenSSL 1.1.0f  25 May 2017
```

**Comment by psychon** [comment]
Recompile ZNC. If you use ZNC from Ubuntu, then tell them their OpenSSL package is broken. There is nothing that we can do about this.
From the error message, it sounds like you went back to an *older* OpenSSL version... either that, or Ubuntu broke their packaging.

> libssl-dev is already the newest version (1.1.0f-2~ubuntu16.04.1+deb.sury.org+1).
> libssl1.0.0 is already the newest version (1.0.2k-1+deb.sury.org~xenial+1).

Those version numbers are "funny". The text on http://deb.survy.org sounds like you are now using OpenSSL from Ubuntu, but from this web page instead.

Sorry, but there is nothing that we can do about broken openssl libraries. Complain to either Ubuntu or deb.survy.org.
