### ISSUE TITLE
Wrong English translations

### ISSUE THREAD

**Issue by psychon** [znc/znc#1465]
- [ ] https://github.com/znc/znc/commit/b8948081639dc1469cade4eb7d587b5f471282a2#diff-29017c32fc7e54eb3ad373b49ef002f1R714
The English plural text uses {2} twice and {1} is missing
- [ ] https://github.com/znc/znc/blob/master/modules/controlpanel.cpp#L1531 Missing space in "hasno"

**Comment by psychon** [comment]
What about https://github.com/znc/znc/blob/master/modules/controlpanel.cpp#L1531 Missing space in "hasno"?
(I edited this issue after creating it and I guess you only looked at the mail; also, I don't have any ZNC git clone laying around so just creating an issue was so much easier than creating a PR; sorry for that)

**Comment by DarthGandalf** [comment]
Yes, I looked only at email.
You don't need git clone laying around, https://help.github.
com/articles/editing-files-in-your-repository/ :P
Anyway, thanks for finding these!

2017-11-27 8:24 GMT+00:00 Uli Schlachter <notifications@github.com>:
