### ISSUE TITLE
Option to list only for connections from localhost (ssh port forwarding use case)

### ISSUE THREAD

**Issue by Tuxdude** [znc/znc#1470]
Currently there is an option to listen for incoming connections from either an IPv4 address or an IPv6 address or both. It will be great if znc only allows listening on localhost.

One use case for this is exposing this port over SSH to a remote machine using port forwarding and at the same time not letting any IRC client be able to connect to the znc server directly.

**Comment by barbequesauce** [comment]
Piggybacking on this with an additional idea - the option to connect from local network only, allowing anyone on the same subnet as the server to connect to znc instead of relying on firewall rules to accomplish the same goal.

**Comment by Tuxdude** [comment]
After posting this, I was playing around with few options in the Web UI and found `BindHost` which allows me to specify the addresses to listen on.

In the config file it is present under `Listener/Host`

**Comment by dgw** [comment]
In user settings, under **Authentication**, there is an **Allowed IPs** field:

> _Leave empty to allow connections from all IPs.
Otherwise, one entry per line, wildcards * and ? are available._

Setting the global **BindHost** allows listening on localhost only, as @Tuxdude posted.

**Comment by DarthGandalf** [comment]
Also listeners configuration is available in `/msg *status AddPort`, not only in webadmin.
