### ISSUE TITLE
ZNC Error After Reboot Server ! 

### ISSUE THREAD

**Issue by fahadmehar** [znc/znc#1482]
After my server get reboted i getting this error the current version was 1.6.4 

[ .. ] Checking for list of available modules...
[ >> ] ok
[ .. ] Opening config [/home/Fahad/.znc/configs/znc.conf]...
[ >> ] ok
[ ** ] Config was saved from ZNC 1.6.4. It may or may not work with current ZNC 1.4
[ .. ] Loading global module [webadmin]...
[ >> ] [/usr/lib/znc/webadmin.so]
[ .. ] Binding to port [+3000]...
[ >> ] ok
[ ** ] Unhandled lines in Listener config!
[ ** ] uriprefix = /
[ ** ] Unrecoverable config error.

**Comment by DarthGandalf** [comment]
As it says, you are trying to run ZNC 1.4 with config from ZNC 1.6.4. Why
are you downgrading the version?

2018-01-09 10:55 GMT+00:00 Fahad <notifications@github.com>:

**Comment by fahadmehar** [comment]
I even don't know why its happen? My server get rebooted... after that when i try to run ZNC i getting this message...  Now What i do ?

**Comment by fahadmehar** [comment]
What's the Solution ?

**Comment by dgw** [comment]
Reinstall the correct version of ZNC.

**Comment by fahadmehar** [comment]
@dgw I delete the old version I am installling new.  It ask me for sudo password.

**Comment by fahadmehar** [comment]
@dgw Fahad@168:~/znc-1.6.5$ make install
test -d /usr/local/bin || /usr/bin/install -c -d /usr/local/bin
test -d /usr/local/include/znc || /usr/bin/install -c -d /usr/local/include/znc
/usr/bin/install: cannot change permissions of '/usr/local/include/znc': No such file or directory
Makefile:172: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by DarthGandalf** [comment]
Not ZNC issue. #znc on freenode might help you to install it.
