### ISSUE TITLE
What to do with IRC servers using Let's Encrypt certificates?

### ISSUE THREAD

**Issue by kode54** [znc/znc#1490]
I have several IRC servers I connect to that are currently using Let's Encrypt certificates, and I guess because they're not sending the entire trust chain with their connection requests, I get untrusted certificate notices every 2 months as they replace their certificates with new ones a month or so before the old ones expire. I end up having to add a new fingerprint every two months or so.

Is there something I can tell these server administrators about configuring their services properly with Let's Encrypt? Or is this a ZNC bug?

**Comment by CyberShadow** [comment]
> and I guess because they're not sending the entire trust chain with their connection requests

You can verify that hypothesis using `s_client`:

```
$ openssl s_client -showcerts -connect irc.badssl.com:6667 < /dev/null
```

**Comment by CyberShadow** [comment]
FWIW, the latest `certbot` version generates the following files and descriptions:

```
`fullchain.pem`: the certificate file used in most server software.
`cert.pem`     : will break many server configurations, and should not be used
                 without reading further documentation (see link below).
```

So not using `fullchain.pem` is probably a mis-configuration that ought to be fixed server-side.

You could probably work around it locally by importing the Let's Encrypt intermediary certificate to your trusted root certificates store.

(The above is not an authoritative answer; I might be completely wrong.)

**Comment by teward** [comment]
@CyberShadow I dont think thats whats being asked or addressed here.

@kode54 Theres no way around that in the existing infrastructure - new cert, new fingerprint.  Not really a bug, either, really, though, I dont think.

**Comment by CyberShadow** [comment]
@kode54 Do you use "Trust the PKI", or do you use certificate fingerprint whitelisting only?

If you enabled PKI verification, then see my posts above. Otherwise see @teward's answer.

**Comment by DarthGandalf** [comment]
Do you have ca-certificates package installed? (its name can be different depending on your OS)

**Comment by DarthGandalf** [comment]
@teward only if certificate is self-signed. In let's encrypt case, there is a common root cert, so manually approving every new cert is not needed.

**Comment by kode54** [comment]
The servers are not sending the full chain, only the tip certificate. And I am only using certificate fingerprint whitelisting, not trusting an entire PKI. I'm not sure how to go about that, on an Ubuntu 16.04 LTS server.

**Comment by DarthGandalf** [comment]
What ZNC version? PKI and therefore Let's encrypt are trusted by default, provided ca-certificates package is installed.

**Comment by kode54** [comment]
ca-certificates is installed. Connecting to these servers without the fingerprint added results in:

```
21:01 <*status> Disconnected from IRC (Invalid SSL certificate: unable to get local issuer certificate, unable to verify the first certificate). Reconnecting...
```

**Comment by DarthGandalf** [comment]
Can you share name of server?

**Comment by kode54** [comment]
irc.kitsunet.net port 6697 for TLS.

**Comment by DarthGandalf** [comment]
> The servers are not sending the full chain, only the tip certificate.

Yep.
If server is misconfigured, we can't do much about it. Ask him to send correct certificate.

**Comment by leak** [comment]
I have a similar issue with `irc.rizon.net:6697` but it seems to return the chain, so not sure if this is actually the same issue, although they are using Let's Encrypt too.

I suspect in this case it is because of server round-robin. Any idea how to deal with that case?

**Comment by DarthGandalf** [comment]
@leak what is the exact error you're getting?

**Comment by leak** [comment]
It is not an error, but rather the prompt `If you trust this certificate, do /znc AddTrustedServerFingerprint.....` every time I restart znc (either because znc or depending libraries updated)

**Comment by DarthGandalf** [comment]
No, there is an error, it's above this prompt. Right before details of the certificate.

**Comment by leak** [comment]
`[14:09:18] <*status> Disconnected from IRC (Invalid SSL certificate: hostname doesn't match). Reconnecting...`

**Comment by DarthGandalf** [comment]
Show the certificate details you're getting, and output of `/znc listservers`

**Comment by leak** [comment]
https://gist.github.com/leak/7cdb4202061ccefe50f2ab99dd8f851e

listservers at the end

**Comment by DarthGandalf** [comment]
Well, this certificate is for irc.rizon.net, but you're connecting to irc6.rizon.net. They are different domains. Connect to irc.rizon.net instead.
