### ISSUE TITLE
Add support for networks ranges in TrustedProxy

### ISSUE THREAD

**Issue by blar** [znc/znc#1503]
With docker my http proxy (haproxy or traefik) for the znc web frontend is anywhere in the [private network](https://en.wikipedia.org/wiki/Private_network) range between 10.0.0.0 and 10.255.255.255. The ip of the load balancer also changes every time it is reconfigured or restarted.

Please add the CIDR notation to TrustedProxy to solve this issue.

TrustedProxy = 10.0.0.0/8

**Comment by DarthGandalf** [comment]
It's in 1.7 already
#1219
