### ISSUE TITLE
ZNC segfaults when compiled with Clang

### ISSUE THREAD

**Issue by wolfy1339** [znc/znc#1508]
I compiled a fresh (removed all previous build files) copy of ZNC with Clang, and when I go to run it, it segfaults.
If debugging is enabled at build time, everything runs fine

```
$ uname -a
Linux prestige 4.13.0-37-generic #42-Ubuntu SMP Wed Mar 7 14:13:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ clang --version
clang version 4.0.1-6 (tags/RELEASE_401/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ znc --version
ZNC 1.7.x-git-930-d6bfe504 - https://znc.in
IPv6: yes, SSL: yes, DNS: threads, charset: yes, i18n: no, build: autoconf
```

**Comment by psychon** [comment]
Well.... backtrace from `gdb`? Some information collected via `valgrind`? An error message? Anything more than "it crashes"?

**Comment by wolfy1339** [comment]
There wasn't any error message at runtime appart from `Segmentation Fault: core dumped`
I'm currently in the process of doing `gdb` debugging.

**Comment by wolfy1339** [comment]
I'm not sure why/how this happened but it stopped happening

**Comment by DarthGandalf** [comment]
Reopen when you have the details.
Also note that ZNC has continuous testing set up for both GCC and Clang.
