### ISSUE TITLE
oidentd doesnt work with znc, ...

### ISSUE THREAD

**Issue by gxf0** [znc/znc#1510]
Not sure where the problem comes from, here is my stetting:

/etc/oident.conf

```
user "znc" {
    default {
        allow spoof
        allow spoof_all
        allow spoof_privport
        allow random
        allow hide
    }
}
```

znc files incl. config stored in /etc/znc
.oidentd.conf is also stored in /etc/znc

I run znc as a service with -d /etc/znc, ... works without problem

After installed oidentd at least my bouncers got the ident: znc - like the user who runs znc, .. but not the defined ident

used this instruction: http://wiki.znc.in/Identfile 
but replaced the /msg *identfile setfile ~/.oidentd.conf with /msg *identfile setfile /etc/znc/.oidentd.conf

also set the rights, even tried to give it 777, ... doesnt work

dont know where the problem comes from

**Comment by DarthGandalf** [comment]
Is $HOME of "znc" user /etc/znc? oidentd reads .oident.conf in the user's
homedir. Is /etc/znc/ readable by oidentd? (more precisely, chmod +x)

2018-04-05 10:14 GMT+01:00 Veit <notifications@github.com>:

**Comment by gxf0** [comment]
Not sure, maybe I made some mistake at some point. Here is my way of setting it up:

1) downloaded and compiled with just a littel configuration: ./configure --prefix=/usr/

2) add new user:
```
adduser --disabled-password --no-create-home --gecos "" znc 
mkdir /etc/znc 
chown -R znc:znc /etc/znc
```

3) make config:
`su -c "znc -d /etc/znc --makeconf" znc`

4) add znc.service

```
[Unit]
Description=ZNC - IRC Bouncer
Requires=nss-user-lookup.target
After=network-online.target nss-user-lookup.target 

[Service]
User=znc
ExecStart=/usr/bin/znc -d /etc/znc --foreground 
ExecReload=/bin/kill -HUP 
Restart=on-failure
KillSignal=SIGINT
SuccessExitStatus=2

[Install]
WantedBy=multi-user.target
```

_________________________________________

ZNC runs like a charm, but i got ~ident@ ... so I installed oidentd, and changed the config, like the first post

than I loaded the ident modul and configured it

```
/msg *status loadmod identfile
/msg *identfile setfile /etc/znc/.oidentd.conf
/msg *identfile setformat global { reply "%user%" }
```

Than I restarted oidentd and znc.

but all I got is znc@.... as ident

I noticed, /etc/znc/moddata/identfile/.registry store some information, but not all

```
File %2f;etc%2f;znc%2f;%2e;oidentd%2e;conf
Format global%20;%7b;%20;reply%20;%22;%25;user%25;%22;%20;%7d;
```

Also /etc/znc/.oidentd.conf keeps empty, never mind if znc is running or not


___________________________________

Also tried to add the information directly in the znf config

```
ISpoofFile = /etc/znc/.oidentd.conf
ISpoofFormat =global { reply "%user%" }
```
... with the result that this just overwrite the /etc/znc/moddata/identfile/.registry

__________________________________

So it seems like the ident modul want to work, .. but doesnt do anything, it doesnt put any information in .oidentd.conf, ...

**Comment by gxf0** [comment]
```
root@r3v:~# echo ~znc
/home/znc
root@r3v:~# echo 'global { reply "test" }' > ~znc/.oidentd.conf
-bash: /home/znc/.oidentd.conf: Datei oder Verzeichnis nicht gefunden
```

Which means he doesn't find the dir, ... I guess i have to change the dir first.


I changed like this:

`usermod -m -d /etc/znc znc`

another try:

```
root@r3v:~# echo ~znc
/etc/znc
root@r3v:~# echo ~znc
/etc/znc
root@r3v:~# echo 'global { reply "test" }' > ~znc/.oidentd.conf
root@r3v:~# chmod a+r ~znc/.oidentd.conf
root@r3v:~# chmod a+x ~znc/
root@r3v:~# service znc start
```

The funny thing is, ... my ident doesnt become "test" but actually it becomes the ident I setup with znc:

` znc_ident@...`

So basically its working, I just dont know why. 

I guess:

1) I forget about the homedir, by changing it to /etc/znc, oidentd was checking for the .oidentd.conf
2) Seems like the file wasnt excetuable before that - I just changed the permission to 755 for the .oidentd.conf

Thanks a lot for your help guys!!!! You are awesome!

But one thing still confuses me, ... my .oidentd.conf still doesnt contain any information about the connected znc ident, .. it just contains global { reply "test" }. How this is possible?

**Comment by gxf0** [comment]
Noooo, not perfect at all, now all bnc use the ident from the main user, not from each ident i specified in the webinerfasce for every single user

**Comment by psychon** [comment]
> So basically its working, I just dont know why.

Well, because you fixed it with:

> usermod -m -d /etc/znc znc

oidentd still looks for the file in znc's home directory, but instead of getting a "no such file" error, this time it actually finds the information it needs.

> But one thing still confuses me, ... my .oidentd.conf still doesnt contain any information about the connected znc ident, .. it just contains global { reply "test" }. How this is possible?

ZNC only overwrites the file while it tries to connect to some IRC server. Afterwards it restores the old content.

**Comment by gxf0** [comment]
my fail, just beacuse I defined it like this, ... have to change it to: /msg *identfile setformat global { reply "%ident%" }

**Comment by gxf0** [comment]
Thanks a lot 👍 :3

**Comment by DarthGandalf** [comment]
The file doesn't need to be executable, the directory needs - otherwise
oidentd won't be able to read the file.

2018-04-05 11:37 GMT+01:00 Veit <notifications@github.com>:
