### ISSUE TITLE
Issues with timestamps on playback after mirc upgrade

### ISSUE THREAD

**Issue by leak** [znc/znc#1514]
ZNC 1.6.6
mIRC 7.52

After upgrading mIRC the auto log playback layout changed because the newer mIRC version supports server-time.

When I connect to ZNC and the log is replayed, I get all the messages as before, but the timestamps are all showing the same time, usually the same timestamp from the first line written and not the real timestamp when the message was actually written.

````
[11:47:05] - Topic: something
[11:47:05] - Set by user on 03/08/2017 - 05:23:44 (36w 3d 6h 23m ago)
[11:47:05] * Now talking in #channel
[11:47:05] <%user1> bla
[11:47:05] <%user2> bla
[11:47:05] <%user1> bla
[11:47:05] <%user1> bla
````
From what I understand `PrependTimestamp` and `TimestampFormat` become inactive once server-time is supported on the client.

What can I do to get the actual timestamps in log replay back?

**Comment by DarthGandalf** [comment]
Fix your client to use the `@time` tag. mIRC does that by default; do you have some script which ignores its value?
