### ISSUE TITLE
"Closing tag "Network" which is not open" when multiple chan tags in one line 

### ISSUE THREAD

**Issue by Yayg** [znc/znc#1520]
Using ZNC 1.6.6 on Fedora I recently came across this issue: When creating a config with:
``` 
<Network freenode>
      Server     = irc.freenode.net 6667
      <Chan gcc></Chan>
</Network>
```
I get `Error on line 55: Closing tag "Network" which is not open.`
But if I get each `Chan` tag on different lines it works.

**Comment by DarthGandalf** [comment]
Well, don't create config like that :) Why are you editing it manually anyway?

**Comment by psychon** [comment]
From a quick look at the code: `<Chan gcc></Chan>` is parsed as a tag with tag `Chan` and value `gcc></Chan`. Changing/fixing that would make the code more complicated with little gain. Perhaps it should be a (fatal?) error if a tag or value contains `>`?

**Comment by Yayg** [comment]
How should I modify the configuration? http://wiki.znc.in/Configuration point this znc.conf as the configuration to be modified.
I'm I trying to ansible it. So should I version another file?

The only thing I wanted to point out is that the error message is really not obvious. Fixing it would be great but at least having a clearer message would help.

**Comment by magnum7385** [comment]
Channel entries in the conf should appear as:
<Chan #help>
</Chan>
with the literal name of the channel (not just "gcc") and the closing tag on a separate line.

**Comment by DarthGandalf** [comment]
@Yayg http://wiki.znc.in/Configuration#Editing_config

> In most cases you should NOT edit znc.conf directly. Use webadmin instead.
