### ISSUE TITLE
Configuring incomplete, errors occurred

### ISSUE THREAD

**Issue by zer0c0nf** [znc/znc#1521]
Hello,

Ive issue with latest release (https://github.com/znc/znc/archive/znc-1.7.0.tar.gz)

On debian 9.4 : 

`../configure.sh
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   locale
CMake Error at CMakeLists.txt:245 (message):
   It looks like git submodules are not initialized.
   Run: git submodule update --init --recursive

-- Configuring incomplete, errors occurred!
See also "/tmp/znc-znc-1.7.0/CMakeFiles/CMakeOutput.log".
See also "/tmp/znc-znc-1.7.0/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "../configure.sh", line 136, in <module>
    + cm_args + extra_args)
  File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '..']' returned non-zero exit status 1
`
Can you resolve my problem? Thx

**Comment by magnum7385** [comment]
The command needed to fix the issue is included in the error message:
git submodule update --init --recursive

**Comment by zer0c0nf** [comment]
Hi magnum7385, but : 

in build or in znc-znc-1.7.0 
`fatal: Not a git repository (or any of the parent directories): .git`

**Comment by magnum7385** [comment]
Do you have any success using the official link release instead of the one you used? https://znc.in/releases/znc-1.7.0.tar.gz

**Comment by wolfy1339** [comment]
That's because you downloaded a tarball of the contents of the repo, and to use that git command, you need to have cloned the repo

**Comment by DarthGandalf** [comment]
Tarball with github repo doesn't include files from git submodules.

```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index a772f2db..7534d6d3 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -242,8 +242,20 @@ endif()
 file(GLOB csocket_files LIST_DIRECTORIES FALSE
 	"${PROJECT_SOURCE_DIR}/third_party/Csocket/Csocket.*")
 if(csocket_files STREQUAL "")
-	message(FATAL_ERROR " It looks like git submodules are not initialized.\n"
-		" Run: git submodule update --init --recursive")
+	execute_process(COMMAND git status
+		WORKING_DIRECTORY ${PROJECT_SOURCE_DIR}
+		RESULT_VARIABLE git_status_var
+		OUTPUT_QUIET
+		ERROR_QUIET)
+	if(git_status_var)
+		message(FATAL_ERROR
+			" It looks like git submodules are not initialized.\n"
+			" Either this is not a git clone, or you don't have git installed")
+	else()
+		message(FATAL_ERROR
+			" It looks like git submodules are not initialized.\n"
+			" Run: git submodule update --init --recursive")
+	endif()
 endif()
 
 install(DIRECTORY webskins
```

Would something like this make it more clear?

**Comment by zer0c0nf** [comment]
Yes DarthGandalf ;) Thx!
