### ISSUE TITLE
Crypt module: "+OK *" and "+OK" compatibility

### ISSUE THREAD

**Issue by greenxx** [znc/znc#1532]
Hi, I tested the blowfish / DH_1080 implementation of crypt and it looks like there's a compatibility problem (at least from what I can tell).

This is probaby a question for @Cizzle who did the implementation to justify if it's a bug / lack of standardization etc...

I'm not a developer, but from the code I've checked other implementations does not seem to have the `*` char before the crypted message which seem to make crypt DH_1080 uncompatible with the other implementations out there which I can find source for, below are a two examples: 
- Fish module linked from znc.in https://gist.github.com/v4lli/ee4edd99128e7cb518ebad548cab7a41
```
/msg *fish setkey testuser2 testing
<*fish> Set encryption key for [testuser2] to [testing]
<testuser2> *ANzZ9z9bt2ohbcrrsAdW1w==
```
```
/msg *crypt setkey testuser testing
<*crypt> Set encryption key for [testuser] to [testing]
<testuser> +OK l/Msh.OInW41
```
- `+OK`  used for all but topic change where `+OK *` is used: https://github.com/sysadm1ns/mceggdrop/blob/master/tcleggdrop_mcpsfuncs.tcl#L321-L328
- `+OK` used for PRIVMSG, NOTICE and TOPIC: https://github.com/flakes/mirc_fish_10/blob/73208781808b44f7accfd9c233579f89356c72d8/fish_10/src/fish-main.cpp#L78-L91

My interpretation is that crypt sees `+OK` as raw text since it doesn't match `+OK *`
Running ZNC v1.7.0 (https://hub.docker.com/_/znc/)

**Comment by milesbenson** [comment]
Just ran into the same issue, fish users can read my encrypted messages, but i cannot read those of them.

**Comment by DarthGandalf** [comment]
Looks like this can be closed.
