### ISSUE TITLE
ZNC doesn't handle subject alternative names of a let's encrypt certificate?

### ISSUE THREAD

**Issue by bin101** [znc/znc#1537]
ZNC Version: 1.8.x (self build from master branch)
OS: Debian 9.3

Hello I have the following problem:

If i want to connect to my znc server via hexchat I get the following error:

```
❨✽❩ Looking up chat.mydomain.example
❨✸❩ Connecting to dyndns.mydomain.example (xxx.xxx.xxx.xxx) port 6667...
* * Certification info:
*   Subject:
*     CN=chat.mydomain.example
*   Issuer:
*     C=US
*     O=Let's Encrypt
*     CN=Let's Encrypt Authority X3
*   Public key algorithm: rsaEncryption (4096 bits)
*   Sign algorithm sha256WithRSAEncryption
*   Valid since May 22 12:51:21 2018 GM to Aug 20 12:51:21 2018 GM
* * Cipher info:
*   Version: TLSv1/SSLv3, cipher ECDHE-RSA-AES128-GCM-SHA256 (128 bits)
❮✘❯ Connection failed. Error: unable to get local issuer certificate.? (20)
```
Also if I want to verify via openssl:

```
openssl s_client -connect chat.mydomain.example:6667
.
.
.
    Verify return code: 21 (unable to verify the first certificate)
    Extended master secret: yes
---
```

Port 443 is mapped to the same machine but will be answered by my nginx proxy with the same certificate znc uses:

```
openssl s_client -connect chat.mydomain.example:443
.
.
.
    Verify return code: 0 (ok)
    Extended master secret: yes
---
```

My setup has the following scenario:
I have a letsencrypt cert for my znc subdomain:
chat.mydomain.example which is a cname record on mydomain.example pointing to dyndns.mydomain.example. (I have to use this because I don't have a static IP at home and have to use dynamic DNS.)
dyndns.mydomain.example is mentioned inside my letsencrypt cert as alternative name.

I use the certificate inside the znc config like this (my znc user has read permission to the pem files):
```
SSLCertFile = /etc/letsencrypt/live/chat.mydomain.example/cert.pem
SSLDHParamFile = /etc/letsencrypt/live/chat.mydomain.example/chain.pem
SSLKeyFile = /etc/letsencrypt/live/chat.mydomain.example/privkey.pem
```

Does anyone know the source of my problem? Currently I have to tick the hexchat option to allow invalid certs which is kind of frustrating...

**Comment by bin101** [comment]
Addition:

Nginx response:
```
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = chat.mydomain.example
verify return:1
---
Certificate chain
 0 s:/CN=chat.mydomain.example
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
```

ZNC response:
```
CONNECTED(00000003)
depth=0 CN = chat.mydomain.example
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN = chat.mydomain.example
verify error:num=21:unable to verify the first certificate
verify return:1
---
Certificate chain
 0 s:/CN=chat.mydomain.example
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
```

There is definitely something missing

**Comment by teward** [comment]
it sounds like the entire certificate chain isn't being served.  Did you follow [the documentation on the wiki](https://wiki.znc.in/Signed_SSL_certificate#LetsEncrypt) for LetsEncrypt?  This includes getting it so that ZNC serves the full certificate chain.

**Comment by bin101** [comment]
I tried it now with the wiki/old way like you mentioned:
cat /etc/letsencrypt/live/example.org/{privkey,cert,chain}.pem > znc.pem

Works like a charm, so something bad is inside letting znc concat the cert, chain and private key...

**Comment by teward** [comment]
> letting ZNC concat the cert, chain, and private key

How're you making this determination?  Did you configure the various SSL options, or no?

**Comment by bin101** [comment]
All shame on me -.- I only had to use the fullchain.pem instead of only the cert... I misinterpreted SSLDHParamFile...

```
SSLCertFile = /etc/letsencrypt/live/chat.mydomain.example/fullchain.pem
SSLKeyFile = /etc/letsencrypt/live/chat.mydomain.example/privkey.pem
```

Issue is closed because of my own stupidy...

**Comment by melikyuksel** [comment]
@bin101 So what do you put for SSLDHParamFile with Let's Encrypt? Just leave it blank? The Wiki instructions for Let's Encrypt are outdated and only mention the pre-v.1.7 way to do it when the SSLDHParamFile parameter didn't exist.

**Comment by Mikaela** [comment]
@melikyuksel Generate DH params by running `openssl dhparam 2048 > dh.pem` (filename can be whatever you want) and point `SSLDHParamFile` to it. Please feel free to improve the wiki.
