### ISSUE TITLE
Please allow to disable "DEBUG mode" warning at connect.

### ISSUE THREAD

**Issue by Lupinus** [znc/znc#1541]
Recent znc versions will send you a private message from *status upon connecting to the bouncer if it's running in debug mode. I understand the reason for this message but please add an option to (optionally) disable this warning (config, command line, etc.). Every time I connect to the bouncer my client is telling me I have new private messages which is really annoying.

I'm the only user on my bouncer and I have root access anyway. If an admin had bad intentions on a multi user instance, they could simply remove the warning and compile znc themself. There are better options if you want to snoop on your users.

I'm running znc in debug mode on purpose since debugging connection issues without stdout is really annoying and I don't want to have to restart znc just to enable debugging and then restart it again to disable it.

Commit that introduced this feature: https://github.com/znc/znc/commit/ab501767a18eece2b3c553868d0c7cfbe496d658

**Comment by magnum7385** [comment]
Why are you running your instance in debug mode?

**Comment by psychon** [comment]
@magnum7385 

> I'm running znc in debug mode on purpose since debugging connection issues without stdout is really annoying and I don't want to have to restart znc just to enable debugging and then restart it again to disable it.

**Comment by magnum7385** [comment]
Thanks, @psychon

**Comment by DarthGandalf** [comment]
@Zarthus any objections to reverting that commit?

**Comment by DarthGandalf** [comment]
Ability to turn debugging on at runtime (#1370) doesn't make such
notification useful.

2018-05-29 11:24 GMT+01:00 Jos Ahrens <notifications@github.com>:

**Comment by Zarthus** [comment]
Yes it does, if it's enabled while you are connected.

The feature itself would probably also broadcast to all connected client that "debug mode is now being turned on" and "debug mode is now being turned off".

**Comment by Zarthus** [comment]
With https://github.com/znc/znc/pull/1556 this should now be mitigated, run znc like `znc --foreground > out.log` or using systemd and then toggle the debug mode when you want to debug connections.
