### ISSUE TITLE
python: CMessage.GetParams() returns unknowns

### ISSUE THREAD

**Issue by A-UNDERSCORE-D** [znc/znc#1543]
When using python based plugins that hook on the new-er *Message hoons (eg OnUserRawMessage), the `GetParams()` method on the CMessage given to the callback returns a tuple containing `Swig Object of type 'unknown'`.

ZNC version tested on: ZNC 1.7.0 (IPv6: yes, SSL: yes, DNS: threads, charset: yes, i18n: no, build: autoconf)
ZNC was built from source on my Ubuntu 18.04 desktop using python 3.6.5

**Comment by DarthGandalf** [comment]
Fixed in 11fb42887871a6196dcdf7f7c5556f1e673aceb6
