### ISSUE TITLE
"blahblah: description"

### ISSUE THREAD

**Issue by psychon** [znc/znc#1548]
```
$ git grep blahblah: | grep -v '.po:'
modules/flooddetach.cpp:        AddCommand("Lines", t_d("[<limit>]"), t_d("blahblah: description"),
modules/flooddetach.cpp:        AddCommand("Silent", t_d("[yes|no]"), t_d("blahblah: description"),
modules/po/flooddetach.pot:msgid "blahblah: description"
```
I think this is not the most helpful description of these commands and should be improved.

**Comment by DarthGandalf** [comment]
Argh.
When I was converting old overload of `AddCommand` to new one (using clang tool), I added this dummy description to commands which didn't have any description, then I replaced *most* of them with a more useful description.
Well... at least this is not a regression.
