### ISSUE TITLE
(soft)symlinked ~.znc cant save config

### ISSUE THREAD

**Issue by fred0r** [znc/znc#1575]
with 1.8.x-git-109-4d82211 it doesnt seem possible to save the config when ~.znc is a symlink.
starting the znc works though

**Comment by magnum7385** [comment]
Did you try symlinking ~.znc or ~/.znc?

**Comment by fred0r** [comment]
i cant tell you how i created it, since i've been using this setup for a long time and both ways creating testlinks look exactly the same in my fs.
the behavior seems to have changed 'lately', since it worked with ~2 month older znc-git.

**Comment by magnum7385** [comment]
ZNC versioning doesn't matter if the symlink itself is invalid.  ~.znc is not the same as ~/.znc, so you need to determine if the symlink is valid or not, first

**Comment by fred0r** [comment]
Sorry for wasting your time.
the symlinked partition was full :/
