### ISSUE TITLE
Add support for IRCv3.2 CHGHOST

### ISSUE THREAD

**Issue by trobotham** [znc/znc#1577]
- https://ircv3.net/specs/extensions/chghost-3.2.html

This would be very beneficial to have in ZNC.

**Comment by stefansaraev** [comment]
http://sprunge.us/Flfl3Q

I think this is enough.

**Comment by DarthGandalf** [comment]
@stefansaraev It's not. `CNick::GetHost` will return wrong value, modules need a callback to be able to do something about this new message. Need a test.

**Comment by DarthGandalf** [comment]
Fixed in #1919 

> modules need a callback

OnRawMessage should work. A dedicated callback probably not necessary
