### ISSUE TITLE
[Support] A client from [172.16.0.1] attempted to login as you, but was rejected 

### ISSUE THREAD

**Issue by kopax** [znc/znc#1579]
I have my `*status` in hexchat telling me this:

    A client from [172.16.0.1] attempted to login as you, but was rejected [Invalid Password].

What does that mean exactly? Who's `you` ? Is it my own znc account?

What kind of incoming connection is it?

**Comment by psychon** [comment]
There was an incoming TCP connection. It tried to log in to znc as your user (that's the `you`), but it failed due to an invalid password.

> What kind of incoming connection is it?

I would guess an IRC connection, but it might also be possible that this is a HTTP connection.

**Comment by teward** [comment]
Given that the IP address is the 'router' of the network (172.16.0.1 is typically a gateway address) my guess is you've got something doing NAT to the thing and not preserving the original IP address (if this is your own network behind a router for instance).  This could return something like this for either an IRC or HTTP (webadmin) connection.

**Comment by kopax** [comment]
>  tried to log in to znc as your user (that's the you), but it failed due to an invalid password.

@psychon I have not myself used a wrong account and I found strange that someone tried to login with my user. It means someone one irc is attacking my nick =/?

> I would guess an IRC connection, but it might also be possible that this is a HTTP connection.

Can you show me how to reproduce this? I would found it a more common attack if it comes from http.

**Comment by DarthGandalf** [comment]
2018-07-16 18:01 GMT+01:00 Dimitri KOPRIWA <notifications@github.com>:

> tried to log in to znc as your user (that's the you), but it failed due to
> an invalid password.
>
> @psychon <https://github.com/psychon> I have not myself used a wrong
> account and I found strange that someone tried to login with my user. It
> means someone one irc is attacking my nick =/?
>
> I would guess an IRC connection, but it might also be possible that this
> is a HTTP connection.
>
> Can you show me how to reproduce this? I would found it a more common
> attack if it comes from http.
>
>
Try to connect with your IRC client (while still connected normally) or
browser, but type a wrong password. You'll see the same message.

**Comment by kopax** [comment]
How do you connect from a browser ?

**Comment by dgw** [comment]
If webadmin is enabled, `http://your.znc.server.ip/` (if that doesn't work, try `https` instead).

**Comment by DarthGandalf** [comment]
http://host:port/ or https://host:port/

2018-07-17 14:22 GMT+01:00 Dimitri KOPRIWA <notifications@github.com>:

**Comment by kopax** [comment]
That is strange, thanks for trying to help.
