### ISSUE TITLE
Unable to open module modpython

### ISSUE THREAD

**Issue by ParityError** [znc/znc#1596]
I have compiled the latest ZNC (1.7.1 as of now) from the source tarball with the following configure options:
```
PKG_CONFIG_PATH=/usr/local/lib/pkgconfig python_LIBS="-L/usr/local/lib/ -lpython3.6m -lutil" ../configure --enable-python
```
Which results in:
```
ZNC 1.7.1 configured

prefix:       /usr/local
debug:        no
ipv6:         yes
openssl:      yes
dns:          threads
perl:         no
python:       yes
swig:         not needed
cyrus:        no
tcl:          no
charset:      yes
zlib:         yes
run from src: no

Now you can run "make" to compile ZNC
```
When I go to load any of my python modules in IRC (which don't even show up in the web control panel or when doing `/znc listmods`) located in `/home/znc/.znc/modules/` I get an error:
```
/znc loadmod modpython
Unable to load modpython: Unable to open module modpython: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory

/znc loadmod mymodule
Unable to load mymodule: Unable to find module mymodule.
```
I have no idea where it's looking for the modules, or shared library or why it can't find it, although I've exhausted most of obvious things I know of and would appreciate if someone could help me resolve this issue. If you need any additional information about the install, etc. please just let me know - thanks.

**Comment by DarthGandalf** [comment]
Show your `/etc/ld.so.conf` and `/etc/ld.so.conf.d/*`

**Comment by DarthGandalf** [comment]
You'll need to add `/usr/local/lib` there.

**Comment by ParityError** [comment]
@DarthGandalf, **Thank you very much!** _That did the trick._

One more question (off-topic from this issue), I compiled ZNC with ICU, although when I look in the web control panel I get:
```
Client encoding: ZNC is compiled without encodings support. ICU is required for it.  
(  ) Don't ensure any encoding at all (legacy mode, not recommended) 
(  ) Try to parse as UTF-8 and as, send as UTF-8 (recommended) 
(  ) Try to parse as UTF-8 and as, send as  Parse and send as only  E.g. UTF-8, or ISO-8859-15
```
I'm not sure if I failed to include something during compilation perhaps, or maybe this is normal? I'm just not sure which option to select or if I should recompile with some other option. Thanks again :)

**Comment by DarthGandalf** [comment]
That look like you have 2 different ZNCs installed. And you are using not the one you compiled.
Check `/msg *status version`.
