### ISSUE TITLE
Webadmin Edit User > Networks shows old Nick

### ISSUE THREAD

**Issue by TonyGravagno** [znc/znc#1605]
From edituser, Add a Network entry. When done, view from edituser. The Nick is correct. Now still in edituser Networks, Edit that network and change the Nick. Save and Continue. In edituser the Nick still shows the previous name. Restart the service to see the correct name.

**Comment by DarthGandalf** [comment]
That table refers to the current nick how ZNC is connected to IRC server. Reconnecting via `/znc jump` or sending some other nick via `/nick foo` would change that.
