### ISSUE TITLE
cookies not saved if ssl enabled

### ISSUE THREAD

**Issue by moham96** [znc/znc#1606]
Hi, 
If I enable ssl in znc then the cookies are not saved in firefox and everytime I refresh the page I get 
`You must login to view that page``
If I disable ssl howver the cookies are saved with no problem
Regards

**UPDATE:  now I get the cookies not saved problem even on ssl disabled with a different message :**

> Your browser does not have cookies enabled for this site!

**Comment by DarthGandalf** [comment]
Did you disable cookies in firefox?

**Comment by ScottG489** [comment]
Hey I'm getting this issue as well and this is about the only thing that comes up when I search for this problem.

I do have SSL enabled for the web interface. When I try to log in it's successful and it brings me to the home page, but if I try to navigate anywhere, or just refresh the page, it kicks me back to the login page with the message "You must login to view that page".

Happy to create a new issue for this if desired.

**Comment by DuncanBennie** [comment]
> Hey I'm getting this issue as well and this is about the only thing that comes up when I search for this problem.
> 
> I do have SSL enabled for the web interface. When I try to log in it's successful and it brings me to the home page, but if I try to navigate anywhere, or just refresh the page, it kicks me back to the login page with the message "You must login to view that page".
> 
> Happy to create a new issue for this if desired.

For what it’s worth, I’m having the same issue.
