### ISSUE TITLE
my znc was working fin on centos7 but after reboot doest work

### ISSUE THREAD

**Issue by xapim** [znc/znc#1609]
i tried reinstall it over and over again and it wont work any help to get it back online would be apreciated
this is what i'm getting

[root@ns388373 ~]# systemctl enable znc.service
Created symlink from /etc/systemd/system/multi-user.target.wants/znc.service to /usr/lib/systemd/system/znc.service.
[root@ns388373 ~]# systemctl start znc.service
[root@ns388373 ~]# service znc status -l
Redirecting to /bin/systemctl status  -l znc.service
● znc.service - ZNC, an advanced IRC bouncer
   Loaded: loaded (/usr/lib/systemd/system/znc.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2018-10-14 17:10:29 CEST; 3s ago
  Process: 30061 ExecStart=/usr/bin/znc -f (code=exited, status=1/FAILURE)
 Main PID: 30061 (code=exited, status=1/FAILURE)

Oct 14 17:10:29 ns388373.ip-176-31-101.eu systemd[1]: Started ZNC, an advanced IRC bouncer.
Oct 14 17:10:29 ns388373.ip-176-31-101.eu systemd[1]: Starting ZNC, an advanced IRC bouncer...
Oct 14 17:10:29 ns388373.ip-176-31-101.eu systemd[1]: znc.service: main process exited, code=exited, status=1/FAILURE
Oct 14 17:10:29 ns388373.ip-176-31-101.eu systemd[1]: Unit znc.service entered failed state.
Oct 14 17:10:29 ns388373.ip-176-31-101.eu systemd[1]: znc.service failed.

**Comment by psychon** [comment]
Well... can you somehow get some actual output from ZNC? What happens when you run `znc -f` as root yourself? (Assuming your systemd unit runs ZNC as root)

**Comment by xapim** [comment]
I am running it as root

**Comment by xapim** [comment]
[root@ns388373 ~]# znc
[ .. ] Checking for list of available modules...
[ ** ] You are running ZNC as root! Don't do that! There are not many valid
[ ** ] reasons for this and it can, in theory, cause great damage!
[root@ns388373 ~]# znc -f
[ .. ] Checking for list of available modules...
[ ** ] You are running ZNC as root! Don't do that! There are not many valid
[ ** ] reasons for this and it can, in theory, cause great damage!

**Comment by sebito91** [comment]
If you recently updated znc you may need to rebuild your clientbuffer module. This tripped me up when updating from Fedora 27 to 28.

https://wiki.znc.in/Clientbuffer

Would perform an ldd on your znc binary and make sure also that all necessary lib dependencies resolve.

**Comment by psychon** [comment]
Hm. https://github.com/znc/znc/commit/1a7895cbd4f733e2c0eedfa371047e4df7fab1e9 is quite old (10 years). I do not really know why znc would previously not have complained about running as root?!?
You could just start znc with `--allow-root` to make znc start, but I have no idea why this used to work for you.

**Comment by DarthGandalf** [comment]
@sebito91 all installed third-party modules need to be rebuilt. @xapim didn't indicate that he has installed any.

@xapim maybe it was running not as root? Check what user `znc.service` runs it in. Run it as the same user. Also journalctl might have logs which you can look at.

**Comment by xapim** [comment]
its weird has been runing fine until i rebooted the server for whm updates then stopped working and counldnt start again

**Comment by xapim** [comment]
[root@ns388373 ~]# znc --allow-root
[ .. ] Checking for list of available modules...
[ ** ] You are running ZNC as root! Don't do that! There are not many valid
[ ** ] reasons for this and it can, in theory, cause great damage!
[ ** ] You have been warned.
[ ** ] Hit CTRL+C now if you don't want to run ZNC as root.
[ ** ] ZNC will start in 30 seconds.
[ .. ] Opening config [/root/.znc/configs/znc.conf]...
[ !! ] No such file
[ ** ] Restart ZNC with the --makeconf option if you wish to create this config.
[ ** ] Unrecoverable config error.

**Comment by xapim** [comment]
the conf is there:

// WARNING
//
// Do NOT edit this file while ZNC is running!
// Use webadmin or *controlpanel instead.
//
// Altering this file by hand will forfeit all support.
//
// But if you feel risky, you might want to read help on /znc saveconfig and /znc rehash.
// Also check https://wiki.znc.in/Configuration

AnonIPLimit = 10
AuthOnlyViaModule = false
ConfigWriteDelay = 0
ConnectDelay = 5
HideVersion = false
LoadModule = webadmin
LoadModule = admindebug
LoadModule = adminlog
LoadModule = chansaver
LoadModule = lastseen
LoadModule = log
LoadModule = notify_connect
LoadModule = partyline
MaxBufferSize = 500
ProtectWebSessions = true
SSLCertFile = /var/lib/znc/.znc/znc.pem
SSLDHParamFile = /var/lib/znc/.znc/znc.pem
SSLKeyFile = /var/lib/znc/.znc/znc.pem
ServerThrottle = 30
Skin = forest
StatusPrefix = *
Version = 1.7.1

<Listener listener0>
	AllowIRC = true
	AllowWeb = true
	IPv4 = true
	IPv6 = true
	Port = 59001
	SSL = true
	URIPrefix = /
</Listener>

<User Just_Pain>
	Admin = false
	Allow = *
	AltNick = Just_Pain
	AppendTimestamp = false
	AuthOnlyViaModule = false
	AutoClearChanBuffer = true
	AutoClearQueryBuffer = true
	ChanBufferSize = 50
	ClientEncoding = ^UTF-8
	DenyLoadMod = false
	DenySetBindHost = false
	Ident = Just_Pain
	JoinTries = 10
	LoadModule = alias
	LoadModule = autoattach
	LoadModule = autoreply
	LoadModule = chansaver
	LoadModule = clientnotify
	LoadModule = controlpanel
	LoadModule = perform
	LoadModule = raw
	LoadModule = stripcontrols
	LoadModule = webadmin
	MaxJoins = 0
	MaxNetworks = 1
	MaxQueryBuffers = 50
	MultiClients = true
	Nick = Just_Pain
	NoTrafficTimeout = 180
	PrependTimestamp = true
	QueryBufferSize = 50
	QuitMsg = %znc%
	RealName = ZNC - https://znc.in
	TimestampFormat = [%H:%M:%S]

	<Pass password>
		Hash = dad2f8914979460a9edae12da9688b15fe772a9c0810b84b9f8544341c46a3fa
		Method = SHA256
		Salt = y_YGKK!3A!G.sg-oM275
	</Pass>
</User>

<User xapim>
	Admin = true
	Allow = *
	AltNick = xapim_
	AppendTimestamp = true
	AuthOnlyViaModule = false
	AutoClearChanBuffer = true
	AutoClearQueryBuffer = true
	ChanBufferSize = 50
	DenyLoadMod = false
	DenySetBindHost = false
	Ident = xapim
	JoinTries = 10
	LoadModule = chansaver
	LoadModule = controlpanel
	LoadModule = alias
	LoadModule = autoattach
	LoadModule = autoreply
	LoadModule = clientnotify
	LoadModule = ctcpflood 4 2
	LoadModule = dcc
	LoadModule = flooddetach 5 2
	LoadModule = listsockets
	LoadModule = log
	LoadModule = notes
	LoadModule = perform
	LoadModule = raw
	LoadModule = shell
	LoadModule = stripcontrols
	LoadModule = webadmin
	MaxJoins = 0
	MaxNetworks = 1
	MaxQueryBuffers = 50
	MultiClients = true
	Nick = xapim
	NoTrafficTimeout = 180
	PrependTimestamp = true
	QueryBufferSize = 50
	QuitMsg = %znc%
	RealName = ZNC - https://znc.in
	TimestampFormat = [%H:%M:%S]

	<Network Ptnet>
		FloodBurst = 9
		FloodRate = 2.00
		IRCConnectEnabled = true
		JoinDelay = 0
		LoadModule = simple_away
		LoadModule = perform
		Server = uevora.ptnet.org +6697
		TrustAllCerts = false
		TrustPKI = true

		<Chan #10-80>
		</Chan>

		<Chan #30-50>
		</Chan>

		<Chan #Portugal>
		</Chan>

		<Chan #Radio>
		</Chan>

		<Chan #eggdrop>
		</Chan>

		<Chan #mircodependentes>
		</Chan>
	</Network>

	<Pass password>
		Hash = f2898fb7360f8292f9b87bde52ae05161a0ab47d1ff8878f0d440c17d08dc04d
		Method = SHA256
		Salt = O;j8khdn;FzHlDmHBT7M
	</Pass>
</User>

**Comment by xapim** [comment]
like i said its really weird as it was working fine even starting with root account wouldnt warn anything i already yum remove znc deleted the var/lib/znc and yum install znc so many times created new confs from scratch with ssl without ssl without adding server and nothing works can't get it to work :(

**Comment by xapim** [comment]
the conf above was the previous working conf which isn't working now

**Comment by DarthGandalf** [comment]
Without error message why exactly ZNC wasn't starting after reboot, we can't do anything

**Comment by xapim** [comment]
i managed to get it working again by compiling it all from scratch manually but after a few server reboots (due to cpanel upgrades) it won't start anymore the error now its cannot locate the pem file

] Unable to locate pem file: /var/lib/znc/.znc/znc.pem
[ ?? ] Would you like to create a new pem file? (yes/no) [yes]: yes
[ .. ] Writing Pem file [/var/lib/znc/.znc/znc.pem]...
[ !! ] Unable to open

file is there i checked myself and even tried to delete and make conf again no luck

**Comment by xapim** [comment]
sh-4.2$ znc -f
[ .. ] Checking for list of available modules...
[ .. ] Opening config [/home/xapim/.znc/configs/znc.conf]...
[ .. ] Loading global module [webadmin]...
[ .. ] Loading global module [admindebug]...
[ .. ] Loading global module [adminlog]...
[ .. ] Loading global module [chansaver]...
[ .. ] Loading global module [lastseen]...
[ .. ] Loading global module [log]...
[ .. ] Loading global module [notify_connect]...
[ .. ] Loading global module [partyline]...
[ .. ] Binding to port [+59001]...
[ !! ] Unable to locate pem file: /var/lib/znc/.znc/znc.pem
[ ?? ] Would you like to create a new pem file? (yes/no) [yes]: yes
[ .. ] Writing Pem file [/var/lib/znc/.znc/znc.pem]...
[ !! ] Unable to open
[ .. ] Binding to port [+59001]...
[ ** ] Loading user [Just_Pain]
[ .. ] Loading user module [alias]...
[ .. ] Loading user module [autoattach]...
[ .. ] Loading user module [autoreply]...
[ .. ] Loading user module [chansaver]...
[ .. ] Loading user module [clientnotify]...
[ .. ] Loading user module [controlpanel]...
[ .. ] Loading user module [perform]...
[ .. ] Loading user module [raw]...
[ .. ] Loading user module [stripcontrols]...
[ .. ] Loading user module [webadmin]...
[ ** ] Loading user [xapim]
[ ** ] Loading network [Ptnet]
[ .. ] Loading network module [simple_away]...
[ >> ] [/usr/local/lib/znc/simple_away.so]
[ .. ] Loading network module [perform]...
[ >> ] [/usr/local/lib/znc/perform.so]
[ .. ] Adding server [uevora.ptnet.org +6697]...
[ .. ] Loading user module [chansaver]...
[ .. ] Loading user module [controlpanel]...
[ .. ] Loading user module [alias]...
[ .. ] Loading user module [autoattach]...
[ .. ] Loading user module [autoreply]...
[ .. ] Loading user module [clientnotify]...
[ .. ] Loading user module [ctcpflood]...
[ .. ] Loading user module [dcc]...
[ .. ] Loading user module [flooddetach]...
[ .. ] Loading user module [listsockets]...
[ .. ] Loading user module [log]...
[ .. ] Loading user module [notes]...
[ .. ] Loading user module [perform]...
[ .. ] Loading user module [raw]...
[ .. ] Loading user module [shell]...
[ .. ] Loading user module [stripcontrols]...
[ .. ] Loading user module [webadmin]...
[ ** ] Staying open for debugging [pid: 32564]
[ ** ] ZNC 1.7.1 - https://znc.in

**Comment by DarthGandalf** [comment]
Did you move the config from /var/lib/znc to /home/xapim? If so, update the
path to the certificate inside the znc.conf

вт, 20 нояб. 2018 г. в 10:45, xapim <notifications@github.com>:
