### ISSUE TITLE
Building from source fails - git submodules not initialized

### ISSUE THREAD

**Issue by sagamusix** [znc/znc#1646]
I am trying to upgrade from 1.7.1 to 1.7.3.
First off, I am using autoconf (I know it is deprecated but until I upgrade that server, it will have to do). `./configure` no longer seems to work out of the box so I ran `./autogen.sh` (this doesn't seem to be mentioned in the changelog?).

Running `./configure` works as expected, but running `make` afterwards fails:
```
Packing man page znc.1.gz...
Packing man page znc-buildmod.1.gz...
It looks like git submodules are not initialized. Run: git submodule update --init --recursive
Makefile:196: recipe for target 'third_party/Csocket/Csocket.h' failed
```
As I am building from the official source tarball, this doesn't seem to make a lot of sense, and the installation instructions do not appear to have been updated for any new steps that would be necessary.

**Comment by DarthGandalf** [comment]
> the official source tarball

Where you got it? If from github, those are known to be broken.

**Comment by magnum7385** [comment]
Do not use the tarball that github provides.  It's broken.
Fetch either, [https://znc.in/releases/znc-1.7.3.tar.gz](url) or [https://znc.in/nightly/znc-latest.tar.gz](url) or `$ git clone https://github.com/znc/znc.git --recursive`

**Comment by sagamusix** [comment]
Nevermind. I first got it from GitHub, noticed that it failed, then grabbed the official tarball, and apparently I didn't notice that I kept using the GitHub tarball rather than the official one. Cleaned everything, re-downloaded the official tarball and now it works as expected.
