### ISSUE TITLE
latest-git compiling against libressl 2.8.3

### ISSUE THREAD

**Issue by fred0r** [znc/znc#1648]
i'm trying to compile latest git against libressl 2.8.3.
libressl is installed in my $home and znc:
`./configure CXXFLAGS=-I$HOME/include/openssl LDFLAGS=-L$HOME/lib --prefix=$HOME --disable-ipv6`

but its unable to compile:

> /usr/bin/ld: src/Csocket.o: in function `Csock::ConfigureCTXOptions(ssl_ctx_st*)':
> Csocket.cpp:(.text+0x281c): undefined reference to `SSL_CTX_set_options'
> /usr/bin/ld: src/Csocket.o: in function `Csock::SetupServerCTX()':
> Csocket.cpp:(.text+0x80a8): undefined reference to `SSL_CTX_set_options'
> /usr/bin/ld: src/SSLVerifyHost.o: in function `ZNC_SSLVerifyHost(CString const&, x509_st const*, CString&)':
> SSLVerifyHost.cpp:(.text+0x85e): undefined reference to `OPENSSL_sk_num'
> /usr/bin/ld: SSLVerifyHost.cpp:(.text+0x8ef): undefined reference to `OPENSSL_sk_value'
> /usr/bin/ld: SSLVerifyHost.cpp:(.text+0xb0f): undefined reference to `OPENSSL_sk_pop_free'
> /usr/bin/ld: SSLVerifyHost.cpp:(.text+0xbbb): undefined reference to `OPENSSL_sk_pop_free'
> /usr/bin/ld: SSLVerifyHost.cpp:(.text+0x1440): undefined reference to `OPENSSL_sk_pop_free'
> /usr/bin/ld: SSLVerifyHost.cpp:(.text+0x1803): undefined reference to `OPENSSL_sk_pop_free'
> collect2: error: ld returned 1 exit status
> make: *** [Makefile:97: znc] Fehler 1
>

**Comment by fred0r** [comment]
this seems to be a csocket-bug, right ?

**Comment by DarthGandalf** [comment]
What is the last working libressl version?

**Comment by fred0r** [comment]
after building current git against older libressl-versions than 1.8.x, on libressl 1.6.5 (1.7.x same as 1st post) the initial error message changed to:

```
/usr/bin/ld: src/Csocket.o: in function `InitSSL(ECompType)':
Csocket.cpp:(.text+0x23a3): undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: Csocket.cpp:(.text+0x23ac): undefined reference to `OPENSSL_init_ssl'
/usr/bin/ld: src/Csocket.o: in function `Csock::ConfigureCTXOptions(ssl_ctx_st*)':
Csocket.cpp:(.text+0x281c): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: src/Csocket.o: in function `Csock::SetupServerCTX()':
Csocket.cpp:(.text+0x80a8): undefined reference to `SSL_CTX_set_options'
/usr/bin/ld: src/Csocket.o: in function `Csock::GetPeerPubKey() const':
Csocket.cpp:(.text+0x8c1f): undefined reference to `EVP_PKEY_get0_DSA'
/usr/bin/ld: Csocket.cpp:(.text+0x8c2e): undefined reference to `DSA_get0_key'
/usr/bin/ld: Csocket.cpp:(.text+0x8dbc): undefined reference to `EVP_PKEY_get0_RSA'
/usr/bin/ld: Csocket.cpp:(.text+0x8dcd): undefined reference to `RSA_get0_key'
/usr/bin/ld: src/Utils.o: in function `CUtils::GenerateCert(_IO_FILE*, CString const&)':
Utils.cpp:(.text+0x1238): undefined reference to `X509_getm_notBefore'
/usr/bin/ld: Utils.cpp:(.text+0x124a): undefined reference to `X509_getm_notAfter'
/usr/bin/ld: src/SSLVerifyHost.o: in function `ZNC_SSLVerifyHost(CString const&, x509_st const*, CString&)':
SSLVerifyHost.cpp:(.text+0x85e): undefined reference to `OPENSSL_sk_num'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0x8ef): undefined reference to `OPENSSL_sk_value'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0x903): undefined reference to `ASN1_STRING_get0_data'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0xb0f): undefined reference to `OPENSSL_sk_pop_free'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0xb42): undefined reference to `ASN1_STRING_get0_data'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0xbbb): undefined reference to `OPENSSL_sk_pop_free'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0xfcd): undefined reference to `ASN1_STRING_get0_data'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0xff9): undefined reference to `ASN1_STRING_get0_data'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0x1097): undefined reference to `ASN1_STRING_get0_data'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0x1440): undefined reference to `OPENSSL_sk_pop_free'
/usr/bin/ld: SSLVerifyHost.cpp:(.text+0x1803): undefined reference to `OPENSSL_sk_pop_free'
collect2: error: ld returned 1 exit status
make: *** [Makefile:97: znc] Fehler 1

```
i dont know how to compare that to znc-git regardiing the old libressl-release dates.

**Comment by DarthGandalf** [comment]
libressl 1.6.5? https://www.libressl.org/releases.html says 2.0.0 was the first release. Are you confusing it with ZNC version?

**Comment by fred0r** [comment]
OOOH !
my libressl versions were **2**.x.x

**Comment by fred0r** [comment]
with `./configure CXXFLAGS=-I$HOME/include LDFLAGS=-L$HOME/lib --prefix=$HOME` it compiled fine against `LibreSSL 3.0.2`
