### ISSUE TITLE
Compile from tarballs

### ISSUE THREAD

**Issue by zc0nf** [znc/znc#1671]
Hello

When I try to compile from tarball sources, it is not currently possible to do so.

Indeed, the dependency for the third_party is only present when I make a git clone, an issue had been opened #1521 , is it possible for each release and thus zip and tar.gz archive to add third_party missing to compile sources without problems?

The readme does not mention anywhere that it is not possible to compile from tarballs.

thank you,

zc0nf

**Comment by psychon** [comment]
Uhm, the files in `third_party` are there for me in the release tarballs:
```
$ wget https://znc.in/releases/znc-1.7.4.tar.gz
$ tar -xvzf znc-1.7.4.tar.gz | grep third_party
znc-1.7.4/third_party/
znc-1.7.4/third_party/googletest/
znc-1.7.4/third_party/Csocket/
znc-1.7.4/third_party/Csocket/Csocket.cc
znc-1.7.4/third_party/Csocket/Csocket.h
```
Are you using https://github.com/znc/znc/archive/znc-1.7.4.tar.gz to download znc? If so, that file is automatically generated by GitHub and we cannot influence its content (well, it contains exactly the same files as are in git). That's exactly the same issue as #1521.

**Comment by zc0nf** [comment]
Hi psychon,

Are you using https://github.com/znc/znc/archive/znc-1.7.4.tar.gz to download znc?
Yes

It is therefore necessary in this case, to update the readme evoking the impossibility to compile from the files made available in the Release section.

Unless someone can find a solution to fix or work around the problem?

For example, if I want to upgrade my znc to the latest stable version, which is the easiest and fastest method?

If I have to go through a git clone, I will have to position myself on the commit that speaks of the release in 1.7.4 which is forbidding and somehow imposes to be always on a development version?

thank you,

zc0nf

**Comment by psychon** [comment]
> Are you using https://github.com/znc/znc/archive/znc-1.7.4.tar.gz to download znc?
> Yes

Then use https://znc.in/releases/znc-1.7.4.tar.gz

**Comment by zc0nf** [comment]
Perfect,

Its possible to update readme ? :-)

zc0nf
