### ISSUE TITLE
please prepare znc for python3.8

### ISSUE THREAD

**Issue by rosset** [znc/znc#1675]
checking for python3 >= 3.0... yes
configure: error: python not found. Try --disable-python.
checking for Py_Initialize... no

python3-3.8.0~b2

https://docs.python.org/3.8/whatsnew/3.8.html#debug-build-uses-the-same-abi-as-release-build

Fedora Bug Report: https://bugzilla.redhat.com/show_bug.cgi?id=1718369

**Comment by DarthGandalf** [comment]
Does it work with CMake build? It uses a different method of finding python. For a quick test, you can replace `configure` with `configure.sh` in the existing command.

I can't test this (or test the fix) myself because python 3.8 isn't available yet.
