### ISSUE TITLE
set_target_properties called with incorrect number of arguments.

### ISSUE THREAD

**Issue by janicez** [znc/znc#1686]
```
CMake Error at modules/CMakeLists.txt:45 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
```

**Comment by DarthGandalf** [comment]
Could you show the full log? Also CMake version, ZNC version, `cmake --system-information`

**Comment by DarthGandalf** [comment]
`cmake --debug-output --trace <the rest of options>` may show more details.

**Comment by janicez** [comment]
I ultimately got ZNC to compile, seemingly correctly, by commenting line 45 of `modules/CMakeLists.txt`.

**Comment by janicez** [comment]
```
-- Checking for module 'libsasl2'
--   Package 'libsasl2', required by 'virtual:world', not found
CMake Error at modules/CMakeLists.txt:45 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  modules/CMakeLists.txt:111 (add_cxx_module)


+------------------------+
| ZNC 1.8.x configured   |
|                        |
| Prefix    : /opt/local |
| SSL       : yes        |
| IPv6      : yes        |
| Async DNS : yes        |
| Perl      : yes        |
| Python    : yes        |
| Tcl       : yes        |
| Cyrus     : no         |
| Charset   : yes        |
| Zlib      : yes        |
| i18n      : yes        |
+------------------------+

Now you can run 'make' to compile ZNC

-- Configuring incomplete, errors occurred!
See also "/home/ellenor/src/znc/build/CMakeFiles/CMakeOutput.log".
See also "/home/ellenor/src/znc/build/CMakeFiles/CMakeError.log".
```

You were right about debug-output and trace being more details, by the way...

```
$ wc -l ~/public_html/ascomycetes.txt  ;# copied from the illumos machine I was having the issue on
   50554 /home/ellenor/public_html/ascomycetes.txt
```

https://umbrellix.net/~ellenor/ascomycetes.txt

**Comment by DarthGandalf** [comment]
I can't reproduce it locally. I tried to start https://omniosce.org/setup/aws but it doesn't let me login. Do you have any suggestion where I can get a working illumos machine?

**Comment by janicez** [comment]
I run one, actually. Would you like to contact me privately (I'm banned from freenode so I cannot talk to you on the IRC) for a shell account?

For what it's worth, I do have ZNC working on said machine, so this bug may be invalid.

On 4 January, 2020 7:53:59 AM PST, Alexey Sokolov <notifications@github.com> wrote:
>I can't reproduce it locally. I tried to start
>https://omniosce.org/setup/aws but it doesn't let me login. Do you have
>any suggestion where I can get a working illumos machine?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/znc/znc/issues/1686#issuecomment-570796232

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by DarthGandalf** [comment]
I can't reproduce it on your machine either, it works with both 1.7.5 and nightly 2020-01-06. Do you have some custom patches/modules?

**Comment by janicez** [comment]
Were you trying cmake or the Autoconf configure?

I know that that's a cmake error. I also know I was able to hammer around it.

On 6 January, 2020 4:49:11 PM PST, Alexey Sokolov <notifications@github.com> wrote:
>I can't reproduce it on your machine either, it works with both 1.7.5
>and nightly 2020-01-06. Do you have some custom patches/modules?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/znc/znc/issues/1686#issuecomment-571381449

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by DarthGandalf** [comment]
Cmake. You can look at my home dir, it's all there.

**Comment by janicez** [comment]
You can probably close as irreproducible for now.

On 7 January, 2020 11:42:29 AM PST, Alexey Sokolov <notifications@github.com> wrote:
>Cmake. You can look at my home dir, it's all there.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/znc/znc/issues/1686#issuecomment-571740455

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
