### ISSUE TITLE
[Security] Cookie missing 'HttpOnly' attribute

### ISSUE THREAD

**Issue by sa7mon** [znc/znc#1689]
The initial cookie given to the user when navigating to the ZNC home page lacks the `HttpOnly` attribute.

Strangely, the code that I believe is supposed to set this attribute looks like it should be working: https://github.com/znc/znc/blob/0ab205ccfa278eaa94063b4ad5e30d997e4c8311/src/HTTPSock.cpp#L745

The request when piped through Burp Suite's proxy, has the following response headers: 

![cookies](https://user-images.githubusercontent.com/3712226/68064837-eff90080-fcee-11e9-902b-8da3b3b6ce8e.PNG)

For more information about why this attribute is so important, refer to [this article](https://blog.codinghorror.com/protecting-your-cookies-httponly/)

* Tested on ZNC 1.7.5

**Comment by DarthGandalf** [comment]
Looks like Burp Suite is messing with the cookie.

**Comment by sa7mon** [comment]
> Looks like Burp Suite is messing with the cookie.

Burp suite doesn't change responses. It only acts as a proxy server to watch traffic and re-send requests if desired.

**Comment by DarthGandalf** [comment]
Try without Burp. Does it still miss HttpOnly?

**Comment by sa7mon** [comment]
Tried that same request in Postman and the Set-Cookie header does have HttpOnly now. Strange.

Can't reproduce the problem so I'll close this issue.
