### ISSUE TITLE
defining path to ssl cert and ssl key and dhparam files does not work

### ISSUE THREAD

**Issue by danhimalplanet** [znc/znc#1694]
I have a Letsencrypt wildcard certificate and private key.

This works fine:

I generated znc.pem , used it with znc, I am able to connect to it successfully over ssl
```
$ openssl dhparam -out dhparam.pem 2048
$ cat /var/lib/docker/volumes/letsencrypt/_data/live/domain.com/{privkey,fullchain}.pem dh2048.pem > znc.pem
```

If I instead define the following in znc.conf and don't use znc.pem , I get a cert error when connecting over ssl ( I mounted dhparam to /dhparam.pem in the znc container )
```
SSLCertFile = /var/lib/docker/volumes/letsencrypt/_data/live/domain.com/fullchain.pem
SSLKeyFile = /var/lib/docker/volumes/letsencrypt/_data/live/domain.com/privkey.pem
SSLDHParamFile = /dhparam.pem
```

**Comment by DarthGandalf** [comment]
What cert error is that?
Show znc -D
What version?

пн, 2 дек. 2019 г. в 03:24, danhimalplanet <notifications@github.com>:
