### ISSUE TITLE
Enable LGTM for code analysis (Semmle)

### ISSUE THREAD

**Issue by XVilka** [znc/znc#1695]
Will help to eliminate obvious errors, along with Coverity - they do report different issues. C/C++ is supported. See:
- https://lgtm.com/
- https://github.com/marketplace/lgtm

Their main focus is the security, which is important for a network service like ZNC. You can read many good articles on how the found various vulnerabilities using their engine and query language (QL) in [their blog](https://blog.semmle.com/).

![image](https://user-images.githubusercontent.com/203261/69871982-2f673c80-12ef-11ea-85bd-ff273782cf90.png)

**Comment by dgw** [comment]
I'm a fan of LGTM/Semmle analysis, but it's worth mentioning that its PR jobs can take quite a while to run—at least, they do for the sizable Python project I use it on. 15 minutes, usually, which is more than 6x the longest CI build/test run we've had in recent memory.

Obviously, YMMV, as the projects are in different languages and of different sizes, but I hope my experience is helpful in making a decision!

**Comment by DarthGandalf** [comment]
I enabled something, let's see what happens.
