### ISSUE TITLE
ZNC 1.7.4 *autoop can't delmasks

### ISSUE THREAD

**Issue by dchmelik** [znc/znc#1696]
On ZNC 1.7.4 (which I want to stay at for *fish) *autoop I can't delmasks.  I mentioned this on IRC, showed output, and MetaNova (though it works for him) suggested open an issue and get debug output.  I see I'd have to restart with '-D,' but what do I do after that?  Maybe the issue is something specific to my server or compilation of ZNC (we'd find with debug) but thanks for not saying on IRC 
'it works for me so isn't an issue"...  I may have had the problem in earlier versions; have been using ZNC since about 1.7.4, but I have such a huge list of users/hostmasks I can't even see the full *autoop user list without deleting wrong/old hostmasks so this finally became a big issue for me.  I also use(d) ZNC on several servers and am pretty sure delmasks worked in the past on some servers/versions, just not this (my main) one...

OS: Slackware64 14.2 up-to-date stable version.

**Comment by psychon** [comment]
From 1.7.4's `autoop.cpp`:
https://github.com/znc/znc/blob/e661cdf9a394e2afd1b97517efa21fa2fa757e22/modules/autoop.cpp#L152-L174
So, what happens when you try to use this command?

> I can't even see the full *autoop user list 

Why not?

**Comment by dchmelik** [comment]
What happens is it doesn't delete them.  So, there are so many in the list I need to delete, it scrolls off the top of the screen and I can't see the ones above.

**Comment by psychon** [comment]
But it does say "Channel(s) Removed from user"?

**Comment by dchmelik** [comment]
No; delmasks doesn't remove channels, does it?  I wasn't asking about delchans.
I said 'What happens is it doesn't delete them (it says it does, but doesn't.)'  I'll explain what that means: 'it,' 'them' are pronouns that refer to the most recent singular (it) and plural (them) things.  'It' refers to actually the command you referred to when you said 'what happens' (which I specified as an answer to that) and 'them' refers to the plural input of that command.
So I already told you delmasks says it removes the masks but doesn't.

<*autoop> Hostmasks(s) Removed from user

**Comment by DarthGandalf** [comment]
Can you show the list before and after and what exactly you sent to the autoop?

**Comment by dchmelik** [comment]
well I said 'it scrolls off the top of the screen and I can't see the ones above' because I have so many users/hostmasks and ones I have to delete.  I could show some of them.

**Comment by dchmelik** [comment]
Okay, here are some commands pasted.
` <darwin> delmasks darwin *!darwin@unix.shellsource.org
 <*autoop> Hostmasks(s) Removed from user darwin
 <darwin> listusers
 <*autoop> +-------------+--------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
 <*autoop> | User        | Hostmasks                                                                      | Key       | Channels                                                                                                                                                |
 <*autoop> +-------------+--------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
 <*autoop> | 187         | |187|*!*t1ght@demons.rikskriminalen.nu                                         | __NOKEY__ | #coders                                                                                                                                                 |
 <*autoop> | ads         | ads*!*ads@77.244.242.36                                                        | __NOKEY__ | #coders                                                                                                                                                 |
 <*autoop> | `-          | ads*!*ads@host111155204031.rev.rikskriminalen.nu                               |           |                                                                                                                                                         |
 <*autoop> | alexander   | *!*basileus@charger.kire.net                                                   | __NOKEY__ | #greece #hellas                                                                                                                                         |
 <*autoop> | `-          | *!*basileus@eggdrops.net                                                       |           |                                                                                                                                                         |
 <*autoop> | American    | usa@c-73-11-182-36.hsd1.wa.comcast.net                                         | __NOKEY__ | #washington                                                                                                                                             |
 <*autoop> | AppleGroo   | *!*2604:180:2:326::7c                                                          | __NOKEY__ | #xnc                                                                                                                                                    |
 <*autoop> | `-          | *!*applegroo@interdo.me                                                        |           |                                                                                                                                                         |
 <*autoop> | B30W01f     | *!*B30W01f@valhallabbs.uk.to                                                   | __NOKEY__ | #demoscene                                                                                                                                              |
 <*autoop> | Balls       | *!*nathan@certified.nonsocial.net                                              | __NOKEY__ | #berniesanders #civil-politics                                                                                                                          |
 <*autoop> | banana      | *!*sid228946@id-228946.stonehaven.irccloud.com                                 | __NOKEY__ | #greece #hellas                                                                                                                                         |
 <*autoop> | Bill_ORLY   | Bill*!*jak@warped.plugh.us                                                     | __NOKEY__ |  #comicbooks #comics                                                                                                                                    |
 <*autoop> | Brinken     | *!*ident@h-223-151.A193.priv.bahnhof.se                                        | __NOKEY__ | #xnc                                                                                                                                                    |
 <*autoop> | bt          | *!*bt@192.249.59.196                                                           | __NOKEY__ | #asciiart                                                                                                                                               |
 <*autoop> | chaos       | chaos*!*ch@ereet.org                                                           | __NOKEY__ |  #coders                                                                                                                                                |
 <*autoop> | chiyou      | *!*chiyou*@66.44.122.23                                                        | __NOKEY__ | #neigong #qigong #satanism #yoga                                                                                                                        |
 <*autoop> | `-          | *!*ip68-100-20-154.dc.dc.cox.net                                               |           |                                                                                                                                                         |
 <*autoop> | comrade     | comrade*!*comrade@really.ownz.com                                              | __NOKEY__ | #coders                                                                                                                                                 |
 <*autoop> | Crusher     | *!*jason.lin@*.dhcp.ftbg.wi.charter.com                                        | __NOKEY__ |  #not-math                                                                                                                                              |
 <*autoop> | |-          | *!*lind@*dyn.centurytel.net                                                    |           |                                                                                                                                                         |
 <*autoop> | `-          | Crusher*!*lind@ip16-60.tvmax-fiber-1.hou.ygnition.net                          |           |                                                                                                                                                         |
 <*autoop> | Curiosity   | Curiosity*!*olybray@probability-theory.makes.me.feel.like.a.dumbass.ws         | __NOKEY__ |  #not-math                                                                                                                                              |
 <*autoop> | dapoohda    | *!*keltoi@*dynamic.midco.net                                                   | __NOKEY__ | #pagan_tea_house                                                                                                                                        |
 <*autoop> | darwin      | *!*d@melik.windwireless.net                                                    | __NOKEY__ | *                                                                                                                                                       |
 <*autoop> | |-          | *!*darwin@45.79.84.213                                                         |           |                                                                                                                                                         |
 <*autoop> | |-          | *!*darwin@loves.mrsmaryjane.com                                                |           |                                                                                                                                                         |
 <*autoop> | |-          | *!*darwin@pythagorean.akousmatikos.templeofmathematics.com                     |           |                                                                                                                                                         |
 <*autoop> | |-          | *!*elfgod@erisfree.net                                                         |           |                                                                                                                                                         |
 <*autoop> | |-          | *!*temple-of-mathematics.com                                                   |           |                                                                                                                                                         |
 <*autoop> | |-          | *!?d@unixnerd.net                                                              |           |                                                                                                                                                         |
 <*autoop> | |-          | *!d@206.63.237.146                                                             |           |                                                                                                                                                         |
 <*autoop> | |-          | *!d@260O.net                                                                   |           |                                                                                                                                                         |
 <*autoop> | |-          | *!d@melik.windwireless.net                                                     |           |                                                                                                                                                         |
 <*autoop> | |-          | *!d@network-neutrality.net                                                     |           |                                                                                                                                                         |
 <*autoop> | |-          | *!darwin@c0derz.net                                                            |           |                                                                                                                                                         |
 <*autoop> | |-          | *!darwin@temple-of-mathematics.com                                             |           |                                                                                                                                                         |
 <*autoop> | |-          | *!darwin@unix.shellsource.org                                                  |           |                                      `
There on the last line you see that one wasn't deleted.

**Comment by dchmelik** [comment]
Here are some commands pasted.
`<darwin> delmasks darwin *!*darwin@loves.mrsmaryjane.com
<*autoop> Hostmasks(s) Removed from user darwin
<darwin> listusers
<*autoop> +-------------+--------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
<*autoop> | User        | Hostmasks                                                                      | Key       | Channels                                                                                                                                                |
<*autoop> +-------------+--------------------------------------------------------------------------------+-----------+---------------------------------------------------------------------------------------------------------------------------------------------------------+
<*autoop> | 187         | |187|*!*t1ght@demons.rikskriminalen.nu                                         | __NOKEY__ | #coders                                                                                                                                                 |
<*autoop> | ads         | ads*!*ads@77.244.242.36                                                        | __NOKEY__ | #coders                                                                                                                                                 |
<*autoop> | `-          | ads*!*ads@host111155204031.rev.rikskriminalen.nu                               |           |                                                                                                                                                         |
<*autoop> | alexander   | *!*basileus@charger.kire.net                                                   | __NOKEY__ | #greece #hellas                                                                                                                                         |
<*autoop> | `-          | *!*basileus@eggdrops.net                                                       |           |                                                                                                                                                         |
<*autoop> | American    | usa@c-73-11-182-36.hsd1.wa.comcast.net                                         | __NOKEY__ | #washington                                                                                                                                             |
<*autoop> | AppleGroo   | *!*2604:180:2:326::7c                                                          | __NOKEY__ | #xnc                                                                                                                                                    |
<*autoop> | `-          | *!*applegroo@interdo.me                                                        |           |                                                                                                                                                         |
<*autoop> | B30W01f     | *!*B30W01f@valhallabbs.uk.to                                                   | __NOKEY__ | #demoscene                                                                                                                                              |
<*autoop> | Balls       | *!*nathan@certified.nonsocial.net                                              | __NOKEY__ | #berniesanders #civil-politics                                                                                                                          |
<*autoop> | banana      | *!*sid228946@id-228946.stonehaven.irccloud.com                                 | __NOKEY__ | #greece #hellas                                                                                                                                         |
<*autoop> | Bill_ORLY   | Bill*!*jak@warped.plugh.us                                                     | __NOKEY__ |  #comicbooks #comics                                                                                                                                    |
<*autoop> | Brinken     | *!*ident@h-223-151.A193.priv.bahnhof.se                                        | __NOKEY__ | #xnc                                                                                                                                                    |
<*autoop> | bt          | *!*bt@192.249.59.196                                                           | __NOKEY__ | #asciiart                                                                                                                                               |
<*autoop> | chaos       | chaos*!*ch@ereet.org                                                           | __NOKEY__ |  #coders                                                                                                                                                |
<*autoop> | chiyou      | *!*chiyou*@66.44.122.23                                                        | __NOKEY__ | #neigong #qigong #satanism #yoga                                                                                                                        |
<*autoop> | `-          | *!*ip68-100-20-154.dc.dc.cox.net                                               |           |                                                                                                                                                         |
<*autoop> | comrade     | comrade*!*comrade@really.ownz.com                                              | __NOKEY__ | #coders                                                                                                                                                 |
<*autoop> | Crusher     | *!*jason.lin@*.dhcp.ftbg.wi.charter.com                                        | __NOKEY__ |  #not-math                                                                                                                                              |
<*autoop> | |-          | *!*lind@*dyn.centurytel.net                                                    |           |                                                                                                                                                         |
<*autoop> | `-          | Crusher*!*lind@ip16-60.tvmax-fiber-1.hou.ygnition.net                          |           |                                                                                                                                                         |
<*autoop> | Curiosity   | Curiosity*!*olybray@probability-theory.makes.me.feel.like.a.dumbass.ws         | __NOKEY__ |  #not-math                                                                                                                                              |
<*autoop> | dapoohda    | *!*keltoi@*dynamic.midco.net                                                   | __NOKEY__ | #pagan_tea_house                                                                                                                                        |
<*autoop> | darwin      | *!*d@melik.windwireless.net                                                    | __NOKEY__ | *                                                                                                                                                       |
<*autoop> | |-          | *!*darwin@45.79.84.213                                                         |           |                                                                                                                                                         |
<*autoop> | |-          | *!*darwin@loves.mrsmaryjane.com `
There the last one wasn't deleted.

**Comment by dchmelik** [comment]
I didn't want to jump into killing the znc and running it in debug mode, since I have some other users using it and no alternative one for them yet, though they mostly were okay with me killing it temporarily... however there might've been several stops & starts.  I deleted and recreated a user in *autoop and no longer am having this problem.  As some experts on IRC suspected, maybe some bad characters/unicode got in there somehow.  I hid my previous comment because considered the list of those hostmasks somewhat confidential.  If I have this problem in the future and have an easier time getting to debugging, I'll try to reopen this with a list what happens if you debug and then when you do delmasks...
