### ISSUE TITLE
ZNC intermittently doesn't encrypt connection

### ISSUE THREAD

**Issue by keystrike** [znc/znc#1716]
Running ZNC 1.7.5

I noticed with Wireshark that the IRC traffic between my client and the ZNC server was not encrypted. But it is now encrypted after reconnecting. No configuration has changed and the connection to the IRC server was maintained. The connection from ZNC to the IRC server is not encrypted. I'm not sure how to replicate this but can run any requested tests.

**Comment by DarthGandalf** [comment]
So you intended one side to be encrypted, and the other not?

I suspect you saw an unencrypted packet in wireshark, but accidentally attributed it to the wrong side.

**Comment by teward** [comment]
There are **two separate connections at play here** so it is likely you are misreading where Wireshark is indicating packet traffic.

This is a quickly drawn diagram to show you what you'll see:
![Drawing1](https://user-images.githubusercontent.com/327952/79701927-ed736e80-826e-11ea-87a8-e10eb450045c.png)

Wireshark will ONLY show you the packets between your computer and the ZNC Server - if you are not connected to the ZNC server with SSL from your IRC client then that is why you see the plain-text packets.  However, the traffic from ZNC to the IRC Network (in the example I used Freenode where `#znc`'s channel lives) will still be encrypted if the connection used from ZNC to the IRC Network is set to use SSL.

Where were you wiresharking your packet data (basically, is it just like the diagram I drew hastily above)?  Are you using SSL to connect from your IRC Client to your ZNC Server?

**Comment by keystrike** [comment]
Thanks for the quick reply. I am monitoring traffic between my IRC client and the ZNC server. I am using SSL to connect from my IRC client to the ZNC server. The client showed my ZNC server's certificate correctly when I checked. My only guess is that perhaps the connection was downgraded for some reason. I will try to replicate the problem and attach a packet capture.

**Comment by teward** [comment]
@keystrike Make sure that your packet capture is filtered to ONLY capture packets between your computer and your ZNC Server, and only on the ZNC port(s) that you know are open on that system.  :)

**Comment by keystrike** [comment]
I spent a few hours on it but wasn't able to replicate the problem. I searched for the old temp pcapng files but couldn't recover them either unfortunately.
