### ISSUE TITLE
*sasl timeouts when user cert is unreadable

### ISSUE THREAD

**Issue by Avamander** [znc/znc#1721]
When the user cert (from *cert) is unreadable for znc then the connection to the server just repeatedly timeouts. No read error is emitted into the server buffer. This happens until *sasl is unloaded, changing mandatory sasl setting or used mechanism doesn't work.

I just encountered this and it wasn't much fun to debug.

**Comment by DarthGandalf** [comment]
What version?
How exactly is it unreadable?

**Comment by Avamander** [comment]
>What version?

ZNC 1.8.0

> How exactly is it unreadable?

No read permission on the file.

**Comment by DarthGandalf** [comment]
I can't reproduce this. Please provide exact steps what modules did you configure, how, which server using, etc
