### ISSUE TITLE
Cannot connect to IRC (Failed to setup bind host). Retrying...

### ISSUE THREAD

**Issue by ZeclintrYzath** [znc/znc#1748]
When i have established a connection with ZNC in IRSSI and i try to connect then i have this error.
Is it a computer problem?

**Comment by DarthGandalf** [comment]
No, it's your misconfiguration. Why do you need bindhost? `/znc clearbindhost` will help you.

Also, when opening bugs, please provide more details, at least what bindhost you used and ZNC version.

**Comment by ZeclintrYzath** [comment]
DarthGandalf wrote:
> No, it's your misconfiguration.

incorrect configuration in the computer, znc or irssi? i use irssi in Ubuntu 18.04 and have this error:

`15:25 -!- Irssi: Starting query in undernet-znc with *status`
`15:25 <*status> Cannot connect to IRC (Failed to setup bind host). Retrying...`
`15:26 <*status> Cannot connect to IRC (Failed to setup bind host). Retrying...`
`15:26 <*status> Cannot connect to IRC (Failed to setup bind host). Retrying...`
`15:27 <*status> Cannot connect to IRC (Failed to setup bind host). Retrying...`

I still tried to install the script hostname.pl, but it didn't help me, when i type, then i see the following::

`15:32 -!- - Welcome to ZNC -`
`15:32 -!- Irssi: Resolving IP addresses...`
`15:32 -!- 1 192.168.0.2          user-desktop`

but i do not see in this list the host that i bind in the config of znc "91.237.143.0".
maybe need through iptables to turn traffic to the desired port 113? Using the command:

`sudo iptables -t nat -A PREROUTING -p tcp -d 91.237.143.0 --dport 113 -j DNAT --to 91.237.143.0:11300`

I also edited the file /etc/hosts:

127.0.0.1       localhost
127.0.1.1       user-desktop
`0.0.0.0 91.237.143.0`

am i doing it right?
i checked my znc version:

`znc -version`
`ZNC 1.6.6+deb1ubuntu0.2 - http://znc.in`
`IPv6: yes, SSL: yes, DNS: threads, charset: yes`

I tried everything i could, but I can't bind the host `91.237.143.0` to hide my real ip address/host.
I want to bind the IP address of another country ~91.237.143.0, but I can't do it, am i doing it right? Where is this error in Ubuntu, znc or irssi?

**Comment by psychon** [comment]
> Why do you need bindhost? `/znc clearbindhost` will help you.

Did you try the above command that @DarthGandalf suggested? Does it make the error go away?

Your bindhost must be one of the IP addresses of the computer that ZNC is running on. This option only exists to choose which IP to use in case the computer has multiple ones. It cannot hide your IP address.

**Comment by DarthGandalf** [comment]
> incorrect configuration in the computer, znc or irssi?

ZNC

> I can't bind the host 91.237.143.0 to hide my real ip address/host.

Correct. You cannot do that, and that's not what bind means. https://wiki.znc.in/FAQ#What_are_BINDHOSTS_and_why_can.27t_I_make_mine_work.3F

**Comment by ZeclintrYzath** [comment]
i used the command you suggested and this outputs:

`/znc clearbindhost`
`17:30 <user> clearbindhost`
`17:30 <*status> Bind host cleared for this network.`
`17:30 <*status> Cannot connect to IRC (Failed to setup bind host). Retrying...`

after that i execute:

`/connect undernet`
`/join #demochannel`

but this still does not establish a spoofed ip address "91.237.143.0".

from ZNC FAQ:

> _then it is likely you have set an IP address or host name that is not available on your computer._

but how to make this fake IP address "91.237.143.0" available on my computer? Can somehow make changes to resolv.conf? But how can i edit it?
I also do:

`/host show`
`show=+~sad@v133-130-111-150.a03a.g.tyo1.static.cnode.io`

And i see this address assigned to me, but how to bind it? Should i use iptables?

and also these 2 commands do nothing:

`% host demo.znc.in`
`% host 91.237.143.0`

**Comment by DarthGandalf** [comment]
> 17:30 <*status> Cannot connect to IRC (Failed to setup bind host). Retrying...

Then use also `/znc clearuserbindhost`. The other command clears only the network host, not user host.

> but how to make this fake IP address "91.237.143.0" available on my computer?

It's fake. Why do you think it will be available? Even if you add it to your computer, how will other hosts (e.g. IRC server) know where to send packets addressed to 91.237.143.0?

**Comment by ZeclintrYzath** [comment]
That is, in fact, it turns out that znc is not able to forge IP address/host. But only VPN will do it! And this issue can be considered solved with the help of any VPN?

**Comment by DarthGandalf** [comment]
> That is, in fact, it turns out that znc is not able to forge IP address/host.

Yay, you finally have read my response and parts of FAQ I linked

> But only VPN will do it!

Now it's time to read the FAQ again: https://wiki.znc.in/FAQ#But_I_want_to_hide_my_IP.21_How_to_do_that.3F

**Comment by ZeclintrYzath** [comment]
And what kind of host:

/host show
show=+~sad@v133-130-111-150.a03a.g.tyo1.static.cnode.io

When i change for example "91.237.143.0" and accordingly i change `/host show` (show=+~sad@v133-130-111-150.a03a.g.tyo1.static.cnode.io). If i expose bindhost for example "2.200.0.0-2.207.255.255" then I change `/host show` accordingly then i have (********not show=+~sad@v133-130-111-150.a03a.g.tyo1.static.cnode.io and already another********).
Change bindhost somehow affects on `/host show`???

when i add network to irssi with 127.0.0.1, i.e:

`/server add -auto 127.0.0.1 1027 usernane:password`

then me need to somehow set the settings firewall/iptables so that the connection is tied on `91.237.143.0` instead `127.0.0.1`, i.e:
It will look something like, type..:

`/server add -auto 91.237.143.0 113 (or 11300) usernane:password`

Along with using the command: `sudo iptables -t nat -A PREROUTING -p tcp -d 91.237.143.0 --dport 113 -j DNAT --to 91.237.143.0:11300`

to clearly identify the incoming traffic on any interface  and indicate it in /etc/hosts.

That is, i am somehow manipulating to change `/host show`?

**Comment by DarthGandalf** [comment]
Check documentation of your client what exactly `/host show` is doing.
