### ISSUE TITLE
znc 1.9 password reset.

### ISSUE THREAD

**Issue by CryptoSiD** [znc/znc#1755]
Hi,

I've been trying to reset my password on znc 1.9.

I follow the F.A.Q but as soon as I restart znc the config goes back to what it was before the change.

1. Stop ZNC.
2. Run "znc --makepass"
3. Edit znc.conf and change the "<Pass password> </Pass>" section which include "Hash" "Method" and "Salt"

I feel bad opening an issue for such a lame problem but I'm unable to resolve it.

**Comment by psychon** [comment]
Shutdown znc before editing the config. I think znc saves the config during shutdown.
