### ISSUE TITLE
oidentd does not work with znc

### ISSUE THREAD

**Issue by camparibr** [znc/znc#1778]
Hi,
My configuration in /etc/oidentd.conf is:

`default {

        default {
                allow spoof
                deny spoof_all
                deny spoof_privport
                allow random
                allow random_numeric
                allow numeric
                allow hide
        }
} `

My file .oidentd.conf location is ~/.oidentd.conf and permission is `-rw-r--r--` (644) ans 
My $HOME direction permission is `drwxr-xr-x`

The configuration os **setfile** is the same `~/.oidentd.conf` and **setformat** is `global { reply "%user%" }`

The message in the server irc is `No ident response; username prefixed with ~`
I have this same configuration in other vps and work. I do not know what is a problem. Cloud you help me?

**Comment by MetaNova** [comment]
Per https://wiki.znc.in/Identfile#Using_identfile_with_oidentd the /etc/oidentd.conf needs to contain
`user "znc" {
    default {
        allow spoof
        allow spoof_all
    }
}`
as the default {} block is insufficient by itself.

**Comment by camparibr** [comment]
I appreciate your help.
I had already switched to this configuration that you suggested, but it didn't work. But I changed now again, it didn't work again. I want to mention that my znc is running with my username and not with "znc" username. The configuration that i put now, was 

`user "myuser" {
    default {
        allow spoof
        allow spoof_all
    }
}`

`
default {
        default {
                allow spoof
                deny spoof_all
                deny spoof_privport
                allow random
                allow random_numeric
                allow numeric
                allow hide
        }
}
`
but does not work.

**Comment by MetaNova** [comment]
The oidentd daemon needs to be restarted when you edit the oidentd.conf file, and you need to make sure port 113 is accessible remotely.

**Comment by camparibr** [comment]
Yes, 
I restaed  daemon oidentd with command `sudo systemctl restart oidentd` and my port 113 is open. I make command `netstat -anp | grep 113` and have the response:

`tcp        0      0 0.0.0.0:113             0.0.0.0:*               LISTEN      24094/oidentd`
`tcp6       0      0 :::113                  :::*                    LISTEN      24094/oidentd`

I already restart znc and even so, does not work.

**Comment by MetaNova** [comment]
Just because a port is being listened on doesn't mean it's accessible .. you even quoted "No ident response; username prefixed with ~" which means port 113 isn't open.  Check your firewall rules.

**Comment by camparibr** [comment]
Ok. Work now. Was the port 113 that still close.
I guess that I had opened. 
Thank you so much even.
