### ISSUE TITLE
1.9-git-master No modules found 

### ISSUE THREAD

**Issue by Bl00dsoul** [znc/znc#1793]
1.8.2 can be compiled with 
./configure --with-module-prefix=/usr --prefix=/usr; make; make install, and work just fine.

But the latest master I can not compile a binary that will load the modules.
The with-module-prefix option seems to have been removed, and modules apear to be hardcoded to $libdir/znc now, which seems fine, but no matter what I try, with --prefix or without, cmake -DCMAKE_INSTALL_PREFIX=

The resulting binary always fails to load modules.

sudo -u znc /usr/local/bin/znc -f
[ .. ] Checking for list of available modules...
[ !! ] failed
[ ** ] No modules found. Perhaps you didn't install ZNC properly?
[ ** ] Read https://wiki.znc.in/Installation for instructions.
[ ?? ] Do you really want to run ZNC without any modules? (yes/no) [no]:

Platform is debian stable

**Comment by DarthGandalf** [comment]
Can you provide full log? It works fine for me after make install

> sudo -u znc /usr/local/bin/znc -f

This seems to use /usr/local not /usr
