### ISSUE TITLE
Remove freenode as default network option on initial setup

### ISSUE THREAD

**Issue by TheMesquito** [znc/znc#1800]
Due to freenode essentially being taken over by a hostile entity (see [here](https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409) )I would suggest the default options for setup be changed to a different server. I would recommend  [LiberaChat](https://libera.chat/) as it is run by former staff that where forced to step down due to the takeover of the network, but any other network other then freenode would probably be a good change.

**Comment by MetaNova** [comment]
Realistically, it also should be irc.libera.chat as this is where the official #znc channel is located.

**Comment by DarthGandalf** [comment]
That's good to know, thanks!

Fortunately, we switched already. Both the default network in the configuration wizard, and #znc are on libera for a while now.

**Comment by DarthGandalf** [comment]
Well, the wizard change is not in the release yet

**Comment by TheMesquito** [comment]
My mistake then! I just setup ZNC again and noticed that it was still freenode, so I wanted to raise the issue here. Thank you for changing the defaults so quickly.

**Comment by CensorshipAlert** [comment]
Please see:
https://github.com/hexchat/hexchat/issues/2604#issuecomment-877724781

The author of that gist was busted today using censorship and misdirection to steer a false narrative:

https://twitter.com/Equitis_Rubrum/status/1413925219794837506

It should also be noted that both the OP and author of said gist are collaboratively working with the Libera staff to defame the Freenode network. No recommendation intended, this is an informational notice only.

**Comment by iczero** [comment]
@CensorshipAlert this is bullshit and you know it. ZNC left freenode because their channel was nuked, and you were entirely complicit in this and hundreds of other unauthorized channel takeovers. What other reason is needed?

**Comment by TheMesquito** [comment]
I would also like to make it clear, I have had no interactions with any staff at Libera about this, I am doing this of my own accord as a concerned former user of freenode. I simply think that since Freenode is basically a completely different network now, it should not be the default option anymore, and like MetaNova said above, the official #znc channel  is Libera so it only makes sense.

**Comment by DarthGandalf** [comment]
@CensorshipAlert rasengan, did you register on github under a new name just to post this? Honestly, this only looks like a desperate attempt to get users back.

Re ZNC defaults: even if there would be no direct actions against #znc itself (there were), still, the majority of people and projects are now at libera. So it only makes sense to have libera as default now.

Re censorship: if I really wanted to censor people, I'd make ZNC to ignore user's server, and replace freenode with libera for all ZNC users, don't you think? Or do you want me to actually implement such censorship?
There's not much to do now on freenode other than trolling, but people are free to connect to it if they wish. It's just not the default.

**Comment by PlasmaStar** [comment]
What's ironic, is certain entities trying to censor out the fact that thousands of users witnessed an exchange of power, by using petty immature comments.
