### ISSUE TITLE
Someone help me. I'm having this problem when compiling znc.

### ISSUE THREAD

**Issue by GabrielSantos198** [znc/znc#1801]
![Screenshot_20210716-110232](https://user-images.githubusercontent.com/69887726/125961231-c98d85c8-c74c-4b7c-8306-cb19417fe8c2.png)

**Comment by GabrielSantos198** [comment]
@DarthGandalf This is my system:

![Screenshot_20210716-131702](https://user-images.githubusercontent.com/69887726/125979151-2ba4250c-e7f4-4ef7-af15-63239cb041fb.png)

**Comment by DarthGandalf** [comment]
Why are you trying to build it on Android?

**Comment by RealKindOne** [comment]
This?

https://play.google.com/store/apps/details?id=com.termux&hl=en_US&gl=US


https://wiki.termux.com/wiki/Main_Page

**Comment by GabrielSantos198** [comment]
@DarthGandalf I don't have pc so I do everything on android.

**Comment by GabrielSantos198** [comment]
@RealKindOne Yes

**Comment by DarthGandalf** [comment]
Why didn't you provide all the details in the initial question? First, please read http://www.catb.org/~esr/faqs/smart-questions.html

Quick google search points at https://stackoverflow.com/questions/4610086/pthread-cancel-alternatives-in-android-ndk and https://github.com/tux-mind/libbthread
You can try those
