### ISSUE TITLE
Finalize server-time

### ISSUE THREAD

**Issue by kylef** [znc/znc#181]
Create a final specification for server-time, this should include how a client should handle MODE,JOIN,PART,QUIT,KICK's which have a time set.

**Comment by jpnurmi** [comment]
Adding server-time to all messages will become easier after #506 is done. I'll start working on it after the release.

**Comment by kylef** [comment]
This issue has been done, to complete a final specification (which is now in IRCv3).

**Comment by DarthGandalf** [comment]
Except the name of cap, which waits for IRC 3.2 to be released, when we can drop the `znc.in/` prefix.
