### ISSUE TITLE
An apology

### ISSUE THREAD

**Issue by nanoni17728** [znc/znc#1818]
Hi. I was the person who opened issue #1810. I would like to apologize for my behavior to @DarthGandalf. I got sidetracked out of my original issue and even though it didn’t lead to anything constructive I don’t think this is the kind of situation where being aggressive is the right thing to do.

There wasn’t any meaning to what I wrote besides letting frustration out. A good chunk of online communities don’t go their way to help and include newcomers and it is quite exhaustive after years.

So yeah, sorry for lashing out. I wish you the best.

**Comment by DarthGandalf** [comment]
No problem
