### ISSUE TITLE
Add ircv3 extended join account into to logging

### ISSUE THREAD

**Issue by khaytsus** [znc/znc#1842]
ZNC already handles extended join nicely in that it passes it along to clients like weechat etc, that all works fine, but I would love to see it logged in the znc logs.

Of course this is the typical join log from znc:

[22:18:19] *** Joins: somenick (~toor@zncrools.com)

Perhaps something like?

[22:18:19] *** Joins: somenick (~toor@zncrools.com accountname)

And if no account name, just don't add the (space)$accountname bit?

**Comment by pajamian** [comment]
Created PR #1870 to address this.
