### ISSUE TITLE
Block the PART of the channels

### ISSUE THREAD

**Issue by ZarTek-Creole** [znc/znc#1844]
I would like an option to avoid exiting channels by blocking "PART #Channel" commands. Indeed, I use an Eggdrop during a restart / relaunch of this one it tends to send a "JOIN 0" or "PART #Channel" which has the effect of leaving the rooms it is an annoying behavior.

I assume that in other cases, some wish not to leave a specific channel and this may apply to other cases!

The idea would be to have a permanent channel parameter that ignores the PARTS of the client irc, indicating that it is a channel with the permanent status which prevents them from leaving.

Thank you.

**Comment by dgw** [comment]
https://wiki.znc.in/Stickychan

**Comment by ZarTek-Creole** [comment]
> https://wiki.znc.in/Stickychan

A very big thank you. I will try it seems perfect. How could I have overlooked this.
