### ISSUE TITLE
Problem with znc

### ISSUE THREAD

**Issue by greyhat94** [znc/znc#1864]
Hi, I need some help with znc. I am trying to enable the option that allows me to enable IRC logging and as soon as I do this I get a message saying: "User was edited, but config file was not written znc". I tried to access my vps server through FileZilla and discovered that znc doesn't write the logs: the latest text file is 0 KB. I thought there was a problem with my znc software. Can anyone help me understand what's wrong with it? Sorry for my bad English.

**Comment by DarthGandalf** [comment]
You might get better support if you come to #znc on libera.chat

But most likely you have some permission issues. Is ~/.znc (or wherever your datadir is) writeable by the znc user (or whichever user is running it)? Or maybe the disk is full?

**Comment by greyhat94** [comment]
Hi! Thank you for your prompt reply. The disk is full and I'm looking to
clean it up. I was wondering if it's possible to delete all logs. What is
the best disk size to avoid this problem?

Il lun 6 feb 2023, 17:13 Alexey Sokolov ***@***.***> ha
scritto:

**Comment by DarthGandalf** [comment]
If you mean the log module, it always grows, so the answer is "infinity", unless you add some kind of log rotation (this is not included in ZNC).

If you mean buffer playback with savebuff module, it doesn't need anything huge. Multiply buffer size by number of channels you have.
