### ISSUE TITLE
Client connecton stalled after CAP ACK

### ISSUE THREAD

**Issue by CTSchorsch** [znc/znc#1875]
Hey all,

we are using znc 1.8.2 to connect a client with small bandwith and high latency to an irc channel. the client connects to the server but stopps after capability handling:

Connecting to 10.250.0.1:5050 (10.250.0.1:5050)
Connected. Now logging in.
Capabilities supported: batch cap-notify echo-message multi-prefix server-time userhost-in-names znc.in/batch znc.in/self-message znc.in/server-time-iso
Capabilities requested: cap-notify multi-prefix server-time userhost-in-names znc.in/server-time-iso 
Capabilities acknowledged: cap-notify multi-prefix server-time userhost-in-names znc.in/server-time-iso
Disconnected ()

connections from a stable and fast LAN/WLAN works fine and we have no idea what happens

Thanks
Georg

**Comment by DarthGandalf** [comment]
show `znc -D`

**Comment by CTSchorsch** [comment]
Next flight is on saturday, 18:00 UTC, i will record the debug-log, thanks

**Comment by CTSchorsch** [comment]
It seems to be an MTU Problem on the satcom link. Not an ZNC Issue
closed
