### ISSUE TITLE
can't remove some channels from chansaver

### ISSUE THREAD

**Issue by dchmelik** [znc/znc#1886]
On znc 1.8.2 I can't completely remove some channels from chansaver; while some (like libera IRC #pidgin) appear to be removed, the next time I connect to znc, they've been re-added.  It happens every time (so far happened to me 100+ times but I just got to reporting it now).

**Comment by RealKindOne** [comment]
Is Stickychan loaded?

https://wiki.znc.in/Stickychan

(You can also join ```irc.libera.chat #znc``` for a possibly faster response time)

**Comment by dchmelik** [comment]
No, it's not.

**Comment by dchmelik** [comment]
<darwin> listmodules
<*status> Global modules:
<*status> webadmin
<*status> certauth
<*status> chansaver
<*status> identfile
<*status> notify_connect
<*status> blockuser
<*status> lastseen
<*status> User modules:
<*status> chansaver
<*status> controlpanel
<*status> alias
<*status> autoattach
<*status> autoreply
<*status> cert
<*status> dcc
<*status> webadmin
<*status> buffextras
<*status> Network modules:
<*status> autocycle
<*status> autoop
<*status> autovoice
<*status> crypt
<*status> keepnick
<*status> modules_online
<*status> nickserv
<*status> perform
<*status> route_replies
<*status> sasl
<*status> simple_away

**Comment by DarthGandalf** [comment]
Check whether your client tries to autojoin some channels

**Comment by dchmelik** [comment]
> Check whether your client tries to autojoin some channels

Somehow they got into that.
