### ISSUE TITLE
Reconnecting too fast

### ISSUE THREAD

**Issue by roughnecks** [znc/znc#1888]
Hello,

since I moved from chrome to Firefox, I'm getting the error in subject when I try to log in to the web interface.
Sometimes I'm able to enter and when I click a menu item, it does the same thing again.
Some other times, if I wait a bit between a click and the next, I'm able to enter successfully.

I'm running ZNC from Debian 12.

Thanks

**Comment by roughnecks** [comment]
Yes, I have that module on fail2ban, but I cannot find any way to increase its settings. I looked under filter.d/znc-adminlog.conf but there isn't such a setting.

**Comment by RealKindOne** [comment]
ZNC's fail2ban does not directly interact with the actual program fail2ban. The fail2ban program just reads ZNC's ```adminlog/znc.log```.

You need to edit ZNC's fail2ban in the webadmin or via your IRC client.

https://wiki.znc.in/Fail2ban

P.S. for a possibly faster response time you can try the irc channel at ```irc.libera.chat #znc```

**Comment by roughnecks** [comment]
Alright thanks, I was able to set it via IRC, couldn't find anything in the webadmin page.

**Comment by roughnecks** [comment]
Found it! Thanks again
