### ISSUE TITLE
Perform /timer unknown command

### ISSUE THREAD

**Issue by Goon3r** [znc/znc#1893]

**Comment by Goon3r** [comment]
Timer commands seem to be getting malformed when being set as part of `perform` configuration.

Steps to reproduce:
- Log into any irc server
- Type `/timer` 
- Observe `Invalid Syntax. Type “/timer help” for more information.` (or similar)
- Configure ZNC network perform module
- Enter command `/timer 10 1 join #somechannel`
- Observe `Message(421): timer Unknown command` in irc server logs when reconnect (`/msg *status connect`)

**Comment by RealKindOne** [comment]
The ```/timer``` command is IRC client specific. You are trying to have your ZNC perform a client specific command that is not possible.

**Comment by Goon3r** [comment]
Thanks @RealKindOne I din't realise that `/timer` wasn't part of the specification, I was just lifting and shifting from old atuo join scripts etc so assumed it was.

Thanks for clearning that up.
