### ISSUE TITLE
identd and identfile doeset works

### ISSUE THREAD

**Issue by jabarel** [znc/znc#1904]
Seems the identd and identfile doesent works at all .Cannot set it all the time look with ~ .

**Comment by DarthGandalf** [comment]
http://www.catb.org/~esr/faqs/smart-questions.html

Works for me. Did you forget to enable it in firewall?

**Comment by jabarel** [comment]
I open on the router on firewall 9113 port but seems doesent works . I pointed directly to my internal ip of nas

**Comment by DarthGandalf** [comment]
Wrong port

**Comment by jabarel** [comment]
Be a little bit more specific , identd use 113 port tcp normally . But doesent works , where I’m rong ?

**Comment by jabarel** [comment]
> > Be a little bit more specific , identd use 113 port tcp normally . But doesent works , where I’m rong ?
> 
> > I open on the router on firewall 9113 port
> 
> You need to open and port forward port 113. 9113 is NOT the ident port.

![1](https://github.com/znc/znc/assets/17461080/ac720a9e-bbbb-46f4-aa25-54c13127830c)
![2](https://github.com/znc/znc/assets/17461080/b5cc08c8-1979-4950-a539-9752acca26bf)
![3](https://github.com/znc/znc/assets/17461080/176c0b1d-3962-4f3d-90ef-cb9f4da5d9f0)

**Comment by DarthGandalf** [comment]
Looks like we're back at http://www.catb.org/~esr/faqs/smart-questions.html

Did you provide *any* details? Please read that doc.

**Comment by jabarel** [comment]
> Looks like we're back at http://www.catb.org/~esr/faqs/smart-questions.html
> 
> Did you provide _any_ details? Please read that doc.

irrelevant that doc, if you dont come with a solution , please stay out of this.
