### ISSUE TITLE
Add optional delay to perform commands

### ISSUE THREAD

**Issue by demosdemon** [znc/znc#208]
I'd like the ability to have some performs (in the perform module) to wait a certain amount of time before executing. Mainly, I have some commands that need to be executed after channel joins, but perform executes before channels are joined. A wait period would help.

**Comment by ne0ark** [comment]
@DarthGandalf Is there an updated version of timed_perform module found anywhere ?

**Comment by DarthGandalf** [comment]
@ne0ark I'm not aware of any updated version of it.
