### ISSUE TITLE
ZNC 1.0 crashes when compiled with LLVM/clang

### ISSUE THREAD

**Issue by nyuszika7h** [znc/znc#301]
I've upgraded libssl on my server, so I had to recompile ZNC, but gcc always used up all RAM and swap so I ended up going with clang.

```
nyuszika7h@cadoth ~ % clang++ --version
Debian clang version 3.0-6 (tags/RELEASE_30/final) (based on LLVM 3.0)
Target: x86_64-pc-linux-gnu
Thread model: posix
```

```
nyuszika7h@cadoth ~ % g++ --version
g++-4.7.real (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```

glibc and gdb backtrace: http://ix.io/4rH/

**Edit:** gcc with modperl and modpython disabled (to prevent out of memory), no crash. clang with the same setup still crashes. http://ix.io/4rJ/

**Comment by Mikaela** [comment]
I think this is fixed as Travis builds successfully with clang and I have done so too with 1.6.0.
