### ISSUE TITLE
Building ZNC on SmartOS (Illumos) Fails to ./configure and build properly

### ISSUE THREAD

**Issue by while1eq1** [znc/znc#309]
During the configure, "checking whether openssl is usable...no" will get triggered every time. Ive tried setting --with-openssl, openssl_CFLAGS, openssl_LIBS, CXXFLAGS, LDFLAGS, just about everything.

I got it to compile by removing that check entirely and hardcoding SSL=yes and specifiying --with-openssl=/path/to/my/openssl.

I also had to remove the '-mt' flag that was getting set in all the Makefiles. It was trying to pass a Sun WorkShop flag to gcc even tho it detected the compiler as gcc.

also the library path to libssl.so.1.0.0 had to be set via crle, this was probably due to the way I built it but anyhow, I got it built and it works flawlessy so far.

Id like to help assist in making this build correctly on SmartOS
##

**Comment by blissdev** [comment]
Curious if anyone has gotten this successfully build.

**Comment by Mikaela** [comment]
What is the case with 1.6.1?
