### ISSUE TITLE
Add support for 'away-notify' at capability negotiation time [$30]

### ISSUE THREAD

**Issue by beingalink** [znc/znc#315]
This would make displaying of the away status in irc clients possible without the need for WHO polling which is not a nice way to do it. More information: http://ircv3.atheme.org/extensions/away-notify-3.1

Of course this only works with irc servers/networks that support this feature. <del>As far as I know this should work on freenode, which is one of the biggest networks.</del>

**Comment by Moter8** [comment]
:+1: just put 10$ on this!

**Comment by kaniini** [comment]
@NuclearW said:

> It would indeed, but it has the same problems that the module I wrote has. Namely one cannot know during capability exchange before authentication if the client connecting is connecting to a network that supports away-notify.

`cap-notify` does not solve this problem.  All capabilities are listed in `CAP LS`, and the spec says you should use `CAP LS` for discovery.  Whatever weechat's problem is, it's not to do with `CAP LS`.

**Comment by kaniini** [comment]
Nevermind it's about offering the capabilities to clients.  I get it now.
