### ISSUE TITLE
Add support for 'account-notify' and 'extended-join' capabilities [$20]

### ISSUE THREAD

**Issue by grawity** [znc/znc#316]
Similar to #315. These two capabilities would allow clients to see users' services accounts without having to poll WHO or even WHOIS. This is supported by freenode server-side.

Both capabilities are usually used together:

 - http://ircv3.org/extensions/account-notify-3.1
 - http://ircv3.org/extensions/extended-join-3.1

---

(Bonus points if znc itself enables/disables the capabilities on the server depending on how many attached clients request them, to reduce traffic from the server (useless AWAY and ACCOUNT messages). On the other hand, this would probably make the znc implementation more complex than needed.)

**Comment by Mikaela** [comment]
And today WeeChat added account-notify https://github.com/weechat/weechat/commit/c10787d92fbb6419b8e2940daec1069b711306d4.
