### ISSUE TITLE
Joining all detached channels at once during network connection can lead to Max SendQ exceeded

### ISSUE THREAD

**Issue by mnoorenberghe** [znc/znc#329]
I recently was getting kicked from MozNet upon connection because "Max SendQ Exceeded".  I have flood protection turned on and set to 3 seconds per line + 3 lines sent immediately.. When I look at the *highlight channel showing the joins in all of the channels, I see that there is a 3 second delay between joining my attached channels but then there is a 9 second delay before all of the detached channels get joined at once (with seemingly no flood protection).  If I have #developers in my list of detached channels, I will get disconnected because of Max SendQ Exceeded. I suspect it's because there is a large number of users (~350) in the channel and the server is trying to send that info along with all of the other detached channels being joined at once.  If I disable #developers then I can connect to the network fine.

Apparently we try to join as many channels as possible at once since MaxJoins was removed in db7c47f97d4b18bce7264af5db6331fc296ff69a

ZNC 1.1-git-80-bbde9ab

Global modules: webadmin, adminlog, log
User modules: controlpanel, chansaver, autoattach 
Network modules: watch, autoop, chansaver, savebuff, cmdnotify, log

**Comment by wasamasa** [comment]
This seems to not have been fixed at all.  I've experienced the described issue during a recent Freenode DDOS, searched the internets and discovered that the default is still zero: https://github.com/znc/znc/blob/master/src/User.cpp#L98
