### ISSUE TITLE
Allow password-less accounts which cannot be looged into without a module authorizing

### ISSUE THREAD

**Issue by md-5** [znc/znc#331]
Similar to the unix passwd -l account to only allow su logins. Need this to do my SSO system properly.
##

**Comment by gregswift** [comment]
@md-5 what did you do to accomplish your implementation?

**Comment by md-5** [comment]
I did the same as cyrus above

**Comment by gregswift** [comment]
ok.  so how are you preventing them from changing their passwords and thus bypassing your backend's password system

**Comment by md-5** [comment]
I'm not.

**Comment by gregswift** [comment]
do you care? (bring serious, not snide)

**Comment by md-5** [comment]
Not really, if they want to break their SSO that is their decision :p

**Comment by md-5** [comment]
Logging in again with their SSO password will set their hash back to :: and make them require that pass.

**Comment by gregswift** [comment]
I wish that loging back in via SSO would reset it back to their ::, but it doesnt as far as i can see.

Also, it sounds nice to let breaking SSO be their decision, but typically your SSO system has enforced password policies, including change frequency. If they bypass it here they can 'make it easier' for their IRC config, while lowering your security posture.

**Comment by md-5** [comment]
>I wish that loging back in via SSO would reset it back to the ::, but it doesnt as far as i can see.

My addon does

**Comment by gregswift** [comment]
I noticed i'm on 1.4 (i install from epel) and so I'm gonna eval the 1.6 release as soon as I can.

That being said, in the scenario i listed they would have to reason to log back in with their SSO, and thus it would never reset, so that is a mute point.  It seems that a better security posture would be achieved by disabling local auth explicitly if using external auth method.

**Comment by md-5** [comment]
> It seems that a better security posture would be achieved by disabling local auth explicitly if using external auth method.

Easily done with a small tweak to your SSO addon
