### ISSUE TITLE
"Client ID" concept to make using multiple clients at the same time easier [$270]

### ISSUE THREAD

**Issue by jimeh** [znc/znc#343]
The current solution to deliver all messages to all clients regardless of if others are connected is outlined in the FAQ [here](http://wiki.znc.in/FAQ#How_to_store_private_messages_even_when_user_is_attached.2C_so_other_clients_can_see_them.3F), and basically boils down to creating multiple users, one for each client.

It works great, except keeping configurations in-sync between client devices, or user accounts to be specific, can get annoying.

My suggestion is to keep a single user but adding support for some unique client identifier that can be specified as part of the username. And then playback buffers are stored on a per user and client ID basis, rather than just based on the user. For the sake of simplicity, I'd personally like the client ID only to effect the buffer playback, as in module settings are still stored on a purely per user basis.

I'd suggest a IRC password string format of something like this:

    username[@client_id][/network_name]:password

A few examples would be:

    jimeh@macbookair/QuakeNet:mypassword
    jimeh@iphone/QuakeNet:mypassword
    jimeh@Nexus_4/QuakeNet:mypassword
    jimeh@XChat/QuakeNet:mypassword

I think you get the idea :)

**Comment by nyuszika7h** [comment]
@jpnurmi I just tested it on freenode, and `USER a@b * * :test` results in the username being `~a`.

**Comment by jpnurmi** [comment]
@nyuszika7h Yes, that's intentional. Is it causing troubles? See the commit message of https://github.com/znc/znc/commit/8d77faa260d2a3eb0de7e6a78e7baad0d6cb7b62 for reasoning.

**Comment by nyuszika7h** [comment]
No, I haven't even tried the new changes yet, I just mentioned it as a matter of fact.

**Comment by dgw** [comment]
Is this not implemented yet? ZNC 1.6.0 supports specifying client IDs.

**Comment by Mikaela** [comment]
This is implemented, but nothing is done yet.

**Comment by jpnurmi** [comment]
znc-chanfilter offers client specific channel lists, and znc-clientbuffer
is supposed to provide client specific buffers, but i heard claims that
it's somehow broken for user's own messages. does someone want to take over
znc-clientbuffer? i don't have much interest in maintaining it...

**Comment by jpnurmi** [comment]
Shall we close this?
- https://github.com/znc/znc/commit/8d77faa260d2a3eb0de7e6a78e7baad0d6cb7b62 made it possible for clients to specify an ID via PASS or USER
- [chanfilter](http://wiki.znc.in/Chanfilter) maintains client specific channel lists for identified clients
- [clientbuffer](http://wiki.znc.in/Clientbuffer) maintains client specific buffers for identified clients

**Comment by Mikaela** [comment]
It could probably be argued than chanfilter and clientbuffer are external modules.

**Comment by jpnurmi** [comment]
Who says external modules are not good enough solution? It was an intentional decision to leave them as external for now, to get some feedback and let them mature first. See #749 and #750.

**Comment by Mikaela** [comment]
Maybe this can be closed then

**Comment by jpnurmi** [comment]
> Maybe this can be closed then

I think so too, but I let someone else to do that because of the bounty.

**Comment by DarthGandalf** [comment]
They had chance to comment on it since March.
