### ISSUE TITLE
nickserv identify not working

### ISSUE THREAD

**Issue by Lord255** [znc/znc#364]
i wondered why the nickserv auto identify didn't work..
i found the answer in the code..

void HandleMessage(CNick& Nick, const CString& sMessage) {
CString sNickServName = (!GetNV("NickServName").empty()) ? GetNV("NickServName") : "NickServ";
if (!GetNV("Password").empty()
&& Nick.GetNick().Equals(sNickServName)
&& (sMessage.find("msg") != CString::npos
|| sMessage.find("authenticate") != CString::npos
|| sMessage.find("choose a different nickname") != CString::npos
|| sMessage.find("If this is your nick, type") != CString::npos
|| sMessage.find("type /NickServ IDENTIFY password") != CString::npos)
&& sMessage.AsUpper().find("IDENTIFY") != CString::npos
&& sMessage.find("help") == CString::npos) {
MCString msValues;
msValues["password"] = GetNV("Password");
PutIRC(CString::NamedFormat(GetNV("IdentifyCmd"), msValues));
}
}

so the server which i'm on is not a standard or i don't know but the trigger msg is the following:

This nickname is registered and protected.  If it is your
nick, type /msg NickServ IDENTIFY password.  Otherwise,
please choose a different nick.

if you can see the patterns are not match for these lines.. :(

**Comment by Mikaela** [comment]
It looks like this is fixed, but not closed with the commit.
