### ISSUE TITLE
Unable to connect to IPv4 IRC server when bindhost is IPv6 & IPv4

### ISSUE THREAD

**Issue by Epaphus** [znc/znc#37]
Hi

I have bindhost which has an IPv6 and an IPv4 address, when I connect to an IPv6 IRC server ZNC connects fine, when I connect to an IPv4  server I get 

[08:43] <_status> Attempting to connect to [1.2.3.4 6667] ...
[08:43] <_status> Cannot connect to IRC (Invalid argument). Retrying...

If I run ZNC in debug mode I see the following

User [user] is connecting to [1.2.3.4 6667] ...
Csocket.cpp:880 Connect Failed. ERRNO [22] FD [6]
IRC::user == SockError(22 Invalid argument)

Is this something that can be fixed?

Work around for now is to create a bindhost which is the IPv4 address of which ZNC will use to connect from.

Regards

**Comment by fahadmehar** [comment]
I am having save problem 

Disconnected from IRC (Server address is IPv6-only, but bindhost is IPv4-only). Reconnecting... 

How I fix this ?

**Comment by Mikaela** [comment]
@fahadmehar try clearing your bindhost, `/msg *status setuserbindhost` or `/msg *status setbindhost`. If that doesn't help, give more details such as `/msg *status version` and output from `znc -D` showing the error.

Related: https://github.com/znc/znc/issues/241 as thanks to it people set 0.0.0.0 as bindhost.

**Comment by DarthGandalf** [comment]
It's `/msg *status clearbindhost`. 0.0.0.0 shouldn't be needed anymore.

**Comment by fahadmehar** [comment]
This is my Ver
<*status> ZNC 1.6.4 - http://znc.in
<*status> IPv6: yes, SSL: yes, DNS: threads, charset: no

**Comment by fahadmehar** [comment]
Please I really want to set VHost,

**Comment by fahadmehar** [comment]
How I fix this '? 

<*status> Disconnected from IRC (Server address is IPv6-only, but bindhost is IPv4-only). Reconnecting...

**Comment by fahadmehar** [comment]
I clear my binhost so many times even with soap its not working...

**Comment by psychon** [comment]
What server are you trying to connect to? Try something that also has an IPv4 address (dunno, some freenode server?)

**Comment by fahadmehar** [comment]
ON DALnet Server @psychon

**Comment by psychon** [comment]
Try 194.68.45.50 or 91.217.189.35 or 154.35.175.101 or 194.14.236.50 as server (random dalnet servers; however, I cannot find one with an IPv6-address; what server did you give ZNC to connect to?)

**Comment by fahadmehar** [comment]
My IP address is IPv6 and They said my bIndhost is IPv6 only? I don't understand this?

**Comment by psychon** [comment]
Pardon me, but my psychic abilities are having a bad day: Who is "they" and what exactly do "they" say? Any more specific error message from ZNC?
Why do you even still have a bindhost after `/msg *status clearbindhost`? That should unset any bindhost.

**Comment by fahadmehar** [comment]
Man, I want to use my VHOST which I set from www.freedns.afraid.org. On IPv6 Address. But when I set the BindHost I get this message

**Comment by psychon** [comment]
Uhm. That sounds more like ZNC's message is mixed up (is it?) and you are having an IPv6-bindhost, but DALnet does not have any IPv6 servers.
In that case, try `/znc addserver ipv6.dal.net` (or `/znc addserver 2001:550:101:a::2` and `/znc addserver 2a00:1a28:1100:4::a`)

**Comment by fahadmehar** [comment]
DALnet allow Ipv6 and on my ZNC panal i have put ipv6.dal.net server...

**Comment by fahadmehar** [comment]
And After setting my Vhost on afraid and i cant able to add Ipv6 Ip on my panal. It says Invalid Hostname.

**Comment by fahadmehar** [comment]
and it says my bindhost is ipv4 only 

Disconnected from IRC (Server address is IPv6-only, but bindhost is IPv4-only). Reconnecting...

**Comment by psychon** [comment]
> and it says my bindhost is ipv4 only
>
> Disconnected from IRC (Server address is IPv6-only, but bindhost is IPv4-only). Reconnecting...

But didn't you say that your bindhost is an IPv6 address?
Here: 

 > Man, I want to use my VHOST which I set from www.freedns.afraid.org. On IPv6 Address. But when I set the BindHost I get this message

I'm confused by your setup. And the use of "VHOST" confuses me further.
Can you tell me what you set up with freedns? (Which IP, which DNS name)

I think that you cannot use this to get a vhost...

**Comment by fahadmehar** [comment]
@psychon  OK I can explain... I purchase VPS ok and I setup my ZNC and after setting up my ZNC i try to set Vhost for ZNC which i did from www.freedns.afraid.org. I put my IPV6 ip and set my VHost i try to put that vhost on znc. I get this message...

**Comment by psychon** [comment]
The BindHost in ZNC just selects the IP address that ZNC connects from. If you only have a single IP address, the BindHost option doesn't have any effect.
Since you mention VHost: When the IRC server sees an incoming connection, it only sees your IP address. It then looks up the PTR record of that IP address to get a domain. Then it resolves that domain into an IP address. If the result matches the IP address of the incoming connection, the domain is used for display purposes instead of the IP address.
So, just setting up a new DNS record with freedns does not help, because you also need the PTR DNS record of the IP address (which you cannot control in most cases).

All of the above is why the option in znc is called BindHost and not VHost.

**Comment by fahadmehar** [comment]
@psychon  I think my VPS IP is Default IPV4 ? Maybe that's the issue?

**Comment by Doky1988** [comment]
IPV6 disable!!!

Copy:

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1

Edit: nano /etc/sysctl.conf

Paste and save!
and shutdown -r now

-------------------------------------------

ZNC configuration no write bindhost!

And work :)
