### ISSUE TITLE
Clone user results in network IRC nick that cannot be edited

### ISSUE THREAD

**Issue by pcolmer** [znc/znc#384]
When I clone an existing user, I reset the Authentication values and the IRC Information values and then click on Clone. When I then edit the user, the cloned network information shows "IRC Nick" as having a value that seems to be derived from the original user, e.g. my original IRC Nick is "philip_colmer" but the cloned IRC Nick is "philip_c-". That value does not seem to be editable, even if I edit the network of the cloned user and change all of the Network Info values.

The only solution seems to be to delete the network and add it back, but that rather defeats the purpose of cloning the user.

**Comment by jimpriest** [comment]
I've run into this as well.

* O User = Original user
* C User = Cloned user.

I clone the OUser.

When I look under CUser's networks I see "OUser" as the network 'name'.

If I edit the network and update all references of OUser to CUser and save, looking at the Networks list - the Network is still named "OUser" as is the IRC Nick which is confusing.

This can be seen in the URL as well:
https://my.url.com/mods/global/webadmin/editnetwork?user=cuser&network=ouser

Like previous posters - the only work around seems to be to delete the network and recreate it.

**Comment by aj701** [comment]
I've been getting this error as well, restarting the znc server works, but a bit of a pain.

**Comment by DarthGandalf** [comment]
Where are the details? What ZNC version?

**Comment by aj701** [comment]
So I was having the same error as the above user. I was cloning user accounts via the web interface, and no matter what individual changes I made to account info the irc nickname for the server under the cloned account would default to the original IRC alt nick information. Even when he irc nick was changed and saved over, all the writeable fields would reflect the irc nick as changed, yet the server info would still default to the  alt of the original account.

One solution is to delete the server and create a new one, another solution is to just run 'pkill znc' , then relaunch it from a terminal. When this is done all the changed information that was saved via the web interface takes effect and there is no sign of the old 'alt nick' on the cloned account.

This is running the most recent version of znc 1.6.1

**Comment by Mikaela** [comment]
Do you happen to use patched ZNC? There was some webadmin theme which required patching and has caused issues like this in the past, but I don't remember what it was called as.

**Comment by aj701** [comment]
Hi Mikaela,

I have encountered this error on multiple servers with the default znc theme as well as using the patched firrre theme. The problem and solution for both remained the same for me.

**Comment by Mikaela** [comment]
This should possibly also be mentioned here (separate issues removed for readability).

```
[20:32:47] <aj701> mikaela - did I just repsond to you on github? haha
[20:34:34] <Mikaela> if it was about patched znc, yes
[20:34:36] <Mikaela> hi
[21:06:15] <aj701> hi mikaela - it was about patched znc :)
[21:06:18] <aj701> how cool
[21:07:19] <Mikaela> I see
```

and firre was the theme name I didn't remember. How about you @jimpriest ?
