### ISSUE TITLE
Feature to log/notify of incoming CTCP requests, including those with custom replies

### ISSUE THREAD

**Issue by dgw** [znc/znc#390]
ZNC as it stands appears to offer no way for clients to know if e.g. a `CTCP VERSION` has been sent to them if the `VERSION` reply is overridden and handled by ZNC itself. Many IRC users, including myself, like to know when our clients are being interrogated, even if the "client" is ZNC.

Whether as a core function or a module, CTCP requests handled by ZNC ought to notify connected clients and/or the log and/or the channel buffer if the user wishes, on a per-network basis at the very least. This is not forwarding the requests themselves, but rather inserting a line in the chat as some popular IRC clients (e.g. X-Chat) do.

This notification/logging should include all common CTCP requests (`VERSION`, `PING`, `INFO`, etc.)—no incoming CTCP request should be filtered by default. (For my purposes, filtering is undesirable, but in the future someone may wish to define which CTCP types are notified to clients/logs.)

**Comment by DarthGandalf** [comment]
Looks like @Zarthus fixed this issue... Reopen if it's not the case.
