### ISSUE TITLE
ZNC doesn't respect symlinked config files

### ISSUE THREAD

**Issue by offbyone** [znc/znc#417]
If my ZNC config file in `~/.znc/configs/znc.conf` is a symlink to `~/dotfiles/znc/.znc/configs/znc.conf` -- which it is, if I use stow to manage the file -- then ZNC should respect the symlink I have, and write its configuration to the underlying real file, not to the symlink.

As it is, I have to copy and update the symlink each time I want to start ZNC, and as soon as I do that, it overwrites the symlink with a file.

**Comment by DarthGandalf** [comment]
> So, what are other parts which you put to that stow except znc.conf?

Silence...
