### ISSUE TITLE
Nick list ghosting after server jump on AndChat

### ISSUE THREAD

**Issue by TBBTNut** [znc/znc#424]
This seems to only apply to AndChat so far. Have now tested on PocketIRC (Windows Mobile 6.1), AndroIRC, and YaaIC too and none have reproduced this. I have a contact who uses IRC7 on Windows Phone 8 but he is too busy to test for me at the moment. I will now submit a bug report on the AndChat bug tracker site with a link to this bug page.

When channels are rejoined after reconnecting to the IRC server (jumping or reconnecting) the stale nicklist isn't cleared before the new one is added. This results in a double-length list, sometimes with users who are no longer in the channel (may have changed nick, parted/been kicked, or otherwise quit).

Please look into this as a lot of channels I'm in are invite-only, and there is no +I mode (invite-exception) on the NetGamers network.

![screenshot_2013-10-25-10-58-22](https://f.cloud.github.com/assets/5773088/1406950/06f75a7c-3d5e-11e3-9ea6-5f297e2d9256.png)
##

**Comment by Mikaela** [comment]
I believe this is invalid as it's AndChat issue and AndChat is discontinued.
