### ISSUE TITLE
AutoClearChanBuffer disabled on some channels randomly

### ISSUE THREAD

**Issue by RixzZ** [znc/znc#440]
Hi, I'm having an 'issue' with AutoClearChanBuffer option. I have it enabled on user settings but it disables itself in some channels.

If I check znc.conf when some channels disables this option, an 'AutoClearChanBuffer = false' appears on channel section.

Usually this happen to me in entire networks and sometimes only in a few channels.

I tried to configure it using webadmin, command or even editing znc.conf before start znc. Same in all cases.

**Comment by Mikaela** [comment]
I think this shouldn't happen with 1.6.0+ anymore (or at least no one has reported it) and this could possibly be closed.
