### ISSUE TITLE
Some Modules Are Listed in Different Areas

### ISSUE THREAD

**Issue by ZacharyDuBois** [znc/znc#583]
During `--makeconf`, Some modules are listed twice as different types. `webadmin` is listed as both a global module and user module. `chansaver ` is listed as both a user module and a network module. 

When `webadmin` is enabled at both the global and user level, a lot of the menu items in the panel are duplicated. This can be confusing to users (and possibly be a bug). If these are meant to be displayed on different levels, it should remove the option to enable it on a lower level. Ex: If I enabled `webadmin` on the global level, the user level should not contain it and vise versa.

There are a few others that are listed in different places:

- `log`
- `block_motd`
- `autoreply`
- A few others I might have missed.

```
[ ** ] -- Global Modules --
[ ** ] 
[ ** ] +-----------+----------------------------------------------------------+
[ ** ] | Name      | Description                                              |
[ ** ] +-----------+----------------------------------------------------------+
[ ** ] | partyline | Internal channels and queries for users connected to znc |
[ ** ] | webadmin  | Web based administration module                          |
[ ** ] +-----------+----------------------------------------------------------+
[ ** ] And 12 other (uncommon) modules. You can enable those later.
[ ** ] 
[ ?? ] Load global module <partyline>? (yes/no) [no]: yes
[ ?? ] Load global module <webadmin>? (yes/no) [no]: yes
[ ** ] 
[ ** ] Now we need to set up a user...
[ ** ] 
[ ?? ] Username (AlphaNumeric): Zachary 
[ ?? ] Enter Password: 
[ ?? ] Confirm Password: 
[ ?? ] Would you like this user to be an admin? (yes/no) [yes]: yes
[ ?? ] Nick [Zachary]: Zachary_DuBois
[ ?? ] Alt Nick [Zachary_DuBois_]: themacproguy    
[ ?? ] Ident [Zachary_DuBois]: Zachary_DuBois
[ ?? ] Real Name [Got ZNC?]: Zachary DuBois
[ ?? ] Bind Host (optional): 
[ ?? ] Number of lines to buffer per channel [50]: 75
[ ?? ] Would you like to clear channel buffers after replay? (yes/no) [yes]: yes
[ ?? ] Default channel modes [+stn]: +stn
[ ** ] 
[ ** ] -- User Modules --
[ ** ] 
[ ** ] +--------------+------------------------------------------------------------------------------------------+
[ ** ] | Name         | Description                                                                              |
[ ** ] +--------------+------------------------------------------------------------------------------------------+
[ ** ] | chansaver    | Keep config up-to-date when user joins/parts                                             |
[ ** ] | controlpanel | Dynamic configuration through IRC. Allows editing only yourself if you're not ZNC admin. |
[ ** ] | perform      | Keeps a list of commands to be executed when ZNC connects to IRC.                        |
[ ** ] | webadmin     | Web based administration module                                                          |
[ ** ] +--------------+------------------------------------------------------------------------------------------+
[ ** ] And 21 other (uncommon) modules. You can enable those later.
[ ** ] 
[ ?? ] Load module <chansaver>? (yes/no) [no]: no  
[ ?? ] Load module <controlpanel>? (yes/no) [no]: yes
[ ?? ] Load module <perform>? (yes/no) [no]: yes
[ ?? ] Load module <webadmin>? (yes/no) [no]: 
```

**Comment by Mikaela** [comment]
As ZNC 1.6.0 is released, shouldn't this issue be closed?

> I understand but things like webadmin, should not be both on the network and user level.

It makes no sense and is weird.

* global level = webadmin is loaded and all users can login
* user level (but not global) = webadmin is loaded and only that user can loginn

*I assume you meant global and user with network and user.*

**Comment by ZacharyDuBois** [comment]
What I meant is people can enable webadmin on both the global and user level. Try it and see what happens.

**Comment by Mikaela** [comment]
Nothing happens. When it's loaded globally, all users can login into it, when loaded user level, only the user can login. When both, the global module takes preference, I think.

**Comment by ZacharyDuBois** [comment]
The issue I had is it basically creates a duplicated web interface. I will test this when I get home.

**Comment by Mikaela** [comment]
That is because it's global and user level module.

**Comment by ZacharyDuBois** [comment]
Yes, but there should be a way to disable conflicting plugins like that. IIRC, I had issues with many modules if they were to be enabled under two levels for the same user. I guess what I am trying to say is that several modules should be restricted to being enabled on only one level.

**Comment by Mikaela** [comment]
>  I guess what I am trying to say is that several modules should be restricted to being enabled on only one level.

I think separate issue should be opened about that as someone looking for that won't find it here when browsing issue lists.

**Comment by ZacharyDuBois** [comment]
Will do when I get home.
