### ISSUE TITLE
Fix build of ZNC with LibreSSL

### ISSUE THREAD

**Issue by brad0** [znc/znc#594]
Here is a patch from the OpenBSD ports tree to fix the build of ZNC against LibreSSL.

http://openbsd.comstyle.com/cgi/cvsweb/ports/net/znc/patches/patch-src_Csocket_cpp?rev=1.1&content-type=text/x-cvsweb-markup

**Comment by Sp1l** [comment]
Created https://github.com/jimloco/Csocket/pull/49 to fix build with LibreSSL.

Saw that the tarball does not include Csocket.cpp, imagine that this is included with some build script?

**Comment by DarthGandalf** [comment]
Both release and nightly tarballs include it...

**Comment by Mikaela** [comment]
> Saw that the tarball does not include Csocket.cpp, imagine that this is included with some build script?

GitHub tarballs don't include submodules and thus are broken and they shouldn't be used.

**Comment by Sp1l** [comment]
Sorry, meant to say the GitHub repo does not include Csocket.cpp yet the tarball does

**Comment by Mikaela** [comment]
It's submodule which you should be able to find at https://github.com/znc/znc/tree/master/third_party but all changes to it belong to where you already went.
