### ISSUE TITLE
Support STARTTLS between ZNC and server. [$10]

### ISSUE THREAD

**Issue by Cronus89** [znc/znc#604]
After a few days of researching, I've found out that ZNC while it does act on the numeric for STARTTLS.

It actually never sends the "STARTTLS" Command to start the connection.  If the server reports "tls" in CAP LS, znc should send "STARTTLS" to the IRC server and then the IRC server will respond with the raw numeric and znc should in theory finish it from there.
##

**Comment by md-5** [comment]
> because we can't really make sure that nothing else sends anything between STARTTLS and the reply to STARTTLS.

Other clients must be able to handle this.

**Comment by DarthGandalf** [comment]
@md-5 ZNC is the client in this case. Perhaps need a separate bug for the other side.

**Comment by md-5** [comment]
@DarthGandalf my point being, STARTTLS must be possible, otherwise it wouldn't exist. ZNC just needs the necessary changes :)

**Comment by kylef** [comment]
Given the tls spec which contains the STARTTLS command is deprecated, perhaps this feature request should be closed.

As per https://ircv3.net/specs/extensions/tls-3.1:

> This specification has been deprecated. We do not recommend implementing this specification or the features described here.

> This extension has been deprecated in favour of encouraging IRC networks to use implicit TLS and deploy Strict Transport Security instead. This is in alignment with the recommendations given in RFC 8314.

**Comment by DarthGandalf** [comment]
Probably something else is missing?

Note that STARTTLS support was never finished, so it's not supported. Feel free to debug it though. But even if you manage to make it work, we probably won't accept the patch, due to this in the spec:

> We do not recommend implementing this specification or the features described here.
