### ISSUE TITLE
ZNC doesn't listen on v4

### ISSUE THREAD

**Issue by Thermi** [znc/znc#640]
Hello,

I restarted my vServer today and since then ZNC doesn't listen on 0.0.0.0/0:1337 anymore, just :::1337.
IPv4 and IPv6 are active in znc.conf. The kernel version is 3.16.1-1-ARCH and the ZNC version is 1.4.
This is the config snippet:
<Listener listener0>
        AllowIRC = true
        AllowWeb = true
        IPv4 = true
        IPv6 = true
        Port = 1337
        SSL = true
</Listener>

Starting znc with -D doesn't show any errors.
It shows "[ .. ] Binding to port [+1337]...
[ >> ] ok
" though.

Regards,
Thermi

**Comment by wlhlm** [comment]
Hi, I'd like to mention, that I'm affected by this as well using znc 1.6.2

I'm using a `Host` directive, which has DNS entries for both IPv4 and IPv6. znc will only open a v6 socket and I'm not able to connect using v4. I'd like to be able to connect using both protocols. IPv6 has proven to be more reliable for me, but unfortunately is not available everywhere (not on my 3G network for example), so I'd like to still be able to connect via v4.

**Comment by DarthGandalf** [comment]
If you just remove the `Host`, it will start listening on both.

**Comment by supine** [comment]
I just hit this problem except there was no "host" set in my listener config.

I've worked around it by making two listeners, one IPv4 specific and one IPv6 specific, like @Thermi did in https://github.com/znc/znc/issues/640#issuecomment-53608391

**Comment by mwt** [comment]
I have this issue as well.
