### ISSUE TITLE
znc not entering channels using key after quick reconnect

### ISSUE THREAD

**Issue by Nihim** [znc/znc#674]
Debian 7 & znc 1.4

In znc the channels keys appear set. If I disconnect and connect znc enters the channels properly but if it reconnects quickly (by a kill for example) it throws errors that it couldn't join them and that they are now disabled.

If I just go ahead and rejoin them, it enters them normally using the key and all.

Any suggestions on how I could force znc to use the key in any scenario or how I can provide more information about this problem?

**Comment by Mikaela** [comment]
Does this still happen to you on 1.6.0 or could this be closed?

**Comment by Nihim** [comment]
As far as I can recall no it hasn't happened since 1.6.0.

**Comment by kyrias** [comment]
I'm still experiencing this.
