### ISSUE TITLE
There is no CONTRIBUTING file

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#708]
Link there appears always when you are opening an issue or pull request.

* https://github.com/blog/1184-contributing-guidelines

It could say something about [Debugging](http://wiki.znc.in/Debugging) and mentioning ZNC & OS versions etc. and probably something related to coding too.

**Comment by Zarthus** [comment]
Would be nice to know what kind of coding style I should use, line endings, and in general if small pull requests are worth sending in instead of just making a new issue.

**Comment by Mikaela** [comment]
The ones that I have noticed are

* Unix line-endings
* Tabs, no spaces as tabs

**Comment by Zarthus** [comment]
aye, but it'd be easier for pull requests to be more compliant if there is an official venue stating all these things, rather than having to dig all this info by yourself.

**Comment by jpnurmi** [comment]
The rule of thumb is to follow the exact same conventions and style of the
file you change. Applies to any project. :)
