### ISSUE TITLE
Channel Key's being dropped.

### ISSUE THREAD

**Issue by supawiz6991** [znc/znc#709]
ZNC 1.4

When a disconnect occurs ZNC is dumping all channel keys. I then have to go and put the keys back in and then disconnect and reconnect my user from irc by uncheck/save then check/save "Connect to IRC & automatically re-connect" option.

This issue is really annoying and frustrating. Any thoughts on why this is occurring?

**Comment by Mikaela** [comment]
@supawiz6991 this is fixed with ZNC 1.6.0 and the current version is 1.6.1. Does this still affect you?

**Comment by jpnurmi** [comment]
Please leave a comment if the problem persists.
