### ISSUE TITLE
Switch to a modern build system [$30]

### ISSUE THREAD

**Issue by jpnurmi** [znc/znc#712]
Please switch to a modern and maintainable build system. I don't care which exact build system it is, as long as it doesn't involve 90's style hand-written makefiles. I've proposed CMake (https://github.com/znc/znc/pull/648) in the past.

> Switching to a modern, understandable, readable and maintainable build system is an important step for striving toward a stable module API (http://wiki.znc.in/Ideas). If you ask me, the library split is essential to get even started (with Autotools I'm not even going to try, sorry). The goal is to have control over exported symbols, which helps to avoid the necessity of rebuilding all modules after every upgrade. It's a long and dusty road to get there, but the benefits should be pretty evident.

**Comment by benapetr** [comment]
I absolutely agree with brad0 python is not everywhere, and linux is not UNIX, there is a number of other NIXes out there like HP-UX and those almost never heard word "python" I could try to help set up CMake I've done that multiple times for mid-sized projects (400+ source code files, multiple targets, libs etc)

**Comment by jpnurmi** [comment]
In the end, it's all about the convenience of ZNC development. Switching to a modern build system goes in the same category with C++11. Not strictly needed, but simply makes the lives of ZNC developers easier. While not necessarily _directly_ benefiting the users, this kind of changes are the ones that pave the road for new amazing ZNC features. Happy developers tend to be more creative than frustrated ones.

> I could try to help set up CMake

Been there, done that... #648

To me, personally, http://www.cmake.org/Wiki/CMake_Editors_Support (*) alone would be worth the change. I use Qt Creator for all my development work. CMake support would give me a proper project tree.

*) seems to be missing CLion so add that promising C++ IDE on the list

**Comment by DarthGandalf** [comment]
> Switching to a modern build system goes in the same category with C++11

Well, not exactly the same, but almost.

> Happy developers tend to be more creative than frustrated ones.

I agree.
And every time I needed to change something in the build system (especially, in Makefile part), I've been very unhappy, and ended up with various ugly hacks.
