### ISSUE TITLE
Provide infrastructure to write tests for a module

### ISSUE THREAD

**Issue by kylef** [znc/znc#771]
Perhaps something like the following:

``` bash
$ znc-testmod <module.cpp> <*moduletests.cpp>
```

Expecting the modules use gtest like ZNC, it would compile the module and the tests and run them together with ZNC linked to the module.

Perhaps also providing some form of API for the tests to ease loading the module configured globally, as network or as a user.
##

**Comment by DarthGandalf** [comment]
Does existing integration tests (`make install && make test2`) satisfy this?
It tests several modules.
