### ISSUE TITLE
Why does ZNC ship with *NickServ and *Q?

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#786]
As far as I am aware, *q is only supported on Quakenet and nowadays there aren't many networks that have NickServ, but don't support SASL. I am only able to name two (OFTC has *cert though) networks where there is NickServ without SASL, but *NickServ module didn't even to do anything there. I think they used HybServ2.

It looks to me like they could be external modules.

Update: according to #znc at freenode, there are multiple networks with NickServ, but without SASL. *perform would probably work as well with them though.

> synIRC, dalnet, YourBNC, Rizon, Swiftirc, SlashNet - They all don't support sasl,  but have nickserv
##

**Comment by DarthGandalf** [comment]
> Is the Q module still maintained? #554 is something I reported a long time ago and still seems to be in znc 1.4.

Apparently, it's not. @ahf ping?
Dropping Q module (aka making it external, and letting ahf to maintain it outside of ZNC repo) would solve this issue, and will help with #1494

**Comment by ahf** [comment]
I have completely overlooked #554. I'm not using the Q module anymore and I'm hardly active on Quakenet either.

I could take a look at #554 during the upcoming week. I don't think I'm the right person to take the decision if the Q module should be maintained externally, internally, or dropped -- I don't know how many znc users that are using it. If #554 is the "only" issue right now I don't see why it would make sense to remove it though. It's not like the Quakenet development community releases early and often! :-)

**Comment by dgw** [comment]
Or roll the Q module into #1496? As long as modules are being consolidated, why not?

**Comment by DarthGandalf** [comment]
> why not?

Because Q is useful on a single network, while sasl and nickserv are useful much more widely. But every single piece of code is an additional burden for maintenance.

**Comment by ahf** [comment]
I also don't think it's a good idea to merge it into a module that tries to standardise the authentication schemes used on the more up-to-date networks. To put it bluntly, I personally think the Quakenet authentication scheme should be avoided. I hope nobody else is using it.

**Comment by DarthGandalf** [comment]
> I don't know how many znc users that are using it.

Without ZNC sending us its usage stats, it's really hard to tell.

> I don't think I'm the right person to take the decision if the Q module should be maintained externally, internally, or dropped

I didn't drop it before because you wanted to look after this module and had a strong opinion on having it in ZNC repo. I'll drop it after 1.7 then, which is exactly the same as making it external - it's only a matter of updating URL to the "fresh" version [here](https://wiki.znc.in/Q)

**Comment by ahf** [comment]
Cool, thank you! Sounds good to me.

**Comment by DarthGandalf** [comment]
I haven't noticed this is still open after #1653
