### ISSUE TITLE
Support STARTTLS between clients and ZNC

### ISSUE THREAD

**Issue by DarthGandalf** [znc/znc#801]
#604 is for ZNC→server
##

**Comment by kylef** [comment]
Given the tls spec which contains the STARTTLS command is deprecated, perhaps this feature request should be closed.

As per https://ircv3.net/specs/extensions/tls-3.1:

> This specification has been deprecated. We do not recommend implementing this specification or the features described here.

> This extension has been deprecated in favour of encouraging IRC networks to use implicit TLS and deploy Strict Transport Security instead. This is in alignment with the recommendations given in RFC 8314.
