### ISSUE TITLE
savebuff: query buffers are not saved and loaded

### ISSUE THREAD

**Issue by jpnurmi** [znc/znc#802]
See @xor-freenet's comments in https://github.com/znc/znc/commit/287a020d21ec5f4798d3df845826e8c103a1225d. Despite the blind changes applied in the commit, query buffers are not actually saved and loaded at all.

- OnIRCConnected() incorrectly assumes that queries would already exist
- SaveBuffersToDisk() is missing handling of queries altogether

**Comment by jpnurmi** [comment]
Two ideas come to my mind. Either save the list of queries separately or change the storage format so that query names can be easily restored out of the encrypted files. With the latter, backwards compatibility must be kept in mind.

**Comment by jpnurmi** [comment]
Furthermore, storing the buffer name is not enough because at the time OnIRCConnected() gets called (RPL_WELCOME=1) we don't know yet which names are channels (RPL_ISUPPORT=5) and which are queries.

**Comment by jpnurmi** [comment]
@xor-freenet, fix available for testing: https://github.com/znc/znc/pull/803

**Comment by xor-freenet** [comment]
@jpnurmi I'm very busy with my own projects, so I would like to ask if this will get merged even if I don't provide testing? If you insist I can test it, but I'd rather not like to.

**Comment by xor-freenet** [comment]
And thanks! :)

**Comment by jpnurmi** [comment]
Hi, as a contributor I can't give any promise on behalf of the ZNC team. The best you can do to help is to verify that it works. It's a complex change - being verified by a third party is naturally more convincing than me saying "works for me". :)
