### ISSUE TITLE
Webadmin 403 After Login

### ISSUE THREAD

**Issue by ChristianGaertner** [znc/znc#805]
I've setup webadmin for znc; everything works as aspected. But I didn't hit that logout button after I used the panel.
Now my ip has cycled (by the provider every 24h) and when I try to login in now it returns a 403 error: __This session does not belong to your IP.__

Is there an easy way to gain back access to the account, without restarting znc?

Cheers,

Christian

P.S.

I know that this is a security feature, and you can turn it off; however if a user provides the correct username and password, why should znc lock the user out, when connecting from another IP? I mean if the attacker has the password, he could connect via IRC as well... Not sure if this lockout is bug or feature...

**Comment by wolfy1339** [comment]
Have you set a value in Allowed IP's?

**Comment by ChristianGaertner** [comment]
No, all IPs are allowed. (Wildcard)

**Comment by Cajs** [comment]
Normally refreshing the page will then log you out and your free to log in?

**Comment by ChristianGaertner** [comment]
Mhh, ok I thing I've found the problem...
When logging in with another computer it doesn't work, but with the same it works perfectly.
Seems like a bug to me anyway... Why should you just be able to be logged in from one computer...

I switch from Desktop to Laptop quite often...

**Comment by DarthGandalf** [comment]
There's no such restriction. Do you somehow share cookies between computers?

2015-01-05 13:10 GMT+00:00 Christian Gärtner <notifications@github.com>:

**Comment by ChristianGaertner** [comment]
No, I'm sure that Chrome doesn't share them between devices.

**Comment by Mikaela** [comment]
> Is there an easy way to gain back access to the account, without restarting znc?

Can you access ZNC using IRC client? `/msg *status saveconfig`, change `ProtectWebSessions = true` to `ProtectWebSessions = false` in `~/.znc/configs/znc.conf` (you might want to take backup of this file and ensure that you change nothing else than this line) and then `/msg *status rehash`

This is just workaround and I am not sure if I would recommend this.

**Comment by ChristianGaertner** [comment]
I've got access already back, by logging in from my desktop computer.

But I think it is a bit annoying to always log out, if I want to switch computers.

**Comment by Mikaela** [comment]
The same option is also in webadmin global settings (`Protect Web Sessions: Disallow IP changing during each web session`.)

**Comment by ChristianGaertner** [comment]
Ok thanks.
