### ISSUE TITLE
controlpanel: command 'delserver'.

### ISSUE THREAD

**Issue by hypech** [znc/znc#810]
Is there any plan to create the command 'DelServer' on controlpanel module?
There's 'AddServer' but there isn't a command to delete IRC servers.

Thanks.

**Comment by jpnurmi** [comment]
*status has a DelServer command

**Comment by dgw** [comment]
*status lets you DelServer for your current network only, if I'm not mistaken. Adding it to *controlpanel would allow managing other users' servers if they're having trouble.

**Comment by hypech** [comment]
Yep. It's for removing other users' servers. It's currently possible to add a new server to an user on controlpanel but it's not possible to remove them.
