### ISSUE TITLE
autoop-module: no case-sensitive

### ISSUE THREAD

**Issue by fred0r** [znc/znc#822]
pls fix that the users hostmask is case-sensitiv

**Comment by teward** [comment]
Why should the users hostmask be considered case-sensitive when using the autoop module?

It makes no sense why case-sensitivity should matter - many IRC networks' vhosts/cloaks won't be 'case sensitive' enough to be an issue (in most networks), and rDNS lookups usually return as lowercase.

So back to my question, what's your reasoning here?  (Also, use *real english*, not shorthand and crap.)

**Comment by fred0r** [comment]
if the users ident changes from 'username@...' to 'Username@...' the users added host is not recognized anymore.

**Comment by Mikaela** [comment]
Ah, so the issue is really that it should be case-insensitive. I think it is that, which version are you using? You can check with `/msg *status version` or running `znc --version` in terminal.

**Comment by fred0r** [comment]
ZNC 1.5-nightly-20140724-8a5e7ef8

**Comment by jpnurmi** [comment]
The module seems to use case sensitive CString::WildCmp(). Sprinkling some AsLower() calls somewhere around HostMatches() should help.
