### ISSUE TITLE
UTF-8 logs

### ISSUE THREAD

**Issue by davout** [znc/znc#826]
When outputting my logs with cat some special characters are replaced with '?', for example characters with accents.

When I manually prepend the UTF-8 BOM to the log file, cat displays all characters properly.

**Comment by kerio92** [comment]
Fix your terminal.

**Comment by davout** [comment]
I have the following environment variables set to 
````
LANG=fr_FR.UTF-8
LC_CTYPE=fr_FR.UTF-8
````

The file utility reports a `ISO-8859 text` file type.

Not saying that my terminal doesn't need fixing and that the issue is with ZNC, trying to get a correct understanding of the issue.

**Comment by Mikaela** [comment]
I see this happening when I try to open logs written by ZNC in GUI text editor, but no issues with terminal ones or cat.

**Comment by davout** [comment]
@Mikaela I reproduced it with vim until I forced the text encodings to UTF-8

**Comment by kerio92** [comment]
`cat` only deals with bytes, it doesn't do any encoding, so LANG and LC_* are not relevant here - your terminal isn't parsing UTF-8 correctly without a BOM, maybe?

**Comment by DarthGandalf** [comment]
Which ZNC version? In 1.5/1.6b you can configure client and server encodings, and they will be applied on those borders, while internally it's UTF-8 everywhere.

**Comment by davout** [comment]
Looks like it's ZNC 1.2
So that doesn't look like a real issue if up-to-date versions allow for encoding diddling.
Thank you for your answers !
