### ISSUE TITLE
Trusted SSL fingerprints of this IRC network help text looks bad

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#828]
![screenshot](http://i.imgur.com/lEGFe7N.png)

As you can see, "When these" is on top ríght, while the rest is under the box where everything should probably be.

ZNC - 1.5.0-git-542-7b1133d - http://znc.in
IPv6: yes, SSL: yes, DNS: threads, charset: yes

I know that this is not the latest commit, but I cannot see any [commit message](https://github.com/znc/znc/commits) hinting that this has been fixed.

**Comment by Mikaela** [comment]
Another issue is that maybe the `,` in the end should be `and`.

> When these certificates are encountered, checks for hostname, expiration date **and** CA are skipped

**Comment by dgw** [comment]
Indeed, this hasn't been touched since 7b1133d (ref. [blame view for the tmpl file in question](https://github.com/znc/znc/blame/5608e4f201caef33de4c79a0b7842709ccf0360a/modules/data/webadmin/tmpl/add_edit_network.tmpl))

**Comment by teward** [comment]
Okay, so I have a dirty solution unfortunately...

https://github.com/teward/znc/commit/7ad60cf6345ee818b55fd6278a62f1c1c203a8b3 details a change that makes it look like this: 
![znc-fixed-perhaps](https://cloud.githubusercontent.com/assets/327952/6194942/39b4859c-b397-11e4-89ef-1746403aeea1.png)

Thoughts?

**Comment by Ennea** [comment]
I think the general markup and styles should be redone for all of these labeled config lists, as the current design is prone to errors in general. I realize this goes beyond the scope of this issue, but I wanted to throw that in regardless.

**Comment by teward** [comment]
@Ennea I totally agree.  In my pull req #859 I even mention the changes I made there are just a bandaid and a overhaul needs to be done.  Bandaid fixes won't fix everything, the CSS and markup and styling should be redone, but compatibility with the other themes does have to be kept.  `_default_` is the only one with this failing right now as defined here.
