### ISSUE TITLE
Provide up to date / officially supported packages

### ISSUE THREAD

**Issue by md-5** [znc/znc#835]

**Comment by DarthGandalf** [comment]
Why?

**Comment by md-5** [comment]
It would be a nice thing to have :)

**Comment by DarthGandalf** [comment]
We already provide up to date officially supported tarballs in http://znc.in/releases and http://znc.in/nightly

**Comment by Mikaela** [comment]
I think that what is being asked is Debian/redhat7etcc. packages.

**Comment by jpnurmi** [comment]
ZNC switched to [semantic versioning](http://semver.org), and maintains a separate stable (bug fix) branch. Distributions no longer need to try to find ways to port bug fixes on top of the latest release. It is handled by the project members. This should make it trivial for distributions to offer up-to-date packages. The first ever bug fix -only release aka 1.6.1 was released last month.
