### ISSUE TITLE
controlpanel: add something like $me for current network

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#847]
>  You can use $me as the user name for modifying your own user.

But there is nothing for current network. There could be `$current`. It would make configuring same settings on multiple servers easier with `/allserv`.

**Comment by GLolol** [comment]
Would `$network` make more sense (or is that already taken)?

**Comment by Mikaela** [comment]
It could, no idea if it's taken.

**Comment by teward** [comment]
It looks like this has been completed and merged in via #900

**Comment by Mikaela** [comment]
Yes, it looks like @jpnurmi forgot to say "fixes" or "closes" in fromt of #847.
