### ISSUE TITLE
[feature] Keep the detached channel settings per client

### ISSUE THREAD

**Issue by farcaller** [znc/znc#848]
For users with a number of high-traffic channels it might make sense to have all the channels attached on desktop, but keep the list to bare minimum on mobile devices (possibly using with plugins that reattach on activity). That will allow more effective mode of operations on mobile clients due to much lower traffic.

**Comment by jpnurmi** [comment]
There's a module for that: http://wiki.znc.in/Chanfilter (requires znc 1.6)

**Comment by DarthGandalf** [comment]
Alternatively, you can setup several per-client users, as described at http://wiki.znc.in/FAQ#How_to_store_private_messages_even_when_user_is_attached.2C_so_other_clients_can_see_them.3F

**Comment by Mikaela** [comment]
> 

Alternatively, you can setup several per-client users, as described at http://wiki.znc.in/FAQ#How_to_store_private_messages_even_when_user_is_attached.2C_so_other_clients_can_see_them.3F

If you do this, you should be aware of https://github.com/znc/znc/issues/839 which means that you will stll see added timestamps if your client supports server-time and if it doesn't support that, you will see timestamps twice in buffer playback.

**Comment by DarthGandalf** [comment]
@Mikaela why? Client users are always connected to the main user, so main user doesn't need to have any buffer itself, it just redirects all messages to client users, so it doesn't have much chance to add timestamps into message text. Also if you still afraid of getting second timestamp, you can always set both `PrependTimestamp` and `AppendTimestamp` to `false`.

**Comment by Mikaela** [comment]
I think this was discussed at freenode on \#znc some time ago.
