### ISSUE TITLE
webadmin client cert auth

### ISSUE THREAD

**Issue by kyrias** [znc/znc#855]
The webadmin already asks for a client certificate when you connect using SSL, so I thought it would be cool if you could use the same certificate as with IRC cert auth as a SSL client certificate in the webadmin panel, or alternatively changing it so it doesn't ask for one if not possible.

**Comment by kerio92** [comment]
You can.

**Comment by kyrias** [comment]
How?

**Comment by kyrias** [comment]
Ah well crap, seems I failed when testing it. Sorry for the noise.

**Comment by TheFrozenFire** [comment]
For posterity:

    openssl pkcs12 -export -in user.pem -out user.p12

Then, in Chrome, go to Settings, Show Advanced Settings, HTTPS/SSL, Manager Certificates. Import the newly-created PKCS#12 file.

When you visit your ZNC web interface it should prompt you to choose the certificate for identification. Then, you can enter your username with a blank password and log in (as you would specify a blank password for IRC authentication).

If someone else wents to pipe up regarding FireFox instructions, please do.

**Comment by Mikaela** [comment]
What I usually do is:

```
openssl req -nodes -newkey rsa:4096 -keyout Mikaela.pem -x509 -days 3650 -out Mikaela.pem -subj "/CN=Mikaela"
```

and if I recall correctly both Chrome and Firefox accept the pem file directly.
