### ISSUE TITLE
TLS certificate validation should work with SHA-1 fingerprints too

### ISSUE THREAD

**Issue by dgw** [znc/znc#867]
Since upgrading to ZNC 1.6.0, I've been looking for server fingerprints on networks' websites. It seems that most are provided as SHA-1. It would be logical for ZNC to accept the more common representation of certificate fingerprints, _especially_ if #866 never happens.
##

**Comment by Mikaela** [comment]
MD5 and SHA-1 are **deprecated**, so accepting them would be a bug.

I personally have this bash/zsh function

```bash
# Get server SSL certificate fingerprint in MD5, SHA1 and SHA256.
# Note that OpenSSL doesn't support IPv6 at time of writing (2015-01-13).
serversslcertfp() {
    SSSLCFFN="/tmp/$(date -Is).pem"
    openssl s_client -showcerts -connect $1 < /dev/null|tee $SSSLCFFN
    cat $SSSLCFFN|openssl x509 -md5 -fingerprint -noout
    cat $SSSLCFFN|openssl x509 -sha1 -fingerprint -noout
    cat $SSSLCFFN|openssl x509 -sha256 -fingerprint -noout
    rm $SSSLCFFN
}
```

**Comment by Mikaela** [comment]
I would also close this.
