### ISSUE TITLE
Playback freezing on 1.6.0 on OS X

### ISSUE THREAD

**Issue by billstanden** [znc/znc#871]
Hi there,
    Upgraded from 1.4 to 1.6.0 on my Mac server via homebrew and I'm now getting playback freezing when a client connects.

Clients gets about 1/5th of the way through a quite large playback set (~30 channels, 1500 lines) and then sits there with no additional updates from the ZNC server.

Generated a fresh config with no change in behaviour.

User options are:

```
LoadModule = chansaver
LoadModule = controlpanel

MaxJoins = 15
Buffer = 1500
MultiClients = true
AutoClearChanBuffer = false
```

Reverting to 1.4 immediately resolves the issue.
##

**Comment by Mikaela** [comment]
> Buffer = 1500

is probably the issue.

**Comment by billstanden** [comment]
Possibly.  Seems to occur even when those buffers aren't close to full though and it's been flawless on 1.4

Agree it's perhaps an "ambitious" configuration.

**Comment by Ttech** [comment]
This seems exactly like the issue I have been getting for a while now, no matter the buffer size it still hangs.

**Comment by jpnurmi** [comment]
Which clients are you using? Is SSL enabled? "A fresh config with no change in behaviour" means no other modules in addition to the defaults loaded, right?

I've been testing with a buffer size of 1500, ZNC joined to 30 (some of the largest according to irc.netsplit.de) channels on Freenode. No troubles so far...

**Comment by billstanden** [comment]
Client doesn't seem to matter.  I get the same results with mIRC, Hexchat, Colloquy (OS X and iOS), Limechat iOS and Textual.

SSL is on.  No other modules apart from defaults.

**Comment by DarthGandalf** [comment]
If you disconnect client, and connect again, what happens?
Also try to run znc -D

2015-02-22 14:59 GMT-08:00 Bill Standen <notifications@github.com>:

**Comment by billstanden** [comment]
Disconnecting the client almost always results in a freeze at near the same point in playback, usually only a few lines different.

I'll give znc -D a shot at my next opportunity

**Comment by billstanden** [comment]
Is there any logical reason running with znc -D would cause this issue not to present?  Perhaps just a slow down in processing?

Twice now I've switched to znc -D and been unable to replicate the problem with the buffers set back to 1500.  Revert to a normal run of just znc and the problem returns once the buffers have time to fill.

**Comment by DarthGandalf** [comment]
Alternatively, wireshark may help, if znc -D changes the behavior...

**Comment by jpnurmi** [comment]
Thanks for the tip. Of course I was running with -D all the time to see what's going on. :)

If you use a client such as irssi that does not support server-time cap, you get a ```<***> Buffer Playback...``` message, but not the ```<***> Playback Complete.``` message on one of the channels and then no playback at all on the "rest" of the channels? Or how does it freeze?

**Comment by jpnurmi** [comment]
Could you paste the output of ```otool -L /path/to/bin/znc```?

**Comment by Mikaela** [comment]
Waiting for information for months, could it be assumed this issue has fixed itself?
