### ISSUE TITLE
1.6.0: when no networks are defined webadmin says that all network modules are loaded by network

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#872]
run `znc --makeconf` and say "no" to creating network. Now go to webadmin and all checkboxes that say what levels the module is loaded on say that all modules that can be loaded on network level are loaded (while there are no networks).

**Comment by jpnurmi** [comment]
Seems to have been that way ever since the checkboxes were added in https://github.com/znc/znc/commit/4338ae5cc521a5348a4dfc9574d05cd33e12bfa0.
