### ISSUE TITLE
ZNC not saving module settings to config files

### ISSUE THREAD

**Issue by l3mde** [znc/znc#885]
Problem i have been struggling for a while now. As i understand, ZNC keeps the configuration in memory. To store it to the on-disk config file you have to trigger a SIGUSR1 on the process.

This works fine for the main znc config, but the config for all loaded modules is not affected by this. So all settings for the modules are gone after restarting the service, rebooting, etc.

Version in use: ZNC 1.4 from EPEL7 repository on CentOS7.

**Comment by Mikaela** [comment]
You can either use webadmin or `/msg *status saveconfig`.

> Version in use: ZNC 1.4 from EPEL7 repository on CentOS7.

As far as I am aware, ZNC doesn't support 1.4 anymore as 1.6.0 is released.

**Comment by DarthGandalf** [comment]
Which exact module are you talking about? Most modules save their own
settings immediately, even without any /msg *status saveconfig

2015-02-24 6:41 GMT-08:00 Mikaela Suomalainen <notifications@github.com>:

**Comment by Kriechi** [comment]
At least for the stickychan module there is PR #881 which basically adds "more automated saving".
@moodydeath could you mention a specific module you are having problems with?

**Comment by l3mde** [comment]
Sorry for the late response,

unfortunatelly did not have time to do more extensive testing on 1.4. (and won't do any help as it is not supported anymore)

Got 1.6 from EPEL7 repository a few days after reporting the bug.

No complaints from anyone on the server since then. Commonly used modules like 'simple_away', 'stickychan', 'autoop', 'autovoice', 'perform', etc. are active.
