### ISSUE TITLE
[META] leave EFnet and only have official channel at freenode?

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#895]
ZNC implements IRCv3 and is part of the IRCv3 working group. EFnet again doesn't do either and the EFnet channel has far less people and is far less active than the freenode channel. Currently both are official though.

* https://github.com/ircv3/ircv3-specifications/blob/master/index#L15-31 (ZNC is on line 31)
* https://github.com/ircv3/ircv3-specifications/blob/master/index#L106-122 (ZNC is on 122)

**Comment by jpnurmi** [comment]
Does it matter if it's official or not? Currently 215 users on EFnet vs. 850 users on Freenode.

**Comment by Mikaela** [comment]
I think it can be found confusing to be officially on two places that have nothing to do with each other. For example Supybot is officially on both freenode and OFTC and there is bot relaying those two channels. Almost everyone is at freenode, but there are some original developers at OFTC.

**Comment by Mikaela** [comment]
> To create new wiki account, please join us on #znc at freenode **or efnet** and ask admins to create a wiki account for you. You can say thanks to spambots for this inconvenience.

Says [the wiki](http://wiki.znc.in/ZNC) when you aren't identified.

**Comment by DarthGandalf** [comment]
22.04.2015 21:01, Mikaela Suomalainen пишет:
>
>     To create new wiki account, please join us on #znc at freenode *or
>     efnet* and ask admins to create a wiki account for you. You can
>     say thanks to spambots for this inconvenience.
>
> Says the wiki <http://wiki.znc.in/ZNC> when you aren't identified.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/znc/znc/issues/895#issuecomment-95319756>.
>
Oops, missed it. Thanks
