### ISSUE TITLE
Trusted SSL fingerprints in webinterface show up in one single line

### ISSUE THREAD

**Issue by hashworks** [znc/znc#911]
![example](http://i.imgur.com/efeQ9m3.png)

**Comment by Mikaela** [comment]
That looks like only one trusted SSL fingerprint to me.

**Comment by hashworks** [comment]
That looks like I'm dumb today to me. Closed.

**Comment by Mikaela** [comment]
In case anyone else is wondering, mulltiple fingerprints look like this:

![](http://i.imgur.com/aA9gUHg.png)

*These are for irc.sorcery.net.*
