### ISSUE TITLE
updating from EPEL to source tarball

### ISSUE THREAD

**Issue by Mickroz** [znc/znc#913]
Hi,
I want to update to latest but since the epel has 1.4 as latest, i'm going to use the source tarball.
What should i backup, and how should i go through this?
At the moment my znc home folder is /var/lib/znc.

**Comment by Mikaela** [comment]
You don't lose anything by upgrading and all config files and logs etc. are in `~/.znc/moddata`.

**Comment by Mickroz** [comment]
Ok, thanks, will install and close this if succesful.

**Comment by Mickroz** [comment]
@Mikaela if i want to move the user znc to /home/znc should i just copy all content in /var/lib/znc and move it to /home/znc, download latest tarball, unrar and overwrite and then run ./configure?

**Comment by Mikaela** [comment]
> if i want to move the user znc to /home/znc should i just copy all content in /var/lib/znc 

/var/lib/znc/**.znc** (assuming that it's normal installation)

and move it to /home/znc

yes

> download latest tarball, unrar and overwrite and then run ./configure?

I don't think I understand this part, overwrite what?

**Comment by Mickroz** [comment]
yeah my bad, i don't need to overwrite anything, just unrar and ./configure.

**Comment by Mickroz** [comment]
I just had to update gcc to 4.7 http://ask.xmodulo.com/upgrade-gcc-centos.html before i could install it.
Thanks @Mikaela
