### ISSUE TITLE
Revise tabular output

### ISSUE THREAD

**Issue by jpnurmi** [znc/znc#914]
As discussed in #775, it would be nice if the massive wrapping tables were replaced with simple ChanServ-style output that looks good regardless of screen/window size, also with non-fixed-width fonts.

For example:

<pre>
    /msg *status help
    ...
    <b>RESTART</b> Restart ZNC
    <b>SHUTDOWN</b> Shutdown ZNC
    ...

    /msg *status help shutdown
    ...
    Syntax: SHUTDOWN [message]
    ...
</pre>

- introduce new commands to show more details instead of having lots of table columns (eg. listchans vs. showchan)
- reduce the amount of columns in all tables to two
- adjust CTable formatting or introduce a new type that doesn't even let add more than two "columns"
##

**Comment by jpnurmi** [comment]
It seems some users the tables, so it might be worth introducing a setting. :/ In order for this to work, the amount of columns still needs to be reduced, though.

**Comment by DarthGandalf** [comment]
Who prefers tables, and why?

**Comment by jpnurmi** [comment]
That's the impression I get from this discussion:
```
<MetaNova> something something if you're using a non-monospaced font, you're asking for things to look bad
<milky> Look buddy, us Mac users are very finicky about our pretty fonts ;P
<MetaNova> further proof you're making your own problems
<KindOne> monospaced font must cost $9.99
<MrC> I might have to side with him on this one. Not everyone wants to use monospaced fonts.
<MrC> And some clients and/or scripts will reduce extra whitespace down to one space, so even with a monospaced font it'd still look like crap.
<MetaNova> MrC: and yet, which is/are the simpler solution(s)? 1) them changing their font to make the ZNC output less ugly, 2) them accepting that, for conversations to look pretty, ZNC output looks less than fantastic, or 3) change the code of ZNC itself to change what the output looks like
<KindOne> just make the output look like chanserv/nickserv.. its always looked like shit
<milky> ^
<MrC> #2 is what usually happens. I'd like to see #3 happen in some form.
<milky> It's a pretty subjective topic and will remain
<MrC> Indeed it will.
<MrC> Though the extra line seperators for each line of hep output (as of 1.6.x) is really a step backward.
<MrC> s/hep/help/
<ZNC-Linker> MrC meant: “Though the extra line seperators for each line of help output (as of 1.6.x) is really a step backward.”
<milky> Didn't notice that and agreed
<MetaNova> MrC: I fully agree with you on that
<milky> 137 messages for help...
<MetaNova> personally, I think the output style of 1.4 was superb
<milky> Just reply with a link to the wiki that says 'RTFM'
<MrC> milky: Ha. Though, actually that might be a good idea.
```

**Comment by DarthGandalf** [comment]
Solution #943 is fine as temporary, but now it consumes lots of vertical space.
The chanserv-like example at the top would still be better.

**Comment by jaagr** [comment]
I also had problems with the output taking up too much space, making it harder for the eyes to parse the output. If you are using **irssi** you could filter out the extra dividing rows to make the output more compact.

`/ignore -regexp -pattern \+[-|=]{5,} * MSGS`

or put the following in your config file

    ignores = (
      { level = "MSGS"; pattern = "\\+[-|=]{5,}"; regexp = "yes"; }
    );
