### ISSUE TITLE
Error Compiling...

### ISSUE THREAD

**Issue by ne0ark** [znc/znc#925]
Building ZNC Perl bindings library...
modperl/ZNC.cpp: In function â€˜void _wrap_new_CPerlModule(PerlInterpreter*, CV*)â€™:
modperl/ZNC.cpp:99568:105: error: no matching function for call to â€˜CPerlModule::CPerlModule(CUser*&, CIRCNetwork*&, const CString&, const CString&, SV*&)â€™
     result = (CPerlModule *)new CPerlModule(arg1,arg2,(CString const &)*arg3,(CString const &)*arg4,arg5);
                                                                                                         ^
modperl/ZNC.cpp:99568:105: note: candidate is:
In file included from modperl/ZNC.cpp:1751:0:
./modperl/module.h:32:2: note: CPerlModule::CPerlModule(CUser*, CIRCNetwork*, const CString&, const CString&, CModInfo::EModuleType, SV*)
  CPerlModule(CUser* pUser, CIRCNetwork* pNetwork, const CString& sModName, const CString& sDataPath,
  ^
./modperl/module.h:32:2: note:   candidate expects 6 arguments, 5 provided
At global scope:
cc1plus: warning: unrecognized command line option "-Wno-reserved-user-defined-literal" [enabled by default]
make[1]: *** [modperl/ZNC.o] Error 1

**Comment by jpnurmi** [comment]
This looks like a build from the latest master. Are you doing an incremental update ie. did you just pull in the latest changes? Make sure to do a clean build, so get rid of all old intermediate files from previous builds. If you have a git clone, do ```git clean -xdf``` to start from clean table.

**Comment by ne0ark** [comment]
That did the trick thanks.

**Comment by jpnurmi** [comment]
np :)

**Comment by DarthGandalf** [comment]
This might be related to #420
