### ISSUE TITLE
How do I access "template<> void TModInfo" in a python module?

### ISSUE THREAD

**Issue by crocket** [znc/znc#926]
Because I don't have `template<> void TModInfo` in a python module,
I can't link a python module to a wiki page.

**Comment by DarthGandalf** [comment]
There is no direct access to that template. But all parameters available to C++ module via that template, are exposed to python modules too.
```python
class foo(znc.Module):
    wiki_page = '...'
```
For full list you can look at other attributes of `Module` in `znc.py`.
If one of parameters is not available this way, then it was forgotten, and it's a bug.

**Comment by crocket** [comment]
Thanks.
znc.Module has the full list of variables.
