### ISSUE TITLE
ZNC 1.6 run giving GLIBCXX_3.4.11 not found error

### ISSUE THREAD

**Issue by chaseflynn** [znc/znc#931]
znc -r                                                             
/usr/lib/libstdc++.so.6: version GLIBCXX_3.4.11 required by /usr/local/bin/znc not found

That's what I'm getting.  I created a fresh jail on FreeNAS, performed the pkg updates, etc. and followed the instructions on the ZNC wiki to install but receive the above error when I try to do anything involving the znc binary.  Any ideas?

**Comment by teward** [comment]
Did you build from source or did you use a precompiled package for it?  (I.E. how did you install it)

**Comment by chaseflynn** [comment]
I've tried so much at this point, it's hard to remember.  But I believe I
used the pkg install irc/znc.

**Comment by teward** [comment]
If it's a prepackaged-for-that-OS package, that's not really a ZNC upstream problem - likely indicates packaging problems in that specific distribution's built binaries...

**Comment by Klaas-** [comment]
you can work around the issue by setting library paths or patching the executeable
patchelf --set-rpath /usr/local/lib/gcc48 /usr/local/bin/znc

in general it's an issue in the freebsd package not znc

**Comment by DarthGandalf** [comment]
Another user shown similar error; they compiled ZNC manually on FreeBSD.

By default g++ is 4.6 there, so they used `CXX=/usr/local/bin/g++48`, but it complains about `/usr/local/lib/gcc46/libstdc++.so.6: version GLIBCXX_3.4.18 required by /usr/local/bin/znc not found`
Workaround for this: `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/gcc48` (patchelf might work too)

Alternatively, just use `CXX=clang++` instead.

So, FreeNAS package should be fixed to compile ZNC correctly.
