### ISSUE TITLE
Channels no longer removed from config despite chansaver being loaded

### ISSUE THREAD

**Issue by Robby-** [znc/znc#932]
The chansaver module is loaded, this causes the channels I join to be added in znc.conf, however, when I part these channels again, these channels are no longer removed from the config. A workaround I discovered is to do `/znc saveconfig` every time I part a channel to make sure it gets removed from the config, because when you kill the znc process and restart znc, you will be joined to the parted channels again if you didn't do the aforementioned workaround.

**Comment by elyscape** [comment]
I'm affected by this too.

**Comment by elyscape** [comment]
Found the problem.  It was introduced by commit c424bd7, specifically [line 647](https://github.com/znc/znc/blob/c424bd7acad08677f6f6140010804ef0f66ade05/src/Chan.cpp#L647).  That commit is part of PR #705, which refactors chansaver to use scheduled config writes.  Line 647 causes writes to not be scheduled if removing a channel from the config file.  It probably exists by virtue of being pasted from [line 638](https://github.com/znc/znc/blob/c424bd7acad08677f6f6140010804ef0f66ade05/src/Chan.cpp#L638), which serves to prevent scheduling writes if the key is changed but the channel isn't supposed to be in the config file anyway.
