### ISSUE TITLE
[Feature Request] Add nickchanges to flood detach

### ISSUE THREAD

**Issue by necessary129** [znc/znc#941]
Hey,
Flood detach is a great module, It detaches from the channel when its being flooded, But it doesn't detach the channel when its being flooded by nick changes, So i request that you add a flood detach function when nickchanges happen to flooddetach module

**Comment by Cajs** [comment]
Not a bad idea, especially as this type of flooding is ever more common.

**Comment by TheDoctorsLife** [comment]
issue is still open, @jpnurmi, you forgot the s

**Comment by jpnurmi** [comment]
The issue will close automatically when https://github.com/znc/znc/pull/997 is merged.
