### ISSUE TITLE
Don't suggest people to use ZNC 1.4

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#947]
```
configure: No compiler with C++11 support was found
configure: error: Either upgrade your compiler, or use ZNC 1.4
```

Recommending 1.4 is not a good idea as it's old and unsupported version, doesn't check SSL certificates (https://github.com/znc/znc/issues/156) and is vulnerable (https://github.com/znc/znc/issues/621) to [POODLE] and [FREAK].

[POODLE]:https://en.wikipedia.org/wiki/POODLE
[FREAK]:https://en.wikipedia.org/wiki/FREAK

**Comment by Mikaela** [comment]
Also noted on IRC

```
2015-04-17 12:05:45+0300 < KindOne> "Either upgrade your compiler" is just too damned generic... be more specific, id say "Upgrade your gcc too 4.7.x or newer..."
2015-04-17 12:05:54+0300 < Mikaela> ttet: still disable the colours & https://freenode.net/faq.shtml
2015-04-17 12:06:11+0300 < Mikaela> gcc isn't the only compiler, I use clang by default
```

**Comment by Mikaela** [comment]
> Clang 3.3 and later implement all of the ISO C++ 2011 standard.

via http://clang.llvm.org/cxx_status.html

I have no idea on other compilers, but as far as I am aware, gcc and clang are the most popular ones.

**Comment by RealRancor** [comment]
FYI: The new Debian Stable (aka Jessie) now ships ZNC 1.4:

https://packages.debian.org/jessie/znc

**Comment by jpnurmi** [comment]
https://github.com/znc/znc/commit/d335c3cdf63f9a83c26fac2e70a072683725f3db
