### ISSUE TITLE
Filter output of *status or other plugins - like grep does

### ISSUE THREAD

**Issue by antivirtel** [znc/znc#953]
I really like to see a filter option for ZNC, since a simple *status help output is more than a hundred lines, and it is not grouped properly (by topics of my need).

I imagine this like that:

    help | grep pattern
    SetPattern | #where

The pipe may not needed, but AFAIK it is widely known.

Thank you very much, and feel free to subscribe!

**Comment by Zarthus** [comment]
Most clients support `CTRL + F` or `/grep <search>`, However, having `help [command name]` to only print the command name help if specified, with the potential of having wildcard support, doesn't sound like a bad idea.

**Comment by antivirtel** [comment]
Sure, but what if my client isn't highlighting the results?

The other idea sounds good, but what if I want to see all command, whose takes #channel as an argument - and what about the other plugins?

**Comment by Mikaela** [comment]
`help *finger*` has been implemented with ZNC 1.6.0, so I believe this issue can be closed.

**Comment by jpnurmi** [comment]
Feel free to re-open the issue if you feel like the solution is not satisfactory.
