### ISSUE TITLE
Per-network traffic info

### ISSUE THREAD

**Issue by sim642** [znc/znc#963]
Currently ZNC can show traffic used by each user but it'd be nice if there would be separate counters for each network for an user.

**Comment by Mikaela** [comment]
I am not sure if this is what you are after, but you might find \*listsockets interesting.

**Comment by sim642** [comment]
That just lists the sockets in use for the connections but not how much traffic has gone through them.

**Comment by Cajs** [comment]
This would be a nice edition, especially for those users running VPS' on "metered bandwidth" (For example, some smaller VPS' only restricted network throughput, e.g 1gb per month).

This would aid in knowing where the data is being used.

**Comment by GLolol** [comment]
:+1: from me.
