### ISSUE TITLE
[Feature Request] Highlights via pm when afk

### ISSUE THREAD

**Issue by Justinzobel** [znc/znc#965]
Would be good to have an option that any nick highlights are sent via pm by ZNC to the user so when they login in they get PMs with any highlights while afk.

**Comment by Mikaela** [comment]
> `/msg *watch add * *highlight *%nick%*`

via http://wiki.znc.in/Watch

Of course this only works while client is attached to ZNC, so the solution would possibly be making \*watch subject to query buffers?

**Comment by Mikaela** [comment]
It was never specified if what I suggested in the previous comment was what @Justinzobel means, but at IRC this is currently being asked about and the solution to the question would be having \*watch in query buffers, so when client is attached, all highlights appear in query from \*highlight (with the example in previous comment).

**Comment by DarthGandalf** [comment]
So what exactly do you mean by afk?
If no client is connected, it will be shown to client when it connects.
If clients are connected, they all get it immediately.

**Comment by DarthGandalf** [comment]
@Mikaela it looks like @Justinzobel wants to watch highlights in channels, not in queries, but to get notified about them in query.

**Comment by Mikaela** [comment]
>  If no client is connected, it will be shown to client when it connects.

It's not on ZNC 1.7.x-git-198-e8d0dcc when one client is connected. I haven't tried quitting both cients, but I doubt that works either, if it works, this is a bug.

> @Mikaela it looks like @Justinzobel wants to watch highlights in channels, not in queries, but to get notified about them in query.

This is what I want too regardless of is my client attached or not. If it is, everything works and if it's not, I get no notifications from \*watch.

**Comment by DarthGandalf** [comment]
> > If no client is connected, it will be shown to client when it connects.

> It's not on ZNC 1.7.x-git-198-e8d0dcc when one client is connected.

If *no client* is connected. If you have a client connected, that client gets the notification, and that's it. How *watch is supposed to know the total number of your clients?

> I haven't tried quitting both cients, but I doubt that works either, if it works, this is a bug.

Well, do try, you'll be pleasantly surprised :)

**Comment by Mikaela** [comment]
> If no client is connected. If you have a client connected, that client gets the notification, and that's it.

And if \*watch would go to query buffers instead of using it's own weird mess, I would get notification even if I had this client connected.

> . How *watch is supposed to know the total number of your clients?

By looking and remembering client identifiers, `jolla` is different from `lakkaweechat` and `hexchat` is again different client.

\*chanfilter and \*chanbuffer have commands for adding clients based on identifier, maybe \*watch should do that too?

**Comment by boske88** [comment]
https://github.com/boske88/ZNC-AwayNotify

**Comment by Mikaela** [comment]
How is that different from \*watch?

**Comment by boske88** [comment]
u dont need to add user to be notifed.u recive notifications from all when u are away and u can ignore some nick who are abusing u ..

**Comment by Mikaela** [comment]
Please try to repeat that in proper English (not slang) as I am not native English speaker and I must try to guess what you mean.

If I understand correctly that only does something when I am away which is not what I want.

**Comment by boske88** [comment]
i am not native english speaker too so this is my way of speaking (watching a lot off tv shows) :p yes, u understand correctly ,mod send u private msg only when u are away...i dont know why do u need that option when u are not away, when someone says your nick on channel(when u are not away) on every client u get highlighted that channel window..

**Comment by Mikaela** [comment]
What does your English teacher think about your spelling?

I think I will be opening new issue explaining the issue as I am still lost what is wanted in this one.

**Comment by DarthGandalf** [comment]
@Justinzobel if you have the answers to questions above, please reopen.

**Comment by Mikaela** [comment]
```
2015-07-08 09:50:46+0300 < Mikaela> DarthGandalf: only repository collabators can reopen issues if it has been closed by repository collabarator or anyone else than the original opener
2015-07-08 09:51:11+0300 < DarthGandalf> They can just comment then
```
