### ISSUE TITLE
Channel matching in commands is case sensitive

### ISSUE THREAD

**Issue by fastcat** [znc/znc#969]
This is essentially a rehash of #213, looks to be caused by the switch from basic string matching to use of the wildcard matching function.

Usage of WildCmp does not lend itself to making that whole function case insensitive, so I think the solution would have to be in the CIRCNetwork::Find* methods (the nick matching ones probably ought to be case insensitive too).

**Comment by jpnurmi** [comment]
Fixed by https://github.com/znc/znc/commit/7345a6ee3ac8547da46e6906843937f8e43aed80
