### ISSUE TITLE
ZNC takes long time to timeout when server dies & option to configure it (at least for admins) would be helpful

### ISSUE THREAD

**Issue by Mikaela** [znc/znc#979]
According to @DarthGandalf the current timeout is around 500 seconds that is quite long. I think it should be around 120 seconds and even better, configurable by at least admins.
##

**Comment by teward** [comment]
I'd feel a little better with 180 or 240 seconds, or if it were configurable (my two cents)

**Comment by Mikaela** [comment]
180 seems like a good number, but 240 might again be a little too long.

**Comment by Mikaela** [comment]
It appears to be specified in https://github.com/znc/znc/blob/znc-1.6.0/include/znc/IRCNetwork.h#L47-57 and requires some other numbers to be changed too unless I entirely misunderstand the comment.

**Comment by GLolol** [comment]
:+1: for configurability and a lower default.

**Comment by t3chguy** [comment]
:+1:

**Comment by Mikaela** [comment]
Opinions on https://github.com/znc/znc/pull/980 ? (Ref, not closing, because not configurable.)

**Comment by teward** [comment]
@Mikaela I think that #980 was just merged a few minutes ago...

**Comment by Mikaela** [comment]
> Mikaela I think that #980 was just merged a few minutes ago...

Yes, I do get email notifications about merged pull requests and as I said in my previous comment, I am not closing this with it, because that pull request is not configurable.

**Comment by teward** [comment]
@Mikaela: Yes I know that - I was responding to your "opinions on that" question, not implying this should be closed.

**Comment by ransagy** [comment]
A bit old but very relevant for me; This would certainly help my issues detailed in #487.
I'll just lower the frequency and compile for now, but +1 from me for making this configurable.
